window.POST_TRANSLATIONS = {
  pl: {
    roi_meta_desc: "Dlaczego warto automatyzować stanowiska produkcyjne? Poznaj szczegółowy przewodnik po obliczaniu wskaźnika ROI, redukcji kosztów operacyjnych i optymalizacji OEE w przemyśle.",
    roi_page_title: "Dlaczego warto automatyzować stanowiska produkcyjne i jak obliczyć ROI? – NEXAUT",
    roi_h1: "Dlaczego warto automatyzować stanowiska i&nbsp;jak precyzyjnie ocenić zwrot z&nbsp;inwestycji (ROI)?",
    roi_intro: "Automatyzacja procesów produkcyjnych przestała być zarezerwowana wyłącznie dla gigantów branży motoryzacyjnej. W&nbsp;dzisiejszych realiach przemysłowych to&nbsp;podstawowy warunek utrzymania konkurencyjności, stabilności jakościowej oraz rentowności zakładu.",
    roi_h2_1: "Wyzwania współczesnej produkcji: Dlaczego praca manualna się nie opłaca?",
    roi_p1_1: "Dynamicznie rosnące koszty pracy, wysoka rotacja pracowników oraz deficyt wykwalifikowanej kadry inżynieryjnej i&nbsp;operatorskiej to&nbsp;problemy, z&nbsp;którymi zmaga się większość zakładów przemysłowych. Czynnik ludzki, choć niezastąpiony w&nbsp;zadaniach wymagających elastyczności i&nbsp;kreatywności, bywa najsłabszym ogniwem w&nbsp;powtarzalnych, monotematycznych procesach technologicznych.",
    roi_p1_2: "Zautomatyzowanie stanowiska montażowego, spawalniczego czy paletyzującego pozwala na&nbsp;wyeliminowanie wahań jakościowych wynikających z&nbsp;zmęczenia operatora, absencji chorobowych czy błędów popełnianych podczas rutynowych czynności.",
    roi_h2_2: "Kluczowe korzyści z&nbsp;wdrożenia automatyzacji i&nbsp;robotyzacji",
    roi_p2_intro: "Inwestycja w&nbsp;nowoczesne cele zautomatyzowane lub stanowiska zintegrowane ze&nbsp;sterownikami PLC przekłada się bezpośrednio na&nbsp;wszystkie obszary działalności przedsiębiorstwa:",
    roi_li_2_1: "<strong>Maksymalizacja wskaźnika OEE (Overall Equipment Effectiveness):</strong> Maszyny mogą pracować w&nbsp;trybie 24/7 bez spadku wydajności na&nbsp;zmianach nocnych i&nbsp;bez konieczności przewidzianych przepisami przerw.",
    roi_li_2_2: "<strong>Drastyczna redukcja braków i&nbsp;reklamacji:</strong> Powtarzalność pozycjonowania robotów przemysłowych sięga setnych części milimetra, co&nbsp;sprowadza poziom odpadów produkcyjnych blisko zera.",
    roi_li_2_3: "<strong>Skrócenie czasu cyklu (Cycle Time):</strong> Precyzja i&nbsp;zsynchronizowane napędy wykonują operacje znacznie szybciej niż najsprawniejszy operator manualny.",
    roi_li_2_4: "<strong>Podniesienie poziomu bezpieczeństwa (Safety):</strong> Zastosowanie wygrodzeń ochronnych, kurtyn świetlnych oraz zaawansowanych modułów Safety PLC pozwala wyeliminować ryzyko wypadków na&nbsp;stanowiskach niebezpiecznych.",
    roi_callout_title: "Wskazówka Inżyniera NEXAUT",
    roi_callout_text: "Przy ocenie opłacalności automatyzacji nie ograniczaj się wyłącznie do&nbsp;porównania pensji operatora z&nbsp;kosztem zakupu robota. Uwzględnij tzw. ukryte koszty pracy manualnej: koszty rekrutacji, szkoleń, środków ochrony osobistej, rotacji pracowników oraz strat wywołanych przestojami z&nbsp;powodu braku obsady.",
    roi_img2_caption: "Rys 1. Porównanie skumulowanych kosztów operacyjnych stanowiska manualnego vs&nbsp;zautomatyzowanego w&nbsp;perspektywie 36&nbsp;miesięcy.",
    roi_h2_3: "Jak prawidłowo obliczyć zwrot z&nbsp;inwestycji (ROI)?",
    roi_p3_1: "Wskaźnik ROI (Return on Investment) określa, w&nbsp;jakim czasie wygenerowane zyski pokryją poniesione nakłady inwestycyjne. Standardowy wzór na&nbsp;ROI w&nbsp;automatyce przemysłowej bazuje na&nbsp;zestawieniu nakładów inwestycyjnych (CAPEX) z&nbsp;rocznymi oszczędnościami operacyjnymi (OPEX).",
    roi_formula_title: "Podstawowa formuła zwrotu z inwestycji:",
    roi_h2_4: "Co uwzględnić po stronie CAPEX i OPEX?",
    roi_p4_1: "Aby kalkulacja była wiarygodna i&nbsp;akceptowalna przez zarząd przedsiębiorstwa, należy precyzyjnie wylistować komponenty obu składowych:",
    roi_li_4_1: "<strong>Nakłady początkowe (CAPEX):</strong> Koszt zakupu robotów, osprzętu, sterowników PLC, paneli HMI, wykonania projektu elektrycznego i&nbsp;mechanicznego, montażu, programowania oraz wdrożenia na&nbsp;obiekcie.",
    roi_li_4_2: "<strong>Oszczędności operacyjne (OPEX):</strong> Redukcja bezpośrednich kosztów robocizny, spadek zużycia surowców dzięki dokładności dozowania, brak kosztów poprawek i&nbsp;reklamacji jakościowych.",
    roi_li_4_3: "<strong>Bieżące koszty utrzymania (OpEx Maszyny):</strong> Zużycie energii elektrycznej, regularne przeglądy serwisowe, wymiana części eksploatacyjnych oraz ewentualne szkolenia nowych pracowników.",
    roi_h2_faq: "Często Zadawane Pytania (FAQ)",
    roi_faq_q1: "Ile zazwyczaj wynosi okres zwrotu z inwestycji (ROI) w automatyzację?",
    roi_faq_a1: "W&nbsp;większości standardowych aplikacji przemysłowych (paletyzacja, zautomatyzowane stanowiska spawalnicze, montażowe) okres zwrotu wynosi od&nbsp;12 do&nbsp;36 miesięcy. Przy pracy w&nbsp;systemie trójzmianowym ROI często następuje już po&nbsp;niespełna roku.",
    roi_faq_q2: "Czy automatyzacja opłaca się przy niskoseryjnej produkcji?",
    roi_faq_a2: "Tak. Dzięki elastycznym systemom sterowania (np. TIA Portal, Allen-Bradley) oraz wykorzystaniu robotów współpracujących (cobotów), przezbrajanie stanowiska pod nowy detal trwa od&nbsp;kilku do&nbsp;kilkunastu minut, co&nbsp;czyni automatyzację wysoce opłacalną także dla krótkich serii.",
    roi_faq_q3: "Jakie jest pierwsze krok do przetestowania opłacalności przed zakupem?",
    roi_faq_a3: "Zalecamy przeprowadzenie przedwdrożeniowego audytu technologicznego oraz symulacji procesowej (np. w&nbsp;ramach Wirtualnego Uruchomienia – VIBN). Pozwala to&nbsp;precyzyjnie wyliczyć czas cyklu oraz zweryfikować założenia zanim zostaną wydane pierwsze fundusze na&nbsp;sprzęt.",
    roi_h2_5: "Podsumowanie – Zbuduj przewagę techniczną z NEXAUT",
    roi_p5_1: "Automatyzacja stanowisk produkcyjnych to&nbsp;strategiczna decyzja, która zabezpiecza zakład przed kryzysami kadrowymi i&nbsp;presją cenową rynku. Zespół inżynierów NEXAUT wspiera firmy na&nbsp;każdym etapie – od&nbsp;audytu możliwości technologicznych, przez wyliczenie wskaźników opłacalności, aż&nbsp;po projektowanie, programowanie PLC/robotów i&nbsp;ostateczne uruchomienie stanowiska na&nbsp;linii."
  },

  en: {
    roi_meta_desc: "Why automate workstations? Read our comprehensive guide on calculating ROI, reducing operational costs, and optimizing OEE in manufacturing.",
    roi_page_title: "Why Automate Workstations & Calculate ROI? – NEXAUT",
    roi_h1: "Why Automate Workstations and How to Accurately Calculate ROI?",
    roi_intro: "Process automation is no longer exclusive to automotive giants. In modern manufacturing, it is a fundamental requirement to maintain competitiveness, consistent quality, and plant profitability.",
    roi_h2_1: "Modern Manufacturing Challenges: Why Manual Labor Fall Short",
    roi_p1_1: "Rapidly rising labor costs, high employee turnover, and shortages of skilled engineers and operators are major hurdles for manufacturing facilities. The human element, though vital for flexible tasks, often represents the weakest link in repetitive, high-precision operations.",
    roi_p1_2: "Automating assembly, welding, or palletizing cells eliminates quality fluctuations caused by fatigue, absenteeism, or routine operational errors.",
    roi_h2_2: "Key Benefits of Automation and Robotics",
    roi_p2_intro: "Investing in modern automated cells or PLC-integrated workstations directly impacts every dimension of plant performance:",
    roi_li_2_1: "<strong>Maximizing OEE (Overall Equipment Effectiveness):</strong> Machinery runs 24/7 without performance dips during night shifts or mandatory break times.",
    roi_li_2_2: "<strong>Drastic Scrap & Defect Reduction:</strong> Industrial robot positioning repeatability reaches hundredths of a millimeter, bringing scrap rates close to zero.",
    roi_li_2_3: "<strong>Cycle Time Reduction:</strong> Precision-driven synchronized drives execute operations significantly faster than manual workers.",
    roi_li_2_4: "<strong>Enhanced Workplace Safety:</strong> Safety fences, light curtains, and integrated Safety PLCs eliminate injury risks in hazardous areas.",
    roi_callout_title: "NEXAUT Engineering Pro-Tip",
    roi_callout_text: "When evaluating ROI, don't just compare worker wages against robot acquisition costs. Include hidden manual labor overheads: recruitment fees, training costs, PPE equipment, turnover losses, and downtime caused by staffing shortages.",
    roi_img2_caption: "Fig 1. Cumulative operational cost comparison: Manual vs. Automated workstation over a 36-month timeline.",
    roi_h2_3: "How to Calculate Return on Investment (ROI) Accurately?",
    roi_p3_1: "ROI indicates how quickly generated savings cover initial investments. Standard industrial automation ROI models balance initial capital expenditures (CAPEX) against ongoing operational savings (OPEX).",
    roi_formula_title: "Core ROI Calculation Formulas:",
    roi_h2_4: "What to Include in CAPEX vs. OPEX?",
    roi_p4_1: "To deliver a credible calculation for executive approval, carefully itemize both sides of the equation:",
    roi_li_4_1: "<strong>Capital Expenditure (CAPEX):</strong> Robot purchasing, tooling, PLC/HMI hardware, electrical & mechanical engineering, assembly, programming, and site commissioning.",
    roi_li_4_2: "<strong>Operational Savings (OPEX):</strong> Labor cost reductions, lower raw material waste due to dosing precision, and elimination of rework or warranty claims.",
    roi_li_4_3: "<strong>Ongoing Maintenance Costs:</strong> Power consumption, scheduled preventative maintenance, spare parts, and occasional operator training.",
    roi_h2_faq: "Frequently Asked Questions (FAQ)",
    roi_faq_q1: "What is the typical payback period for workstation automation?",
    roi_faq_a1: "For standard applications (palletizing, robotic welding, automated assembly), the typical payback period ranges between 12 and 36 months. In 3-shift operations, ROI is frequently achieved in under 12 months.",
    roi_faq_q2: "Is automation profitable for low-volume production?",
    roi_faq_a2: "Yes. With flexible control systems (e.g. TIA Portal, Allen-Bradley) and cobots, changeovers take only minutes, making automation highly profitable even for small production batches.",
    roi_faq_q3: "What is the best first step to verify feasibility before purchasing hardware?",
    roi_faq_a3: "We recommend a technical audit and process simulation (such as Virtual Commissioning – VIBN). This allows precise cycle time calculation and concept validation before capital commitment.",
    roi_h2_5: "Summary – Build Your Technical Advantage with NEXAUT",
    roi_p5_1: "Workstation automation is a strategic investment shielding your plant against labor shortages and market pressure. NEXAUT engineers guide you through every stage – from feasibility audits and ROI estimations to PLC/robot programming and final site integration."
  },

  de: {
    roi_meta_desc: "Warum Arbeitsplätze automatisieren? Erfahren Sie alles über ROI-Berechnung, Betriebskostensenkung und OEE-Optimierung in der Industrie.",
    roi_page_title: "Arbeitsplatz-Automatisierung & ROI-Berechnung – NEXAUT",
    roi_h1: "Warum lohnt sich die Automatisierung von Arbeitsplätzen und wie berechnet man den ROI?",
    roi_intro: "Prozessautomatisierung ist längst nicht mehr nur der Automobilindustrie vorbehalten. In der modernen Produktion ist sie Grundvoraussetzung für Wettbewerbsfähigkeit, Qualitätskonstanz und Rentabilität.",
    roi_h2_1: "Herausforderungen der modernen Produktion: Warum manuelle Arbeit unattraktiv wird",
    roi_p1_1: "Steigende Lohnkosten, hohe Fluktuation und der Mangel an Fachkräften belasten Industrieunternehmen. Der Faktor Mensch ist bei flexiblen Aufgaben unersetzlich, stellt jedoch bei monotonen Hochpräzisionsprozessen oft das schwächste Glied dar.",
    roi_p1_2: "Die Automatisierung von Montage-, Schweiß- oder Palettierstationen eliminiert Qualitätsschwankungen durch Ermüdung, Ausfallzeiten oder Routinefehler.",
    roi_h2_2: "Kerneffekte von Automatisierung und Robotik",
    roi_p2_intro: "Die Investition in automatisierte Zellen oder PLC-integrierte Arbeitsplätze wirkt sich direkt auf alle Unternehmensbereiche aus:",
    roi_li_2_1: "<strong>Maximierung der Gesamtanlageneffektivität (OEE):</strong> Maschinen arbeiten rund um die Uhr ohne Leistungseinbußen in Nachtschichten oder gesetzliche Pausen.",
    roi_li_2_2: "<strong>Ausschussreduzierung:</strong> Die Wiederholgenauigkeit von Industrie-Robotern liegt im Hundertstel-Millimeter-Bereich und reduziert Ausschuss auf nahezu Null.",
    roi_li_2_3: "<strong>Taktzeitverkürzung (Cycle Time):</strong> Präzise synchrone Antriebe führen Bewegungen deutlich schneller aus als manuelle Bediener.",
    roi_li_2_4: "<strong>Arbeitssicherheit (Safety):</strong> Schutzzäune, Lichtgitter und Safety-SPS-Module eliminieren Unfallrisiken an gefährlichen Arbeitsplätzen.",
    roi_callout_title: "NEXAUT Ingenieur-Tipp",
    roi_callout_text: "Berücksichtigen Sie bei der ROI-Berechnung nicht nur Löhne vs. Roboterpreis. Kalkulieren Sie verdeckte Kosten ein: Rekrutierung, Schulungen, PSA-Ausrüstung und Stillstandszeiten durch Personalmangel.",
    roi_img2_caption: "Abb. 1. Kumulierte Betriebskosten im Vergleich: Manueller vs. Automatisierter Arbeitsplatz über 36 Monate.",
    roi_h2_3: "Wie berechnet man den Return on Investment (ROI) korrekt?",
    roi_p3_1: "Der ROI gibt an, wann erzielte Einsparungen die Investition decken. Die Standardformel vergleicht die Investitionsausgaben (CAPEX) mit den jährlichen Betriebseinsparungen (OPEX).",
    roi_formula_title: "Grundlegende ROI-Formeln:",
    roi_h2_4: "Was gehört zu CAPEX und OPEX?",
    roi_p4_1: "Für eine valide Entscheidungsvorlage für die Geschäftsführung müssen beide Seiten detailliert aufgeschlüsselt werden:",
    roi_li_4_1: "<strong>Investitionskosten (CAPEX):</strong> Roboter, Peripherie, SPS/HMI-Hardware, Elektro- & Mechanikkonstruktion, Montage, Programmierung und Inbetriebnahme.",
    roi_li_4_2: "<strong>Betriebseinsparungen (OPEX):</strong> Einsparungen bei Direktlöhnen, weniger Materialausschuss und Wegfall von Nacharbeit oder Reklamationen.",
    roi_li_4_3: "<strong>Laufende Betriebskosten:</strong> Stromverbrauch, regelmäßige Wartung, Ersatzteile und gelegentliche Bediener-Schulungen.",
    roi_h2_faq: "Häufig gestellte Fragen (FAQ)",
    roi_faq_q1: "Wie lange dauert die Amortisation (ROI) in der Praxis?",
    roi_faq_a1: "Bei Standardanwendungen (Palettierung, Schweißen, Montage) liegt die Amortisationszeit meist zwischen 12 und 36 Monaten. Im 3-Schicht-Betrieb wird der ROI oft in unter 12 Monaten erreicht.",
    roi_faq_q2: "Lohnt sich die Automatisierung bei kleinen Serien?",
    roi_faq_a2: "Ja. Dank flexibler Steuerungssysteme (z. B. TIA Portal, Allen-Bradley) und Cobots dauern Umrüstungen nur wenige Minuten, was die Automatisierung auch für Kleinserien hochprofitabel macht.",
    roi_faq_q3: "Was ist der erste Schritt zur Feststellung der Machbarkeit?",
    roi_faq_a3: "Wir empfehlen ein technologisches Audit sowie eine Prozesssimulation (z. B. Virtuelle Inbetriebnahme – VIBN), um Taktzeiten und Auslegung vor Hardwarekäufen exakt zu validieren.",
    roi_h2_5: "Zusammenfassung – Technologischer Vorsprung mit NEXAUT",
    roi_p5_1: "Die Automatisierung von Arbeitsplätzen ist eine strategische Entscheidung gegen Fachkräftemangel und Marktdruck. Das NEXAUT-Team begleitet Sie von der Machbarkeitsanalyse über ROI-Kalkulationen bis hin zur SPS-/Roboter-Programmierung und Inbetriebnahme vor Ort."
  }
};