window.POST_TRANSLATIONS = {
  pl: {
    cobot_meta_desc: "Poznaj wytyczne norm ISO 10218 oraz ISO/TS 15066 dotyczące bezpieczeństwa cobotów. Sprawdź, jak przeprowadzić audyt i certyfikację CE stanowiska bez wygrodzeń.",
    cobot_page_title: "Bezpieczeństwo cobotów – Wytyczne ISO i audyt stanowiska – NEXAUT",
    cobot_h1: "Bezpieczeństwo cobotów – wytyczne ISO i&nbsp;audyt stanowiska pracy",
    cobot_intro: "Wielu przedsiębiorców błędnie zakłada, że kupując „robota współpracującego” (cobota), automatycznie zwolnieni są ze stosowania osłon, kurtyn świetlnych i skanerów bezpieczeństwa. To niebezpieczny mit. Certyfikacja i bezpieczeństwo nie dotyczą samego ramienia robota, lecz całego stanowiska zrobotyzowanego wraz z chwytakiem i przenoszonym detalem.",
    cobot_h2_1: "1. Mit „bezpiecznego robota” a rzeczywistość prawna (ISO 10218 i ISO/TS 15066)",
    cobot_p1_1: "Sam cobot jako maszyna nieukończona spełnia normę PN-EN ISO 10218-1. Jednak z chwilą zamontowania na nim narzędzia (np. ostrego chwytaka pneumatycznego) i pobrania detalu (np. arkusza blachy), tworzymy nową maszynę w rozumieniu Dyrektywy Maszynowej (lub rozporządzenia Machinery Regulation). Integrator ma obowiązek przeprowadzić pełną ocenę ryzyka zgodną z normą specyfikacji technicznej ISO/TS 15066.",
    cobot_h2_2: "2. Cztery tryby współpracy człowieka z robotem",
    cobot_p2_1: "Norma ISO 10218 wymienia cztery dopuszczalne metody zapewnienia bezpieczeństwa na stanowiskach zrobotyzowanych. W praktyce wdrażania cobotów najistotniejsze są dwa ostatnie tryby:",
    cobot_callout_title: "Złota Zasada Inżyniera NEXAUT",
    cobot_callout_text: "Tryb PFL (Power and Force Limiting) bez wygrodzeń wymaga obowiązkowo przeprowadzenia walidacji i fizycznych pomiarów siły uderzenia za pomocą certyfikowanego siłomierza (np. GKS Gissler / PRÜFTECHNIK). Pomiary wykonuje się dla każdej wrażliwej części ciała operatora wyznaczonej w ocenie ryzyka!",
    cobot_h2_3: "3. Pomiary siły i nacisku – progi biomechaniczne",
    cobot_p3_1: "Załącznik A normy ISO/TS 15066 określa dopuszczalne wartości graniczne siły (N) i ciśnienia/nacisku (N/cm²) dla 29 obszarów ludzkiego ciała (z podziałem na kontakt dozwolony i niedozwolony, np. głowa i szyja są całkowicie wyłączone ze stref kolizyjnych). Jeżeli zmierzona podczas testów zderzeniowych siła przekracza limity, konieczna jest zmiana trajektorii, zmniejszenie prędkości lub zastosowanie miękkich osłon amortyzujących.",
    cobot_h2_4: "4. Certyfikacja CE stanowiska zrobotyzowanego",
    cobot_p4_1: "Pozytywny wynik audytu bezpieczeństwa, kompletna dokumentacja oceny ryzyka oraz protokół pomiarowy stanowią podstawę do wystawienia Deklaracji Zgodności WE/UE oraz naniesienia tabliczki ze znakiem CE na całe stanowisko zrobotyzowane. Tylko w ten sposób pracodawca spełnia wymagania prawne i chroni się przed konsekwencjami ewentualnych wypadków przy pracy.",
    cobot_h2_faq: "Często Zadawane Pytania (FAQ)",
    cobot_faq_q1: "Czy do każdego cobota muszę stawiać ogrodzenie ochronne?",
    cobot_faq_a1: "Nie do każdego, ale zależy to od oceny ryzyka. Jeśli narzędzie robota (np. nóż, palnik, ostry chwytak) lub przenoszony element stwarza zagrożenie dla zdrowia, stanowisko musi posiadać osłony lub optoelektroniczne sensory bezpieczeństwa (np. skanery laserowe).",
    cobot_faq_q2: "Kto odpowiada za bezpieczeństwo i nadanie znaku CE dla stanowiska z cobotem?",
    cobot_faq_a2: "Za bezpieczeństwo całości odpowiada Integrator (firma wdrażająca aplikację) lub Zakład Przemysłowy, jeśli buduje stanowisko we własnym zakresie. Producent samego ramienia cobota dostarcza jedynie deklarację włączenia maszyny nieukończonej.",
    cobot_faq_q3: "W jaki sposób inżynierowie NEXAUT pomagają w bezpiecznym wdrażaniu cobotów?",
    cobot_faq_a3: "Przeprowadzamy kompleksowe audyty bezpieczeństwa istniejących i nowych stanowisk zrobotyzowanych, wykonujemy pomiary siły kolizji zgodnie z ISO/TS 15066, sporządzamy ocenę ryzyka oraz przygotowujemy pełną dokumentację do deklaracji CE.",
    cobot_h2_5: "Podsumowanie – Zadbaj o pełne bezpieczeństwo i zgodność z przepisami",
    cobot_p5_1: "Coboty oferują niespotykaną dotąd elastyczność w automatyzacji procesów, jednak wyeliminowanie tradycyjnych ogrodzeń nakłada obowiązek rzetelnego audytu bezpieczeństwa. Skontaktuj się z ekspertami NEXAUT, aby upewnić się, że Twoje stanowiska zrobotyzowane są w 100% bezpieczne dla pracowników i zgodne z normami ISO!"
  },

  en: {
    cobot_meta_desc: "Discover ISO 10218 and ISO/TS 15066 safety guidelines for cobots. Learn how to perform safety audits and CE certification for unshielded cells.",
    cobot_page_title: "Cobot Safety – ISO Guidelines & Workstation Auditing – NEXAUT",
    cobot_h1: "Cobot Safety – ISO Guidelines and Workstation Auditing",
    cobot_intro: "A cobot alone doesn't guarantee a fence-free setup. Safety certification applies to the complete robotic cell—including the end-effector tool and carried payload—not just the standalone robot arm.",
    cobot_h2_1: "1. The 'Inherently Safe Robot' Myth vs Legal Reality (ISO 10218 & ISO/TS 15066)",
    cobot_p1_1: "As partly completed machinery, a standalone cobot arm complies with EN ISO 10218-1. However, once equipped with a gripper or payload, a new machine is formed under the Machinery Regulation. Integrators must perform a full risk assessment according to ISO/TS 15066.",
    cobot_h2_2: "2. Four Modes of Human-Robot Collaboration",
    cobot_p2_1: "ISO 10218 outlines four collaborative operational modes. In cobot applications, two modes are particularly relevant:",
    cobot_callout_title: "NEXAUT Golden Engineering Rule",
    cobot_callout_text: "Unfenced Power and Force Limiting (PFL) mode mandates physical force measurements using certified collision force meters (e.g., GKS / PRÜFTECHNIK). Measurements must cover all body areas defined in the risk assessment!",
    cobot_h2_3: "3. Force & Pressure Measurements – Biomechanical Limits",
    cobot_p3_1: "Annex A of ISO/TS 15066 specifies maximum force (N) and pressure (N/cm²) thresholds across 29 human body regions (head/neck contact is strictly forbidden). If collision measurements exceed thresholds, speed reduction or padding is required.",
    cobot_h2_4: "4. CE Certification for Robotic Workstations",
    cobot_p4_1: "A successful safety audit, risk assessment file, and force measurement report serve as the foundation for the EC Declaration of Conformity and CE marking for the entire robotic cell.",
    cobot_h2_faq: "Frequently Asked Questions (FAQ)",
    cobot_faq_q1: "Do I always need perimeter fencing for a cobot?",
    cobot_faq_a1: "Not always, but it depends on the risk assessment. If the gripper or part handled is sharp, hot, or dangerous, hard guarding or safety laser scanners are mandatory.",
    cobot_faq_q2: "Who is responsible for the overall CE marking of a cobot cell?",
    cobot_faq_a2: "The System Integrator (or end-user constructing the cell in-house) bears legal responsibility for CE marking. The robot arm manufacturer only provides a Declaration of Incorporation.",
    cobot_faq_q3: "How does NEXAUT assist with safe cobot deployments?",
    cobot_faq_a3: "We perform comprehensive safety audits, ISO/TS 15066 impact force testing, risk assessments, and prepare full technical documentation for CE conformity.",
    cobot_h2_5: "Summary – Ensure Full Compliance and Operator Safety",
    cobot_p5_1: "Cobots deliver unprecedented automation flexibility, but eliminating safety fences demands rigorous compliance testing. Contact NEXAUT experts to ensure your robotic cells are 100% compliant and safe!"
  },

  de: {
    cobot_meta_desc: "Erfahren Sie mehr über ISO 10218 und ISO/TS 15066 Richtlinien für Cobot-Sicherheit. So führen Sie ein Sicherheitsaudit und eine CE-Zertifizierung durch.",
    cobot_page_title: "Cobot-Sicherheit – ISO-Richtlinien & Arbeitsplatz-Audit – NEXAUT",
    cobot_h1: "Cobot-Sicherheit – ISO-Richtlinien und Arbeitsplatz-Audit",
    cobot_intro: "Ein Cobot allein garantiert keine zaunfreie Roboterzelle. Die CE-Kennzeichnung und Sicherheitsbewertung gelten für das Gesamtsystem – einschließlich Greifer und Werkstück.",
    cobot_h2_1: "1. Mythos 'sicherer Roboter' vs. rechtliche Realität (ISO 10218 & ISO/TS 15066)",
    cobot_p1_1: "Als unvollständige Maschine erfüllt ein Cobot-Arm die EN ISO 10218-1. Nach Anbau von Greifer und Werkstück entsteht eine vollständige Maschine. Integratoren müssen eine Risikobeurteilung nach ISO/TS 15066 durchführen.",
    cobot_h2_2: "2. Vier Modi der Mensch-Roboter-Kollaboration",
    cobot_p2_1: "Die Norm ISO 10218 definiert vier kollaborative Betriebsarten. Für Cobots sind zwei Modi besonders entscheidend:",
    cobot_callout_title: "Goldene NEXAUT Ingenieur-Regel",
    cobot_callout_text: "Der schutzzaunlose PFL-Betrieb (Power and Force Limiting) erfordert zwingend Kraft- und Druckmessungen mit kalibrierten Messgeräten für alle in der Risikobeurteilung identifizierten Körperregionen!",
    cobot_h2_3: "3. Kraft- und Druckmessungen – Biomechanische Grenzwerte",
    cobot_p3_1: "Anhang A der ISO/TS 15066 legt Grenzwerte für Kraft (N) und Druck (N/cm²) für 29 Körperzonen fest (Kopf- und Halsbereich ausgeschlossen). Überschreiten die Messwerte die Grenzen, müssen Geschwindigkeiten reduziert oder Dämpfungen angebracht werden.",
    cobot_h2_4: "4. CE-Zertifizierung der Roboterzelle",
    cobot_p4_1: "Sicherheitsaudit, Risikobeurteilung und Kraftmessprotokolle sind die Grundlage für die EG-Konformitätserklärung und das CE-Kennzeichen der gesamten Roboterzelle.",
    cobot_h2_faq: "Häufig gestellte Fragen (FAQ)",
    cobot_faq_q1: "Muss für jeden Cobot ein Schutzzaun errichtet werden?",
    cobot_faq_a1: "Nicht zwingend, es hängt von der Risikobeurteilung ab. Bei scharfen Werkzeugen oder gefährlichen Werkstücken sind Schutztreffervorrichtungen oder Laserscanner erforderlich.",
    cobot_faq_q2: "Wer haftet für die CE-Kennzeichnung der Cobot-Applikation?",
    cobot_faq_a2: "Der Systemintegrator (oder der Betreiber bei Eigenbau) trägt die rechtliche Verantwortung. Der Roboterhersteller liefert lediglich eine Einbauerklärung.",
    cobot_faq_q3: "Wie unterstützt NEXAUT bei sicheren Cobot-Integrationen?",
    cobot_faq_a3: "Wir bieten Sicherheitsaudits, Kraftmessungen nach ISO/TS 15066, Risikobeurteilungen und die Erstellung der vollständigen CE-Dokumentation an.",
    cobot_h2_5: "Zusammenfassung – Maximale Sicherheit und Normenkonformität",
    cobot_p5_1: "Cobots bieten hohe Flexibilität, erfordern aber fundierte Sicherheitskonzepte ohne Schutzzaun. Kontaktieren Sie das NEXAUT-Team für die Auditierung Ihrer Roboterzelle!"
  }
};