window.POST_TRANSLATIONS = {
  pl: {
    reg_meta_desc: "Automatyzacja procesów w&nbsp;okręgach przemysłowych: Rzeszów, Legnica, Bydgoszcz, Szczecin. Poznaj specyfikę Doliny Lotniczej, Zagłębia Miedziowego i&nbsp;branży morskiej z&nbsp;NEXAUT.",
    reg_page_title: "Automatyzacja Procesów: Rzeszów, Legnica, Bydgoszcz, Szczecin – NEXAUT",
    reg_h1: "Automatyzacja procesów w&nbsp;kluczowych okręgach: Rzeszów, Legnica, Bydgoszcz i&nbsp;Szczecin",
    reg_intro: "Polska mapa przemysłowa charakteryzuje się ogromnym zróżnicowaniem technologicznym. Od&nbsp;rygorystycznych norm bezpieczeństwa w&nbsp;rzeszowskiej Dolinie Lotniczej, przez trudne warunki środowiskowe Zagłębia Miedziowego wokół Legnicy, po&nbsp;przetwórstwo tworzyw w&nbsp;Bydgoszczy i&nbsp;przemysł morski w&nbsp;Szczecinie – automatyzacja musi być idealnie szyta na&nbsp;miarę specyfiki danego regionu.",
    reg_h2_1: "1. Regionalne huby przemysłowe i&nbsp;ich unikalne wyzwania",
    reg_p1_1: "Skuteczny projekt automatyzacji wymaga dogłębnego zrozumienia specyfiki lokalnego rynku przemysłowego:",
    
    // Huby
    reg_hub1_title: "Dolina Lotnicza &amp; Mikromaszyny",
    reg_hub1_desc: "Sektor lotniczy i&nbsp;precyzyjny (AS9100). Automatyczne tendrowanie maszyn CNC, robotyzacja szlifowania i&nbsp;polerowania łopatek turbin oraz&nbsp;pełna identyfikowalność (Traceability).",
    reg_hub2_title: "Zagłębie Miedziowe &amp; Ciężki Przemysł",
    reg_hub2_desc: "Hutnictwo, przemysł wydobywczy oraz&nbsp;komponenty automotive. Wymagania dotyczące wysokiego udźwigu (Heavy-Duty), stopnia ochrony IP67/IP68 i&nbsp;odporności na&nbsp;wysokie temperatury.",
    reg_hub3_title: "Polimerowe Zagłębie &amp; Narzędziownie",
    reg_hub3_desc: "Przetwórstwo tworzyw sztucznych i&nbsp;produkcja form wtryskowych. Odbieranie wyprasek przez roboty liniowe, etykietowanie IML i&nbsp;kontrola jakości wizyjnej w&nbsp;czasie rzeczywistym.",
    reg_hub4_title: "Przemysł Morski &amp; Offshore Wind",
    reg_hub4_desc: "Produkcja konstrukcji wielkogabarytowych dla energetyki wiatrowej oraz&nbsp;logistyka portowa. Zrobotyzowane ukosowanie, spawanie łukowe i&nbsp;zautomatyzowany transport ciężki.",

    reg_h2_2: "2. Odpowiedź automatyki na&nbsp;specyficzne wymagania gałęziowe",
    reg_p2_1: "Nowoczesne systemy sterowania i&nbsp;stanowiska zrobotyzowane dostosowuje się bezpośrednio pod profile produkcyjne poszczególnych regionów:",
    reg_li_1: "<strong class=\"text-white\">Integracja z&nbsp;maszynami CNC i&nbsp;centrami obróbczymi:</strong> Automatyczne załadunki i&nbsp;wyładunki detali przy użyciu robotów 6-osiowych integrowanych przez protokoły Profinet / OPC UA.",
    reg_li_2: "<strong class=\"text-white\">Roboty Heavy-Duty oraz&nbsp;spawanie wielkogabarytowe:</strong> Stanowiska spawalnicze z&nbsp;torowiskami i&nbsp;pozycjonerami dedykowane do&nbsp;trudnych warunków środowiskowych.",
    reg_li_3: "<strong class=\"text-white\">Autonomiczna kontrola jakości wizyjnej:</strong> Systemy oparte na&nbsp;sieciach neuronowych (Deep Learning) wyłapujące skazy powierzchniowe na&nbsp;wtryskanych elementach plastikowych czy&nbsp;odlewach.",
    reg_li_4: "<strong class=\"text-white\">Systemy SCADA i&nbsp;zbieranie danych fabrycznych:</strong> Oprogramowanie monitorujące wydajność OEE w&nbsp;rozproszonych zakładach produkcyjnych.",

    reg_callout_title: "NEXAUT – Twój Ogólnopolski Partner w&nbsp;Integracji Automatyki",
    reg_callout_text: "Niezależnie od&nbsp;lokalizacji – od&nbsp;Rzeszowa i&nbsp;Legnicy po&nbsp;Bydgoszcz i&nbsp;Szczecin – inżynierowie NEXAUT dostarczają układy sterowania PLC/HMI/SCADA oraz&nbsp;kompletne stanowiska zrobotyzowane dostosowane do&nbsp;specyficznych norm Twojej branży.",
    reg_h2_faq: "Często Zadawane Pytania (FAQ)",
    reg_faq_q1: "Jakie standardy automatyki obowiązują w&nbsp;przemyśle lotniczym (np.&nbsp;Rzeszów)?",
    reg_faq_a1: "Przemysł lotniczy wymaga pełnej powtarzalności oraz&nbsp;skrupulatnego logowania parametrów każdego procesu (traceability). Systemy PLC/SCADA muszą gwarantować zapis danych procesowych oraz&nbsp;integrację z&nbsp;systemami ERP/MES zgodnie ze&nbsp;standardami normy AS9100.",
    reg_faq_q2: "Jak zabezpieczyć roboty i&nbsp;szafy sterownicze w&nbsp;warunkach ciężkiego przemysłu miedziowego?",
    reg_faq_a2: "Stosuje się dedykowane szafy o&nbsp;klasie szczelności IP66 z&nbsp;układami chłodzenia freonowego lub&nbsp;wodnego, odporne na&nbsp;zapylenie i&nbsp;wysoką temperaturę, a&nbsp;także pokrowce ochronne na&nbsp;roboty oraz&nbsp;specjalne przewody elastyczne o&nbsp;podwyższonej wytrzymałości termicznej.",
    reg_faq_q3: "Czy NEXAUT realizuje wdrożenia i&nbsp;serwis na&nbsp;terenie całej Polski?",
    reg_faq_a3: "Tak. Nasz zespół realizuje projekty wdrożeniowe, modernizacje (Retrofit) oraz&nbsp;wsparcie serwisowe i&nbsp;diagnostykę zdalną dla zakładów przemysłowych w&nbsp;każdym województwie.",
    reg_h2_5: "Podsumowanie – Zoptymalizuj produkcję w&nbsp;swoim regionie",
    reg_p5_1: "Niezależnie od&nbsp;branży i&nbsp;unikalnych wymagań środowiskowych, nowoczesna automatyzacja jest kluczem do&nbsp;podniesienia wydajności i&nbsp;konkurencyjności zakładu. Chcesz omówić projekt dla Twojej fabryki w&nbsp;Rzeszowie, Legnicy, Bydgoszczy czy&nbsp;Szczecinie? Skontaktuj się z&nbsp;zespołem NEXAUT!"
  },

  en: {
    reg_meta_desc: "Process automation in key industrial hubs: Rzeszów, Legnica, Bydgoszcz, Szczecin. Discover regional needs in aerospace, heavy industry, plastics, and marine sectors with NEXAUT.",
    reg_page_title: "Process Automation: Rzeszów, Legnica, Bydgoszcz, Szczecin – NEXAUT",
    reg_h1: "Process automation in key industrial hubs: Rzeszów, Legnica, Bydgoszcz, and Szczecin",
    reg_intro: "Poland's industrial landscape features immense technological diversity. From aerospace standards in Rzeszów to heavy-duty copper metallurgy around Legnica, plastics in Bydgoszcz, and maritime structures in Szczecin, automation must be tailored specifically to each regional demand.",
    reg_h2_1: "1. Regional Industrial Hubs and Unique Challenges",
    reg_p1_1: "Successful automation projects rely on understanding localized industry requirements:",
    reg_hub1_title: "Aviation Valley &amp; Precision Machining",
    reg_hub1_desc: "Aerospace sector (AS9100 compliance). Automatic CNC machine tending, turbine blade grinding robotics, and strict process traceability.",
    reg_hub2_title: "Copper Belt &amp; Heavy Metallurgy",
    reg_hub2_desc: "Metallurgy, mining, and heavy automotive parts. High payload robots (Heavy-Duty), IP67/IP68 ingress protection, and high-temperature resistance.",
    reg_hub3_title: "Plastics Hub &amp; Toolmaking",
    reg_hub3_desc: "Plastics processing and injection mold manufacturing. Linear robot part extraction, IML labeling, and real-time vision inspection.",
    reg_hub4_title: "Maritime &amp; Offshore Wind Industry",
    reg_hub4_desc: "Large-scale wind energy structures and port logistics. Robotic beveling, arc welding, and automated heavy transport.",
    reg_h2_2: "2. Automation Tailored to Industry Needs",
    reg_p2_1: "Control systems and robotic cells are engineered for target sector requirements:",
    reg_li_1: "<strong class=\"text-white\">CNC &amp; Machining Center Integration:</strong> 6-axis robot tending using Profinet and OPC UA protocols.",
    reg_li_2: "<strong class=\"text-white\">Heavy-Duty Robotics &amp; Large Welding:</strong> Heavy payload gantries, linear tracks, and robust welding cells built for harsh environments.",
    reg_li_3: "<strong class=\"text-white\">Autonomous Vision Inspection:</strong> Deep learning neural networks detecting surface defects on molded plastics and metallic castings.",
    reg_li_4: "<strong class=\"text-white\">SCADA &amp; Factory Data Acquisition:</strong> Multi-site OEE tracking software for distributed industrial plants.",
    reg_callout_title: "NEXAUT – Your Nationwide Automation Integrator",
    reg_callout_text: "Regardless of your region – from Rzeszów and Legnica to Bydgoszcz and Szczecin – NEXAUT engineers design custom PLC/HMI/SCADA and robotic systems matching your industry standards.",
    reg_h2_faq: "Frequently Asked Questions (FAQ)",
    reg_faq_q1: "What automation standards apply to the aerospace sector (e.g., Rzeszów)?",
    reg_faq_a1: "Aerospace requires full process repeatability and detailed data logging (traceability). Systems must log processing metrics into ERP/MES platforms in line with AS9100 standards.",
    reg_faq_q2: "How are control cabinets and robots protected in copper metallurgy conditions?",
    reg_faq_a2: "Engineers deploy IP66-rated cabinets with active liquid cooling, heat-resistant robot covers, and heavy-duty cabling suited for high dust and temperatures.",
    reg_faq_q3: "Does NEXAUT offer nationwide services across Poland?",
    reg_faq_a3: "Yes. Our engineering teams perform commissioning, retrofitting, and remote diagnostic support across all Polish voivodeships.",
    reg_h2_5: "Summary – Optimize Production in Your Region",
    reg_p5_1: "Modern industrial automation drives operational efficiency regardless of regional specifics. Planning a plant upgrade in Rzeszów, Legnica, Bydgoszcz, or Szczecin? Contact NEXAUT today!"
  },

  de: {
    reg_meta_desc: "Prozessautomatisierung in Industriezentren: Rzeszów, Legnica, Bydgoszcz und Stettin. Luftfahrt, Schwerindustrie, Kunststoffe und Maritim mit NEXAUT.",
    reg_page_title: "Prozessautomatisierung: Rzeszów, Legnica, Bydgoszcz, Stettin – NEXAUT",
    reg_h1: "Prozessautomatisierung in Industriezentren: Rzeszów, Legnica, Bydgoszcz und Stettin",
    reg_intro: "Polens Industriekarte zeichnet sich durch große Vielfalt aus: Luftfahrtnormen im Süden, Schwerindustrie im Westen, Kunststoffverarbeitung im Zentrum und Seefahrt im Nordwesten.",
    reg_h2_1: "1. Regionale Industriezentren und ihre Herausforderungen",
    reg_p1_1: "Erfolgreiche Automatisierungsprojekte erfordern tiefes Verständnis regionaler Branchen:",
    reg_hub1_title: "Luftfahrttal &amp; Präzisionsmechanik",
    reg_hub1_desc: "Luftfahrtsektor (AS9100). Automatische Bestückung von CNC-Maschinen, Roboterschleifen von Turbinenschaufeln und lückenlose Rückverfolgbarkeit.",
    reg_hub2_title: "Kupferbecken &amp; Schwerindustrie",
    reg_hub2_desc: "Hüttenwesen und Bergbau. Schwerlastroboter, Schutzarten IP67/IP68 und Hitzebeständigkeit.",
    reg_hub3_title: "Kunststoffzentrum &amp; Werkzeugbau",
    reg_hub3_desc: "Spritzgussautomatisierung, Linearroboter-Entnahme, IML-Etikettierung und Kamerasysteme.",
    reg_hub4_title: "Maritim &amp; Offshore-Windenergie",
    reg_hub4_desc: "Großkomponenten für Windenergie und Hafenlogistik. Roboterfaskanten, Lichtbogenschweißen und Schwertransport.",
    reg_h2_2: "2. Maßgeschneiderte Automatisierungslösungen",
    reg_p2_1: "Steuerungssysteme und Roboterzellen werden direkt an Branchenprofile angepasst:",
    reg_li_1: "<strong class=\"text-white\">CNC-Maschinenanbindung:</strong> Automatische Roboterbestückung über Profinet / OPC UA.",
    reg_li_2: "<strong class=\"text-white\">Schwerlast-Roboter &amp; Großteil-Schweißen:</strong> Roboterzellen für raue Industrieumgebungen.",
    reg_li_3: "<strong class=\"text-white\">Optische Qualitätskontrolle:</strong> KI-gestützte Bildverarbeitung zur Fehlererkennung bei Kunststoff- und Gussteilen.",
    reg_li_4: "<strong class=\"text-white\">SCADA &amp; Datenerfassung:</strong> Software zur Überwachung der Gesamtanlageneffektivität (OEE).",
    reg_callout_title: "NEXAUT – Ihr bundesweiter Systemintegrator",
    reg_callout_text: "Ob Rzeszów, Legnica, Bydgoszcz oder Stettin – NEXAUT entwickelt SPS-/HMI-/SCADA-Systeme sowie Roboterzellen nach Ihren Branchenstandards.",
    reg_h2_faq: "Häufig gestellte Fragen (FAQ)",
    reg_faq_q1: "Welche Standards gelten für die Luftfahrtindustrie (z. B. Rzeszów)?",
    reg_faq_a1: "Lückenlose Prozessdokumentation und Rückverfolgbarkeit gemäß AS9100.",
    reg_faq_q2: "Wie schützt man Schaltschränke in der Schwerindustrie?",
    reg_faq_a2: "Einsatz von IP66-Schaltschränken mit aktiver Kühlung und Hitzeschutztextilien für Roboter.",
    reg_faq_q3: "Bietet NEXAUT Dienstleistungen in ganz Polen an?",
    reg_faq_a3: "Ja, wir betreuen Kunden im gesamten polnischen Bundesgebiet.",
    reg_h2_5: "Zusammenfassung – Produktion lokal optimieren",
    reg_p5_1: "Moderne Automatisierung steigert Produktivität und Qualität. Planen Sie ein Projekt? Kontaktieren Sie NEXAUT!"
  }
};