window.POST_TRANSLATIONS = {
  pl: {
    iot_meta_desc: "Dowiedz się, jak wdrożyć Przemysł 4.0 i Industrial IoT. Zbieranie danych z PLC przez OPC UA i MQTT, integracja z chmurą oraz Predictive Maintenance.",
    iot_page_title: "Przemysł 4.0 i IoT w praktyce – Zbieranie danych z maszyn – NEXAUT",
    iot_h1: "Przemysł 4.0&nbsp;i&nbsp;IoT – jak zbierać i&nbsp;analizować dane z&nbsp;maszyn produkcyjnych?",
    iot_intro: "Przemysłowy Internet Rzeczy (IIoT) i&nbsp;koncepcja Przemysłu 4.0 wykraczają daleko poza teoretyczne hasła marketingowe. Dla współczesnego zakładu produkcyjnego dane z&nbsp;maszyn stanowią cenne źródło wiedzy o&nbsp;wydajności procesów, wskaźniku OEE (Overall Equipment Effectiveness) oraz zbliżających się awariach. Sprawdź, jak prawidłowo zbudować architekturę zbierania danych z&nbsp;parku maszynowego.",
    iot_h2_1: "1. Kluczowe protokoły komunikacyjne: OPC UA oraz MQTT",
    iot_p1_1: "Podstawą sprawnego przesyłania danych między warstwą sterowania OT (Operational Technology) a&nbsp;warstwą IT jest wyznaczenie uniwersalnego języka komunikacji. Tradycyjne protokoły przemysłowe ustępują miejsca nowoczesnym standardom otwartym:",
    iot_h2_2: "2. Architektura Edge Computing – przetwarzanie przy maszynie",
    iot_p2_1: "Wysyłanie surowych sygnałów z&nbsp;czujników (np. próbkowanie drgań z&nbsp;częstotliwością 10 kHz) bezpośrednio do&nbsp;chmury jest nieefektywne i&nbsp;kosztowne. Właśnie dlatego kluczową rolę odgrywają przemysłowe komputery Edge (np. Siemens Industrial Edge, WAGO Edge Controller). Urządzenia te wstępnie filtrują, agregują i&nbsp;anonimizują dane przed przekazaniem ich wyżej do&nbsp;systemów MES lub chmury AWS/Azure.",
    iot_callout_title: "Złota Zasada Inżyniera NEXAUT",
    iot_callout_text: "Nigdy nie obciążaj głównej pętli sterowania cyklicznego sterownika PLC (programu wykonawczego maszyny) zadaniami wysyłania skomplikowanych zapytania do&nbsp;baz danych. Dedykuj do&nbsp;tego osobny wątek w&nbsp;serwerze OPC UA lub zastosuj zewnętrzną bramkę komunikacyjną IIoT.",
    iot_h2_3: "3. Predykcyjne utrzymanie ruchu (Predictive Maintenance)",
    iot_p3_1: "Zamiast reagować na&nbsp;awarię po&nbsp;jej wystąpieniu (Reagowanie) lub wymieniać sprawne komponenty na&nbsp;zaś (Służba Prewencyjna), zaawansowana analityka danych pozwala wdrożyć Predictive Maintenance. Algorytmy uczenia maszynowego (ML) analizują prądy silników, temperaturę łożysk oraz profil drgań, wykrywając symptom uszkodzenia na&nbsp;wiele tygodni przed rzeczywistym zatrzymaniem linii.",
    iot_h2_4: "4. Bezpieczeństwo IT/OT i separacja sieci (Cybersecurity)",
    iot_p4_1: "Połączenie środowiska produkcyjnego z&nbsp;siecią zakładową IT lub chmurą stwarza nowe wyzwania z&nbsp;zakresu cyberbezpieczeństwa. Podstawą bezpiecznej wdrożenia jest fizyczna lub logiczna separacja sieci (VLAN), stosowanie przemysłowych zapór ogniowych (Firewall) z&nbsp;głęboką inspekcją pakietów DPI oraz wdrożenie normy IEC 62443.",
    iot_h2_faq: "Często Zadawane Pytania (FAQ)",
    iot_faq_q1: "Czy do wdrożenia IIoT wymagana jest wymiana starych maszyn i sterowników PLC?",
    iot_faq_a1: "Nie! Koncepcja tzw. Retrofittingu pozwala doposażyć istniejące starsze maszyny w dodatkowe czujniki (np. drgań i temperatury) oraz zewnętrzne bramki IoT, które pobierają dane bez ingerencji w oryginalny program sterownika PLC.",
    iot_faq_q2: "Jaka jest różnica między systemem SCADA a systemem MES i chmurą IIoT?",
    iot_faq_a2: "SCADA służy do bieżącego sterowania i wizualizacji procesu w czasie rzeczywistym na hali. System MES zarządza zleceniami produkcyjnymi i rozlicza czas pracy, natomiast chmura IIoT integruje dane z wielu zakładów, pozwalając na zaawansowaną analitykę i predykcję awarii.",
    iot_faq_q3: "Jak NEXAUT pomaga we wdrażaniu rozwiązań Przemysłu 4.0?",
    iot_faq_a3: "Projektujemy i wdrażamy kompleksowe architektury IIoT – od integracji sterowników PLC (Siemens, Allen-Bradley), przez konfigurację serwerów OPC UA i bramek Edge, aż po przesyłanie i wizualizację danych w systemach MES oraz dashboardach analitycznych.",
    iot_h2_5: "Podsumowanie – Przekształć dane produkcyjne w przewagę konkurencyjną",
    iot_p5_1: "Prawidłowo zaplanowana infrastruktura zbierania danych z maszyn redukuje nieplanowane przestoje, podnosi wskaźnik OEE i ułatwia podejmowanie trafnych decyzji biznesowych. Chcesz cyfryzować swój park maszynowy zgodnie z najlepszymi praktykami? Skontaktuj się z zespołem inżynierów NEXAUT!"
  },

  en: {
    iot_meta_desc: "Learn how to implement Industry 4.0 and IIoT. Collect PLC data via OPC UA and MQTT, cloud integration, and Predictive Maintenance.",
    iot_page_title: "Industry 4.0 & IIoT in Practice – Machine Data Analytics – NEXAUT",
    iot_h1: "Industry 4.0 & IoT – How to Collect and Analyze Data from Production Machines?",
    iot_intro: "The Industrial Internet of Things (IIoT) and Industry 4.0 extend far beyond hype. For modern manufacturing plants, machine data is a goldmine for OEE tracking, process optimization, and fault prevention. Learn how to build a robust data collection architecture.",
    iot_h2_1: "1. Core Communication Protocols: OPC UA & MQTT",
    iot_p1_1: "Connecting Operational Technology (OT) with Information Technology (IT) demands a unified communication language. Traditional fieldbuses yield to open standards:",
    iot_h2_2: "2. Edge Computing Architecture – On-Premises Data Processing",
    iot_p2_1: "Sending raw sensor streams (e.g., 10 kHz vibration sampling) directly to the cloud is bandwidth-heavy and costly. Industrial Edge devices (e.g., Siemens Industrial Edge) filter, aggregate, and anonymize data prior to cloud uploading.",
    iot_callout_title: "NEXAUT Golden Engineering Rule",
    iot_callout_text: "Never burden the main cyclic execution loop of your PLC with direct database queries. Dedicate a background thread in an OPC UA server or deploy an external IIoT gateway.",
    iot_h2_3: "3. Predictive Maintenance",
    iot_p3_1: "Moving beyond reactive or calendar-based maintenance, advanced telemetry powers Predictive Maintenance. Machine learning algorithms evaluate motor current, bearing temperatures, and vibration signatures to predict failures weeks before an outage.",
    iot_h2_4: "4. IT/OT Cybersecurity & Network Segmentation",
    iot_p4_1: "Connecting shop-floor equipment to corporate networks or the cloud introduces security risks. Robust deployments mandate physical or VLAN network isolation, industrial firewalls with Deep Packet Inspection (DPI), and IEC 62443 compliance.",
    iot_h2_faq: "Frequently Asked Questions (FAQ)",
    iot_faq_q1: "Does IIoT implementation require replacing legacy machinery and PLCs?",
    iot_faq_a1: "No! Through retrofitting, legacy machines are equipped with external sensors (vibration, temperature) and IIoT gateways that pull metrics without modifying legacy PLC code.",
    iot_faq_q2: "What is the difference between SCADA, MES, and IIoT Cloud?",
    iot_faq_a2: "SCADA handles real-time machine control and visualization on the shop floor. MES manages production jobs and OEE, while IIoT cloud aggregates multi-plant telemetry for advanced predictive analytics.",
    iot_faq_q3: "How does NEXAUT assist with Industry 4.0 implementations?",
    iot_faq_a3: "We design end-to-end IIoT architectures—from PLC integration (Siemens, Allen-Bradley) and OPC UA/Edge gateway setups to cloud dashboards and MES connectivity.",
    iot_h2_5: "Summary – Turn Machine Telemetry into Competitive Advantage",
    iot_p5_1: "A well-structured data acquisition infrastructure cuts unplanned downtime, boosts OEE, and accelerates data-driven decision making. Contact NEXAUT engineers to digitize your plant!"
  },

  de: {
    iot_meta_desc: "Erfahren Sie, wie Sie Industrie 4.0 und IIoT umsetzen. Datenerfassung von SPSen über OPC UA/MQTT, Cloud-Anbindung und Predictive Maintenance.",
    iot_page_title: "Industrie 4.0 & IoT in der Praxis – Maschinendatenerfassung – NEXAUT",
    iot_h1: "Industrie 4.0 & IoT – Wie sammelt und analysiert man Maschinendaten?",
    iot_intro: "Das Industrielle Internet der Dinge (IIoT) und Industrie 4.0 bieten echten Mehrwert für moderne Fertigungsbetriebe. Maschinendaten sind der Schlüssel zur Steigerung der Gesamtanlageneffektivität (OEE) und Vermeidung von Ausfällen.",
    iot_h2_1: "1. Zentrale Kommunikationsprotokolle: OPC UA & MQTT",
    iot_p1_1: "Für den Datenaustausch zwischen OT (Steuerungsebene) und IT benötigt man einheitliche Standards:",
    iot_h2_2: "2. Edge Computing – Datenverarbeitung direkt an der Maschine",
    iot_p2_1: "Rohdaten direkt in die Cloud zu senden ist ineffizient. Industrial-Edge-Geräte filtern und verdichten Daten lokal, bevor sie an MES- oder Cloud-Systeme (AWS/Azure) übertragen werden.",
    iot_callout_title: "Goldene NEXAUT Ingenieur-Regel",
    iot_callout_text: "Belasten Sie nicht den zyklischen Hauptprogrammablauf der SPS mit komplexen Datenbankabfragen. Nutzen Sie dafür OPC-UA-Server oder externe IIoT-Gateways.",
    iot_h2_3: "3. Vorausschauende Instandhaltung (Predictive Maintenance)",
    iot_p3_1: "Maschinelles Lernen analysiert Motorströme, Lagertemperaturen und Schwingungsprofile, um drohende Schäden Wochen vor einem Stillstand zu erkennen.",
    iot_h2_4: "4. IT/OT-Cybersecurity und Netzwerktrennung",
    iot_p4_1: "Die Anbindung der Produktion an das IT-Netz erfordert Sicherheitsmaßnahmen: VLAN-Netzwerktrennung, Industrial Firewalls und die Einhaltung der IEC 62443.",
    iot_h2_faq: "Häufig gestellte Fragen (FAQ)",
    iot_faq_q1: "Müssen für IIoT alte Maschinen und SPSen ausgetauscht werden?",
    iot_faq_a1: "Nein! Durch Retrofitting werden Bestandsanlagen mit zusätzlichen Sensoren und externen IIoT-Gateways nachgerüstet, ohne die SPS-Software zu verändern.",
    iot_faq_q2: "Was unterscheidet SCADA, MES und IIoT Cloud?",
    iot_faq_a2: "SCADA dient der Prozesssteuerung vor Ort. MES steuert Aufträge und OEE. Die IIoT-Cloud führt Daten mehrerer Standorte für übergreifende Analysen zusammen.",
    iot_faq_q3: "Wie unterstützt NEXAUT bei Industrie-4.0-Projekten?",
    iot_faq_a3: "Wir konzipieren und realisieren durchgängige IIoT-Architekturen – von der SPS-Anbindung über Edge-Gateways bis hin zu MES- und Cloud-Dashboards.",
    iot_h2_5: "Zusammenfassung – Verwandeln Sie Daten in Wettbewerbsvorteile",
    iot_p5_1: "Eine durchdachte Infrastruktur zur Datenerfassung reduziert Ausfallzeiten und steigert die OEE. Kontaktieren Sie das Experten-Team von NEXAUT!"
  }
};