window.POST_TRANSLATIONS = {
  pl: {
    pn_meta_desc: "Poznaj metody diagnostyki i optymalizacji sieci Profinet na obiekcie. Jak eliminować zakłócenia EMC, błędy okablowania i przeciążenia pętli komunikacyjnych?",
    pn_page_title: "Diagnostyka i optymalizacja sieci Profinet – NEXAUT",
    pn_h1: "Prawidłowa diagnostyka i&nbsp;optymalizacja sieci Profinet na&nbsp;obiekcie",
    pn_intro: "Profinet to&nbsp;obecnie najpopularniejszy standard komunikacyjny w&nbsp;automatyce przemysłowej. Choć technologia ta&nbsp;opiera się na&nbsp;niezawodnym przemysłowym Ethernet, losowe wypatrywanie błędów w&nbsp;przypadku zatrzymania linii produkcyjnej potrafi trwać godzinami. Poznaj najważniejsze przyczyny awarii magistrali Profinet oraz skuteczne procedury diagnostyczne i&nbsp;optymalizacyjne.",
    pn_h2_1: "1. Fizyczna warstwa sieci – najczęstszy źródło problemów",
    pn_p1_1: "Ponad 70% awarii sieci Profinet wynika z&nbsp;zaniedbań na&nbsp;poziomie infrastruktury kablowej. Do&nbsp;najczęstszych grzechów montażowych należą zagięcia zielonych przewodów Ethernetowych przekraczające dopuszczalny promień gięcia, niewłaściwy zarobek wtyków RJ45 lub M12 oraz zbyt duży odcinek zdjętego ekranu przy uziemieniu.",
    pn_h2_2: "2. Pomiary i narzędzia diagnostyki fizycznej",
    pn_p2_1: "Zwykły multimetr nie nadaje się do&nbsp;testowania magistrali wysokie częstotliwości. Przed uruchomieniem instalacji należy wykonać audyt za&nbsp;pomocą dedykowanych testerów okablowania (np. Fluke Networks), które sprawdzają przesłuchy, tłumienność oraz impedancję przewodu.",
    pn_callout_title: "Złota Zasada Inżyniera NEXAUT",
    pn_callout_text: "Zawsze stosuj obustronne uziemienie ekranu kabla Profinet do&nbsp;szyny wyrównania potencjałów (PE) za&nbsp;pomocą specjalnych klamer sprężynowych o&nbsp;dużej powierzchni styku. Zwykłe skręcanie ekranu w&nbsp;tzw. „pigtail” działa jak antena odbiorcza dla zakłóceń elektromagnetycznych!",
    pn_h2_3: "3. Optymalizacja cyklu i czasu odświeżania (Send Clock & Update Time)",
    pn_p3_1: "Nieprzemyślana konfiguracja programowa w&nbsp;TIA Portal lub innym środowisku może doprowadzić do&nbsp;przeciążenia procesora sterownika PLC. Nie każde urządzenie w&nbsp;sieci wymaga odświeżania danych co&nbsp;1&nbsp;ms. Dla wysp zaworowych czy prostych czujników czas odświeżania na&nbsp;poziomie 8&nbsp;ms lub 16&nbsp;ms jest w&nbsp;zupełności wystarczający i&nbsp;znacząco odciąża ruch sieciowy.",
    pn_h2_4: "4. Analiza logiczna i monitoring stanów stacji (PN-TAP & Wireshark)",
    pn_p4_1: "Podczas trudnych do&nbsp;zdiagnozowania, sporadycznych błędów (np. pojedynczy gubiony pakiet raz na&nbsp;tydzień), warto wpiąć w&nbsp;sieć pasywny analizator (PN-TAP) i&nbsp;rejestrować ruch programem Wireshark lub dedykowanym systemem diagnostycznym (np. InduSol PROmesh / Diagnostic Tool). Pozwala to&nbsp;precyzyjnie wskazać, które urządzenie zerwało połączenie jako pierwsze.",
    pn_h2_faq: "Często Zadawane Pytania (FAQ)",
    pn_faq_q1: "Co oznacza błąd BF (Bus Fault) na sterowniku PLC lub wyspie I/O?",
    pn_faq_a1: "Dioda BF sygnalizuje brak komunikacji z przynajmniej jednym skonfigurowanym urządzeniem Profinet. Przyczyną może być fizyczne uszkodzenie przewodu, brak zasilania węzła, uszkodzony switch lub niezgodność nazwy Profinet Name/IP.",
    pn_faq_q2: "Jaka jest różnica między Profinet RT (Real-Time) a IRT (Isochronous Real-Time)?",
    pn_faq_a2: "Profinet RT służy do standardowej komunikacji na linii (czasy reakcji 1-10 ms). Profinet IRT to komunikacja deterministyczna z synchronizacją zegarową poniżej 1 ms, wymagana przy wieloosiowym sterowaniu serwonapędami (Motion Control).",
    pn_faq_q3: "Czy NEXAUT świadczy usługi audytu i pomiarów sieci Profinet?",
    pn_faq_a3: "Tak. Inżynierowie NEXAUT wykonują kompleksowe pomiary fizyczne i logiczne istniejących magistrali Profinet/Profibus, lokalizują usterki EMC, optymalizują topologię oraz wystawiają protokoły zdawcze.",
    pn_h2_5: "Podsumowanie – Zapewnij bezawaryjną komunikację w Twoim zakładzie",
    pn_p5_1: "Stabilna sieć Profinet to fundament płynnej pracy nowoczesnej fabryki. Unikanie błędów montażowych, przemyślana konfiguracja parametrów odświeżania oraz okresowe audyty sieci pozwalają całkowicie wyeliminować niespodziewane przestoje technologiczne. Potrzebujesz wsparcia w diagnostyce komunikacji na obiekcie? Skontaktuj się z zespołem NEXAUT!"
  },

  en: {
    pn_meta_desc: "Discover methods for Profinet network diagnostics and optimization on site. How to eliminate EMC interference, cabling errors, and communication loop overloads?",
    pn_page_title: "Profinet Network Diagnostics & Optimization – NEXAUT",
    pn_h1: "Proper Diagnostics and Optimization of Profinet Networks On Site",
    pn_intro: "Profinet is currently the most popular communication standard in industrial automation. While based on reliable Industrial Ethernet, random troubleshooting during line stoppages can take hours. Learn the key causes of Profinet failures and effective diagnostic procedures.",
    pn_h2_1: "1. Physical Layer – The Most Common Root Cause",
    pn_p1_1: "Over 70% of Profinet network faults stem from cable infrastructure issues. Common installation mistakes include bending green Ethernet cables beyond allowed radii, improper RJ45/M12 connector termination, and excessive shield stripping.",
    pn_h2_2: "2. Measurements and Physical Diagnostic Tools",
    pn_p2_1: "Standard multimeters cannot test high-frequency fieldbuses. Prior to commissioning, perform audits using dedicated cable certifiers (e.g., Fluke Networks) to evaluate crosstalk, attenuation, and impedance.",
    pn_callout_title: "NEXAUT Golden Engineering Rule",
    pn_callout_text: "Always ground Profinet cable shielding at both ends to the equipotential bonding rail (PE) using specialized large-surface shield clamps. Twisting shield braid into a 'pigtail' acts as a receiver antenna for electromagnetic interference!",
    pn_h2_3: "3. Cycle Time and Update Time Optimization",
    pn_p3_1: "Suboptimal software configurations in TIA Portal can overload the PLC CPU. Not every node requires 1 ms refresh rates. For valve manifolds or basic sensors, an 8 ms or 16 ms update time is sufficient and greatly reduces network load.",
    pn_h2_4: "4. Logical Analysis and Station Diagnostics (PN-TAP & Wireshark)",
    pn_p4_1: "For elusive intermittent faults (e.g., single packet loss once a week), insert a passive tap (PN-TAP) and capture traffic using Wireshark or dedicated analyzers (e.g., InduSol PROmesh). This precisely pinpoint which device dropped connection first.",
    pn_h2_faq: "Frequently Asked Questions (FAQ)",
    pn_faq_q1: "What does the BF (Bus Fault) LED mean on a PLC or I/O island?",
    pn_faq_a1: "The BF LED signals lost communication with at least one configured Profinet device. Causes include physical cable damage, node power loss, faulty switches, or Profinet Name/IP mismatches.",
    pn_faq_q2: "What is the difference between Profinet RT (Real-Time) and IRT (Isochronous Real-Time)?",
    pn_faq_a2: "Profinet RT handles standard deterministic messaging (1-10 ms cycle times). Profinet IRT delivers sub-millisecond clock-synchronized communication required for multi-axis Motion Control.",
    pn_faq_q3: "Does NEXAUT provide Profinet audit and measurement services?",
    pn_faq_a3: "Yes. NEXAUT engineers conduct physical and logical audits of industrial fieldbuses, locate EMC issues, optimize topologies, and provide official test reports.",
    pn_h2_5: "Summary – Ensure Uninterrupted Communication in Your Plant",
    pn_p5_1: "A stable Profinet network is the backbone of modern factory operations. Preventing wiring mistakes, optimizing refresh rates, and running periodic audits eliminate unscheduled downtime. Contact NEXAUT for field diagnostics support!"
  },

  de: {
    pn_meta_desc: "Erfahren Sie Methoden zur Profinet-Diagnose und -Optimierung vor Ort. Wie Sie EMV-Störungen, Verdrahtungsfehler und Netzwerküberlastungen eliminieren.",
    pn_page_title: "Profinet Diagnostik & Optimierung – NEXAUT",
    pn_h1: "Ordnungsgemäße Diagnose und Optimierung von Profinet-Netzwerken",
    pn_intro: "Profinet ist der führende Kommunikationsstandard in der Industrieautomatisierung. Obwohl die Technologie auf zuverlässigem Industrial Ethernet basiert, kann die Fehlersuche bei Stillständen Stunden dauern. Lernen Sie die Hauptursachen für Störungen und effektive Diagnoseverfahren kennen.",
    pn_h2_1: "1. Physikalische Schicht – Die häufigste Fehlerquelle",
    pn_p1_1: "Über 70 % aller Profinet-Ausfälle entstehen durch Mängel der Kabelinfrastruktur. Zu den häufigsten Montagefehlern gehören das Unterschreiten von Biegeradien, mangelhaft konfektionierte RJ45/M12-Stecker und zu weit abisolierte Schirmungen.",
    pn_h2_2: "2. Messungen und physikalische Diagnosewerkzeuge",
    pn_p2_1: "Ein einfaches Multimeter eignet sich nicht für Hochfrequenzbusse. Vor der Inbetriebnahme sollte ein Audit mit Kabeltestern (z. B. Fluke) zur Messung von Übersprechen und Dämpfung durchgeführt werden.",
    pn_callout_title: "Goldene NEXAUT Ingenieur-Regel",
    pn_callout_text: "Erdung Sie den Schirm des Profinet-Kabels stets beidseitig über flächige Schirmklammern an der Potentialausgleichsschiene (PE). Das Verdrillen des Schirms zu einem 'Pigtail' wirkt wie eine Empfangsantenne für EMV-Störungen!",
    pn_h2_3: "3. Zykluszeit- und Aktualisierungszeit-Optimierung",
    pn_p3_1: "Fehlerhafte Konfigurationen im TIA Portal können die SPS-CPU überlasten. Nicht jedes Gerät benötigt 1 ms Aktualisierungszeit. Für Ventilinseln oder Sensorik reichen 8 ms oder 16 ms vollkommen aus.",
    pn_h2_4: "4. Logische Analyse und Protokollüberwachung (PN-TAP & Wireshark)",
    pn_p4_1: "Bei sporadischen Fehlern empfiehlt sich der Einsatz eines passiven Tap-Geräts (PN-TAP) zur Datenaufzeichnung mittels Wireshark oder InduSol-Systemen, um den Verursacher eindeutig zu identifizieren.",
    pn_h2_faq: "Häufig gestellte Fragen (FAQ)",
    pn_faq_q1: "Was bedeutet die BF-LED (Bus Fault) an der SPS oder I/O-Insel?",
    pn_faq_a1: "Die BF-LED zeigt den Kommunikationsverlust zu mindestens einem projektierten Profinet-Teilnehmer an. Ursachen sind Kabelschäden, Spannungsausfall, defekte Switches oder Namenskonflikte.",
    pn_faq_q2: "Was unterscheidet Profinet RT (Real-Time) von IRT (Isochronous Real-Time)?",
    pn_faq_a2: "Profinet RT deckt standardmäßige Reaktionszeiten ab (1-10 ms). Profinet IRT bietet taktsynchrone Kommunikation unter 1 ms, die für mehrachsige Serdominantsteuerungen (Motion Control) erforderlich ist.",
    pn_faq_q3: "Bietet NEXAUT Audits und Messungen für Profinet-Netzwerke an?",
    pn_faq_a3: "Ja. NEXAUT führt umfassende physikalische und logische Audits von Feldbussen durch, ortet EMV-Probleme, optimiert Topologien und erstellt Messprotokolle.",
    pn_h2_5: "Zusammenfassung – Sichern Sie störungsfreie Kommunikation",
    pn_p5_1: "Ein stabiles Profinet-Netzwerk ist die Voraussetzung für reibungslose Produktion. Vermeidung von Montagefehlern und regelmäßige Audits sichern maximale Anlagenverfügbarkeit. Kontaktieren Sie NEXAUT für Expertenunterstützung vor Ort!"
  }
};