window.POST_TRANSLATIONS = {
  pl: {
    diseases_meta_desc: "Choroby zawodowe w&nbsp;fabrykach i&nbsp;jak im przeciwdziałać. Zobacz, jak robotyzacja, koboty i&nbsp;nowoczesna ergonomia eliminują hałas, pyły i&nbsp;przeciążenia kręgosłupa.",
    diseases_page_title: "Choroby zawodowe w&nbsp;fabrykach – Automatyzacja i&nbsp;Ergonomia – NEXAUT",
    diseases_h1: "Choroby zawodowe w&nbsp;fabrykach – jak automatyzacja i&nbsp;ergonomia chronią zdrowie pracowników?",
    diseases_intro: "Wielogodzinne przenoszenie ciężarów, praca w&nbsp;szkodliwym zapyleniu, stały hałas oraz monotypia ruchowa to&nbsp;główne przyczyny zwolnień lekarskich i&nbsp;trwałych uszczerbków na&nbsp;zdrowiu operatorów. Automatyzacja uciążliwych procesów przestała być jedynie domeną wydajności – stała się priorytetem ochrony zdrowia.",
    diseases_h2_1: "1. Statystyka schorzeń w&nbsp;przemyśle wytwórczym",
    diseases_p1_1: "Choroby układu mięśniowo-szkieletowego (MSD) oraz zaburzenia słuchu stanowią ponad 60% wszystkich diagnozowanych chorób zawodowych w&nbsp;sektorze przemysłowym. Odpowiedzią nowoczesnego inżynieringu jest zastępowanie pracy ludzkiej tam, gdzie jest ona najbardziej destrukcyjna dla organizmu.",
    
    // Wskaźniki
    diseases_stat_1: "Redukcja ręcznego dźwigania ciężarów",
    diseases_stat_2: "Narażenia operatora na&nbsp;pyły w&nbsp;komorze",
    diseases_stat_3: "Zgodności z&nbsp;normami ergonomicznymi",

    diseases_h2_2: "2. Najczęstsze choroby zawodowe i&nbsp;technologiczne metody ich eliminacji",
    
    // Karty
    diseases_c1_title: "Schorzenia Kręgosłupa i&nbsp;Stawów",
    diseases_c1_desc: "Wynikają z&nbsp;ręcznej paletyzacji, schylania się i&nbsp;podnoszenia detali. <br><br><strong class=\"text-white\">Rozwiązanie:</strong> Zrobotyzowane gniazda paletyzacji oraz podajniki z&nbsp;regulowaną wysokością HMI.",
    diseases_c1_tag: "Roboty Paletyzujące / Koboty",
    diseases_c2_title: "Pylica i&nbsp;Uszkodzenia Płuc",
    diseases_c2_desc: "Występują przy szlifowaniu, polerowaniu, piaskowaniu i&nbsp;spawaniu.<br><br><strong class=\"text-white\">Rozwiązanie:</strong> Zamknięte zrobotyzowane cele obróbcze z&nbsp;automatyczną odciągową wentylacją.",
    diseases_c2_tag: "Zamknięte Cele Procesowe",
    diseases_c3_title: "Ubytek Słuchu i&nbsp;Zespół Wibracyjny",
    diseases_c3_desc: "Skutek długotrwałej pracy z&nbsp;narzędziami pneumatycznymi i&nbsp;udarowymi.<br><br><strong class=\"text-white\">Rozwiązanie:</strong> Izolowane obudowy dźwiękochłonne i&nbsp;automatyczne dokręcanie wielowrzecionowe.",
    diseases_c3_tag: "Wyguszenie &amp; Automatyzacja",

    diseases_h2_3: "3. Rola Kobotów (Robotów Współpracujących) w&nbsp;Ergonomii",
    diseases_p3_1: "Nie każdą linię da się w&nbsp;pełni odizolować od&nbsp;ludzi. W&nbsp;takich miejscach idealnie sprawdzają się roboty współpracujące (koboty). Przejmują one na&nbsp;siebie najcięższe fazy cyklu (np.&nbsp;podtrzymanie ciężkiego komponentu), podczas gdy człowiek wykonuje jedynie precyzyjne czynności kontrolne lub montażowe.",
    diseases_callout_title: "NEXAUT – Projektujemy Stanowiska Przyjazne Dla Człowieka",
    diseases_callout_text: "Tworzone przez nas linie produkcyjne i&nbsp;stanowiska zrobotyzowane projektujemy w&nbsp;oparciu o&nbsp;wytyczne inżynierii ergonomicznej. Pomagamy eliminować rutynowe, niebezpieczne i&nbsp;obciążające fizycznie operacje, zmieniając rolę operatora z&nbsp;siłowej na&nbsp;nadzorczo-sterującą.",
    diseases_h2_faq: "Często Zadawane Pytania (FAQ)",
    diseases_faq_q1: "Czy wdrożenie kobota wymaga budowania dużych wygrodzeń ochronnych?",
    diseases_faq_a1: "Nie zawsze. Koboty posiadają wbudowane czujniki siły i&nbsp;momentu obrotowego. W&nbsp;przypadku kontaktu z&nbsp;operatorem natychmiast bezpiecznie się zatrzymują, co&nbsp;często pozwala na&nbsp;pracę bez tradycyjnych siatek wygradzających (po wykonaniu oceny ryzyka).",
    diseases_faq_q2: "Jakie normy regulują ergonomię na&nbsp;stanowiskach zrobotyzowanych?",
    diseases_faq_a2: "Kluczowe są normy ISO 11228 (dotycząca ręcznego przemieszczania ciężarów), ISO 10218 (wymagania bezpieczeństwa dla robotów) oraz specyfikacja ISO/TS 15066 odnosząca się bezpośrednio do&nbsp;robotów współpracujących.",
    diseases_faq_q3: "Jak przekonać zarząd do&nbsp;inwestycji w&nbsp;automatyzację pod kątem BHP?",
    diseases_faq_a3: "Koszty absencji chorobowej, rekrutacji nowych pracowników oraz ewentualnych odszkodowań znacznie przewyższają koszt wdrożenia prostego gniazda zrobotyzowanego, które zwraca się również poprzez wyższą i&nbsp;powtarzalną jakość produkcji.",
    diseases_h2_5: "Podsumowanie – Zdrowy pracownik to&nbsp;stabilna produkcja",
    diseases_p5_1: "Eliminacja czynników wywołujących choroby zawodowe to&nbsp;nie tylko obowiązek prawny, ale przede wszystkim strategiczna korzyść dla zakładu. Skontaktuj się z&nbsp;zespołem NEXAUT – pomożemy Ci zautomatyzować najbardziej wymagające stanowiska na&nbsp;Twojej hali!"
  },

  en: {
    diseases_meta_desc: "Occupational diseases in factories – how automation and ergonomics protect worker health against noise, dust, and strain.",
    diseases_page_title: "Occupational Diseases in Factories – Automation & Ergonomics – NEXAUT",
    diseases_h1: "Occupational diseases in factories – how automation and ergonomics protect worker health?",
    diseases_intro: "Heavy lifting, toxic dust, constant noise, and repetitive motion lead to chronic illnesses and operator sick leave. Automating stressful tasks is now a primary health priority.",
    diseases_h2_1: "1. Illness Statistics in Manufacturing",
    diseases_p1_1: "Musculoskeletal disorders (MSDs) and hearing loss account for over 60% of all occupational diseases in manufacturing.",
    diseases_stat_1: "Reduction in manual heavy lifting",
    diseases_stat_2: "Operator dust exposure in enclosures",
    diseases_stat_3: "Compliance with ergonomic standards",
    diseases_h2_2: "2. Common Occupational Diseases and Technological Remedies",
    diseases_c1_title: "Spine & Joint Disorders",
    diseases_c1_desc: "Caused by manual palletizing and repetitive bending. <br><br><strong class=\"text-white\">Solution:</strong> Robotic palletizing cells and height-adjustable HMI feeders.",
    diseases_c1_tag: "Palletizing Robots / Cobots",
    diseases_c2_title: "Pneumoconiosis & Lung Harm",
    diseases_c2_desc: "Resulting from grinding, sandblasting, and welding dust.<br><br><strong class=\"text-white\">Solution:</strong> Enclosed robotic cells with automatic dust extraction ventilation.",
    diseases_c2_tag: "Enclosed Process Cells",
    diseases_c3_title: "Hearing Loss & Vibration Syndrome",
    diseases_c3_desc: "From prolonged pneumatic tool usage.<br><br><strong class=\"text-white\">Solution:</strong> Sound-insulated enclosures and multi-spindle automatic tightening.",
    diseases_c3_tag: "Soundproof & Automation",
    diseases_h2_3: "3. The Role of Cobots (Collaborative Robots) in Ergonomics",
    diseases_p3_1: "When total isolation isn't feasible, cobots take over heavy holding or repetitive straining, leaving precision work to humans.",
    diseases_callout_title: "NEXAUT – Human-Centric Station Engineering",
    diseases_callout_text: "We design robotic stations according to ergonomic engineering guidelines, shifting operators from manual labor to supervisory roles.",
    diseases_h2_faq: "Frequently Asked Questions (FAQ)",
    diseases_faq_q1: "Do cobots require physical safety fencing?",
    diseases_faq_a1: "Not always. Cobots feature integrated force/torque sensors, stopping safely upon human contact.",
    diseases_faq_q2: "Which standards regulate robotic ergonomics?",
    diseases_faq_a2: "Key standards include ISO 11228 (manual handling), ISO 10218 (robot safety), and ISO/TS 15066 (collaborative robots).",
    diseases_faq_q3: "How to justify automation ROI via OHS?",
    diseases_faq_a3: "Costs of sick leave, high turnover, and injuries far outweigh the cost of a cobot cell, which also boosts output quality.",
    diseases_h2_5: "Summary – Healthy Workers Ensure Stable Production",
    diseases_p5_1: "Eliminating occupational hazards protects employees and guarantees line uptime. Contact NEXAUT to automate strenuous tasks!"
  },

  de: {
    diseases_meta_desc: "Berufskrankheiten in Fabriken – Wie Automatisierung und Ergonomie die Gesundheit der Mitarbeiter schützen.",
    diseases_page_title: "Berufskrankheiten in Fabriken – Automatisierung & Ergonomie – NEXAUT",
    diseases_h1: "Berufskrankheiten in Fabriken – wie Automatisierung und Ergonomie die Gesundheit der Arbeiter schützen?",
    diseases_intro: "Moderne Produktionshallen bergen mechanische, elektrische und robotergestützte Risiken. Eine präzise Risikobeurteilung ist unumgänglich.",
    diseases_h2_1: "1. Krankheitsstatistiken in der Fertigung",
    diseases_p1_1: "Skeletterkrankungen und Hörschäden machen über 60% aller anerkannten Berufskrankheiten aus.",
    diseases_stat_1: "Reduzierung von manuellem Heben",
    diseases_stat_2: "Staubbelastung in Kabinen",
    diseases_stat_3: "Einhaltung ergonomischer Normen",
    diseases_h2_2: "2. Häufige Berufskrankheiten und technische Lösungen",
    diseases_c1_title: "Wirbelsäulen- & Gelenkschäden",
    diseases_c1_desc: "Entstehen durch manuelle Palettierung.<br><br><strong class=\"text-white\">Lösung:</strong> Roboter-Palettierzellen und höhenverstellbare Zuführungen.",
    diseases_c1_tag: "Palettierroboter / Cobots",
    diseases_c2_title: "Staublunge & Atembeschwerden",
    diseases_c2_desc: "Verursacht durch Schleif- und Schweißstaub.<br><br><strong class=\"text-white\">Lösung:</strong> Geschlossene Roboterzellen mit Absaugung.",
    diseases_c2_tag: "Geschlossene Prozesszellen",
    diseases_c3_title: "Gehörschäden & Vibrationssyndrom",
    diseases_c3_desc: "Folge von Druckluftwerkzeugen.<br><br><strong class=\"text-white\">Lösung:</strong> Schallschutzgehäuse und automatische Verschraubungen.",
    diseases_c3_tag: "Schallschutz & Automatisierung",
    diseases_h2_3: "3. Die Rolle von Cobots in der Ergonomie",
    diseases_p3_1: "Kollaborative Roboter übernehmen das Heben schwerer Lasten und unterstützen den Bediener direkt am Arbeitsplatz.",
    diseases_callout_title: "NEXAUT – Ergonomische Arbeitsplatzgestaltung",
    diseases_callout_text: "Wir entwickeln Roboterarbeitsplätze nach ergonomischen Richtlinien und entlasten Ihre Belegschaft nachhaltig.",
    diseases_h2_faq: "Häufig gestellte Fragen (FAQ)",
    diseases_faq_q1: "Benötigen Cobots Schutzumzäunungen?",
    diseases_faq_a1: "Nicht zwingend. Integrierte Kraftsensoren stoppen den Cobot bei Berührung sofort.",
    diseases_faq_q2: "Welche Normen regeln die Ergonomie?",
    diseases_faq_a2: "Relevant sind ISO 11228, ISO 10218 und die Spezifikation ISO/TS 15066.",
    diseases_faq_q3: "Wie rechnet sich die Investition?",
    diseases_faq_a3: "Einsparungen bei Ausfallzeiten und Rekrutierungskosten führen zu einer schnellen Amortisation.",
    diseases_h2_5: "Zusammenfassung – Gesunde Mitarbeiter für eine stabile Produktion",
    diseases_p5_1: "Die Vermeidung von Berufskrankheiten ist ein strategischer Vorteil. Kontaktieren Sie das NEXAUT-Team!"
  }
};