window.POST_TRANSLATIONS = {
  pl: {
    vass_meta_desc: "Standard VASS 6 to precyzyjny zestaw wytycznych programistycznych i sprzętowych. Sprawdź, dlaczego koncern VW go wymaga i jak wpływa na projekty automotive.",
    vass_page_title: "Czym jest standard VASS 6 w automatyce i dlaczego VW go wymaga? – NEXAUT",
    vass_h1: "Czym jest standard VASS 6&nbsp;w&nbsp;automatyce i&nbsp;dlaczego koncern VW go wymaga?",
    vass_intro: "Standard VASS 6&nbsp;to jeden z&nbsp;najbardziej rygorystycznych i&nbsp;zaawansowanych standardów automatyzacji na&nbsp;świecie. Opracowany przez Grupę Volkswagen, stanowi bezwzględny wymóg dla dostawców maszyn, robotyków i&nbsp;programistów PLC budujących linie produkcyjne dla marek VW, Audi, SEAT, Škoda oraz Porsche.",
    vass_h2_1: "Geneza i definicja: Co oznacza skrót VASS?",
    vass_p1_1: "Nazwa standardu pochodzi od&nbsp;akronimu głównych marek koncernu: <strong>V</strong>olkswagen, <strong>A</strong>udi, <strong>S</strong>EAT oraz <strong>S</strong>koda. Najnowsza generacja – <strong>VASS 6</strong> (bazująca na&nbsp;środowisku Siemens TIA Portal oraz robotach KUKA/FANUC) – definiuje jednolitą strukturę sprzętową, programową i&nbsp;wizualizacyjną dla fabryk na&nbsp;całym świecie.",
    vass_p1_2: "Głównym celem VASS jest uniknięcie sytuacji, w&nbsp;której każda linia produkcyjna zaprojektowana przez zewnętrznego integratora ma&nbsp;unikalną, „autorską” architekturę sterowania. Dzięki standaryzacji, utrzymanie ruchu w&nbsp;dowolnej fabryce VW operuje na&nbsp;identycznych blokach funkcyjnych, diagnostyce i&nbsp;interfejsie HMI.",
    vass_h2_2: "Filary standardu VASS 6 w praktyce inżynieryjnej",
    vass_p2_intro: "Wdrożenie VASS 6 obejmuje kompleksowe zasady w&nbsp;czterech głównych obszarach technicznych:",
    vass_li_2_1: "<strong>Sterowniki PLC i TIA Portal:</strong> Ściśle określona struktura bloków FB/FC, bibliotek funkcjonalnych oraz numeracji zmiennych. Zdecentralizowane sterowanie opiera się na&nbsp;sieciach PROFINET z&nbsp;wykorzystaniem profili PROFIsafe.",
    vass_li_2_2: "<strong>Robotyzacja (KUKA KRC4 / FANUC):</strong> Standaryzowane makra ruchowe, dedykowane struktury sygnałowe interfejsu PLC-Robot oraz sztywne wytyczne dotyczące konfiguracji narzędzi (chwytaków, zgrzewadeł, pistoletów klejących).",
    vass_li_2_3: "<strong>Diagnostyka i HMI (WinCC / ProDiag):</strong> Jednolity wygląd paneli operatorskich. Każdy błąd na&nbsp;linii generuje natychmiastowy komunitat diagnostyczny wskazujący precyzyjny czujnik lub napęd bez potrzeby podłączania komputera inżynierskiego.",
    vass_li_2_4: "<strong>Hardware-Freigabeliste (Lista Zatwierdzonego Sprzętu):</strong> Integrator może używać wyłącznie komponentów (czujników, zaworów, wysp zaworowych, skanerów) znajdujących się na&nbsp;oficjalnej liście zatwierdzonej przez koncern VW.",
    vass_callout_title: "Wskazówka Inżyniera NEXAUT",
    vass_callout_text: "Tworzenie oprogramowania w&nbsp;standardzie VASS 6 różni się od&nbsp;klasycznego programowania PLC. Tutaj inżynier nie wymyśla architektury na&nbsp;nowo, lecz precyzyjnie składa aplikację z&nbsp;autoryzowanych bloków VASS i&nbsp;konfiguruje sekwencje. Kluczem do&nbsp;sukcesu jest bezbłędne przejście automatycznego audytu kodu (tzw. VASS-Check).",
    vass_img2_caption: "Rys 1. Zintegrowana architektura diagnostyki i&nbsp;sterowania w&nbsp;standardzie VASS 6.",
    vass_h2_3: "Dlaczego koncern Volkswagen bezwzględnie wymaga VASS 6?",
    vass_p3_1: "Dla koncernu produkującego miliony pojazdów rocznie, priorytetem jest minimalizacja przestojów (Downtime). Zastosowanie VASS 6 niesie ze&nbsp;sobą wymierne korzyści operacyjne i&nbsp;finansowe:",
    vass_box_title: "Główne zalety biznesowe standardu VASS 6:",
    vass_box_li1: "<strong>1. Błyskawiczne usuwanie awarii:</strong> Elektryk w&nbsp;fabryce w&nbsp;Poznaniu, Wolfsburgu czy Győr reaguje na&nbsp;awarię tak samo, bo&nbsp;interfejs i&nbsp;kody błędów są&nbsp;identyczne.",
    vass_box_li2: "<strong>2. Skróconi czas uruchomienia (Ramp-up):</strong> Standaryzowane moduły pozwalają skrócić fazę uruchomienia linii o&nbsp;nawet 30%.",
    vass_box_li3: "<strong>3. Łatwa rekonfiguracja linii:</strong> Przeniesienie celi zautomatyzowanej między zakładami nie wymaga ponownego szkolenia kadry technicznej.",
    vass_h2_4: "Wyzwania dla integratorów i dostawców maszyn",
    vass_p4_1: "Realizacja projektu w&nbsp;standardzie VASS 6 wiąże się z&nbsp;wysokim progiem wejścia dla firm automatyki. Do&nbsp;najważniejszych wyzwań należą:",
    vass_li_4_1: "<strong>Konieczność certyfikacji personelu:</strong> Inżynierowie PLC i&nbsp;robotycy muszą posiadać aktualne certyfikaty ukończenia szkoleń VASS (często organizowanych bezpośrednio przez koncern VW).",
    vass_li_4_2: "<strong>Rygorystyczne odbiory techniczne:</strong> Kod jest weryfikowany specjalnymi narzędziami skanującymi. Nawet najmniejsze odstępstwo od&nbsp;standardu blokuje odbiór końcowy instalacji.",
    vass_li_4_3: "<strong>Ciągłe aktualizacje (VASS Release):</strong> Standard stale ewoluuje (np. przejścia między wersjami VASS 5 a&nbsp;VASS 6), co&nbsp;wymaga ciągłego podnoszenia kwalifikacji zespołu.",
    vass_h2_faq: "Często Zadawane Pytania (FAQ)",
    vass_faq_q1: "Czym różni się VASS 5 od VASS 6?",
    vass_faq_a1: "Główną różnicą jest przejście ze&nbsp;starszego środowiska Step7 (Classic) na&nbsp;Siemens TIA Portal, wprowadzenie zaawansowanej diagnostyki ProDiag, integracja nowszych sterowników serii S7-1500 oraz zaktualizowane biblioteki dla robotów KUKA KRC4 i&nbsp;FANUC.",
    vass_faq_q2: "Czy standard VASS dotyczy tylko linii zwiastujących i spawalniczych?",
    vass_faq_a2: "Nie. Choć wywodzi się z&nbsp;obszaru spawalni (Body in White), VASS 6 obowiązuje obecnie na&nbsp;większości wydziałów: w&nbsp;tłoczniach, lakierniach, montażu końcowym oraz przy produkcji napędów elektrycznych i&nbsp;baterii.",
    vass_faq_q3: "Czy NEXAUT świadczy usługi programowania w standardzie VASS 6?",
    vass_faq_a3: "Tak. Zespół inżynierów NEXAUT posiada wieloletnie doświadczenie w&nbsp;projektowaniu, programowaniu PLC/robotów oraz uruchamianiu linii produkcyjnych zgodnych ze&nbsp;standardem VASS 6 dla zakładów branży automotive.",
    vass_h2_5: "Podsumowanie – Postaw na doświadczenie w projektach VASS",
    vass_p5_1: "Standard VASS 6 to&nbsp;gwarancja najwyższej niezawodności i&nbsp;jakości w&nbsp;przemysłu motoryzacyjnym. Sukces projektu realizowanego dla koncernu Volkswagen wymaga jednak partnera, który doskonale zna niuanse tej specyfikacji. Zespół NEXAUT zapewnia pełne wsparcie programistyczne i&nbsp;wdrożeniowe zgodne z&nbsp;wymaganiami VASS 6."
  },

  en: {
    vass_meta_desc: "The VASS 6 standard is a precise set of programming and hardware guidelines. Learn why the VW Group requires it and how it affects automotive projects.",
    vass_page_title: "What is the VASS 6 standard in automation and why does VW require it? – NEXAUT",
    vass_h1: "What is the VASS 6 Standard in Automation and Why Does the VW Group Require It?",
    vass_intro: "The VASS 6 standard is one of the most stringent and advanced automation standards globally. Developed by the Volkswagen Group, it is a mandatory requirement for machinery suppliers, roboticists, and PLC programmers building production lines for VW, Audi, SEAT, Škoda, and Porsche.",
    vass_h2_1: "Origins and Definition: What Does VASS Stand For?",
    vass_p1_1: "The acronym stems from the group's core brands: <strong>V</strong>olkswagen, <strong>A</strong>udi, <strong>S</strong>EAT, and <strong>S</strong>koda. The latest generation – <strong>VASS 6</strong> (based on Siemens TIA Portal and KUKA/FANUC robotics) – establishes a unified hardware, software, and visualization framework for plants worldwide.",
    vass_p1_2: "The primary objective of VASS is avoiding proprietary, custom control architectures designed by external system integrators. Standardization enables maintenance teams across any VW plant to operate on identical function blocks, diagnostics, and HMI interfaces.",
    vass_h2_2: "Pillars of the VASS 6 Standard in Engineering Practice",
    vass_p2_intro: "Implementing VASS 6 encompasses comprehensive rules across four core technical domains:",
    vass_li_2_1: "<strong>PLCs & TIA Portal:</strong> Strictly defined FB/FC block structures, standardized function libraries, and variable naming conventions. Decentralized control relies on PROFINET networks utilizing PROFIsafe profiles.",
    vass_li_2_2: "<strong>Robotics (KUKA KRC4 / FANUC):</strong> Standardized motion macros, dedicated PLC-to-Robot signal interfaces, and rigid guidelines for end-of-arm tooling configurations (grippers, welding guns, dispensing equipment).",
    vass_li_2_3: "<strong>Diagnostics & HMI (WinCC / ProDiag):</strong> Uniform operator panel styling. Every line fault generates instant diagnostic messages pin-pointing the exact sensor or actuator without requiring an engineering laptop.",
    vass_li_2_4: "<strong>Hardware-Freigabeliste (Approved Hardware List):</strong> Integrators must exclusively select components (sensors, valves, valve manifolds, safety scanners) listed on VW's official approval document.",
    vass_callout_title: "NEXAUT Engineering Pro-Tip",
    vass_callout_text: "Developing software in VASS 6 differs fundamentally from traditional PLC programming. Engineers do not invent control structures from scratch; instead, they assemble applications using pre-authorized VASS blocks and configure sequences. Success hinges on passing automated code audits (VASS-Check).",
    vass_img2_caption: "Fig 1. Integrated diagnostic and control architecture in the VASS 6 standard.",
    vass_h2_3: "Why Does the Volkswagen Group Strictly Enforce VASS 6?",
    vass_p3_1: "For an automotive manufacturer producing millions of vehicles annually, minimizing unplanned downtime is critical. Implementing VASS 6 provides measurable operational and financial benefits:",
    vass_box_title: "Key Business Advantages of VASS 6:",
    vass_box_li1: "<strong>1. Rapid Fault Resolution:</strong> Technicians in Poznań, Wolfsburg, or Győr respond to faults identically because interfaces and error codes are completely standardized.",
    vass_box_li2: "<strong>2. Accelerated Ramp-up:</strong> Pre-validated modules shorten line commissioning phases by up to 30%.",
    vass_box_li3: "<strong>3. Seamless Line Reconfiguration:</strong> Relocating automated cells between plants requires no re-training for technical staff.",
    vass_h2_4: "Challenges for System Integrators & Machine Builders",
    vass_p4_1: "Delivering VASS 6 projects entails a steep entry barrier for automation firms. Primary hurdles include:",
    vass_li_4_1: "<strong>Mandatory Personnel Certification:</strong> PLC engineers and roboticists must hold current VASS training certificates (often conducted directly by VW).",
    vass_li_4_2: "<strong>Rigorous Technical Audits:</strong> Code is audited using automated scanning tools. Minor deviations block final site acceptance.",
    vass_li_4_3: "<strong>Continuous Standard Releases:</strong> VASS evolves continuously (e.g., migrating between VASS 5 and VASS 6), necessitating ongoing team qualifications.",
    vass_h2_faq: "Frequently Asked Questions (FAQ)",
    vass_faq_q1: "What is the difference between VASS 5 and VASS 6?",
    vass_faq_a1: "The primary distinction is migrating from legacy Step7 Classic to Siemens TIA Portal, integrating advanced ProDiag diagnostics, supporting S7-1500 controllers, and updated robot libraries for KUKA KRC4 and FANUC.",
    vass_faq_q2: "Does VASS apply only to body shop and welding lines?",
    vass_faq_a2: "No. Although originating in Body in White (BIW), VASS 6 now applies across press shops, paint shops, final assembly, and EV battery or powertrain manufacturing.",
    vass_faq_q3: "Does NEXAUT provide programming services according to VASS 6?",
    vass_faq_a3: "Yes. NEXAUT engineers bring extensive experience in PLC/robot programming, system architecture, and commissioning compliant with VASS 6 for Tier-1 suppliers and OEMs.",
    vass_h2_5: "Summary – Leverage Technical Experience in VASS Projects",
    vass_p5_1: "The VASS 6 standard guarantees maximum operational reliability in the automotive industry. Successfully delivering projects for the Volkswagen Group requires a partner versed in every specification detail. NEXAUT provides complete programming and commissioning support aligned with VASS 6."
  },

  de: {
    vass_meta_desc: "Der VASS 6-Standard ist ein präzises Set von Programmier- und Hardware-Richtlinien. Erfahren Sie, warum der VW-Konzern ihn verlangt und wie er Automotive-Projekte beeinflusst.",
    vass_page_title: "Was ist der VASS 6-Standard in der Automatisierung und warum verlangt der VW-Konzern ihn? – NEXAUT",
    vass_h1: "Was ist der VASS 6-Standard in der Automatisierung und warum verlangt der VW-Konzern ihn?",
    vass_intro: "Der VASS 6-Standard gehört zu den anspruchsvollsten Automatisierungsstandards weltweit. Vom Volkswagen-Konzern entwickelt, ist er eine zwingende Vorgabe für Maschinenbauer, Robotiker und SPS-Programmierer bei Anlagen für VW, Audi, SEAT, Škoda und Porsche.",
    vass_h2_1: "Ursprung und Definition: Wofür steht VASS?",
    vass_p1_1: "Der Name leitet sich aus den Kernmarken des Konzerns ab: <strong>V</strong>olkswagen, <strong>A</strong>udi, <strong>S</strong>EAT und <strong>S</strong>koda. Die neueste Generation – <strong>VASS 6</strong> (basierend auf Siemens TIA Portal und KUKA/FANUC Robotern) – definiert eine einheitliche Hardware-, Software- und Visualisierungsstruktur weltweit.",
    vass_p1_2: "Hauptziel von VASS ist die Vermeidung herstellerspezifischer Eigenentwicklungen durch externe Integratoren. Dank der Standardisierung nutzt die Instandhaltung in jedem VW-Werk identische Bausteine, Diagnosen und HMI-Schnittstellen.",
    vass_h2_2: "Die Säulen des VASS 6-Standards in der Praxis",
    vass_p2_intro: "Die Umsetzung von VASS 6 umfasst umfassende Vorgaben in vier technischen Hauptbereichen:",
    vass_li_2_1: "<strong>SPS-Steuerungen & TIA Portal:</strong> Strenge Vorgaben für FB/FC-Bausteinstrukturen, Funktionsbibliotheken und Variablen. Die dezentrale Steuerung nutzt PROFINET mit PROFIsafe-Profilen.",
    vass_li_2_2: "<strong>Robotik (KUKA KRC4 / FANUC):</strong> Standardisierte Makros, definierte Schnittstellen-Signale zwischen SPS und Roboter sowie Vorgaben für Werkzeuge (Greifer, Schweißzangen, Klebesysteme).",
    vass_li_2_3: "<strong>Diagnose & HMI (WinCC / ProDiag):</strong> Einheitliches Design der Bediengeräte. Jeder Fehler generiert sofortige Klartextmeldungen mit exakter Sensor- oder Aktorzuordnung ohne Ingenieur-PC.",
    vass_li_2_4: "<strong>Hardware-Freigabeliste:</strong> Integratoren dürfen ausschließlich Komponenten (Sensoren, Ventile, Ventilinseln) verbauen, die auf der offiziellen VW-Freigabeliste stehen.",
    vass_callout_title: "NEXAUT Ingenieur-Tipp",
    vass_callout_text: "Die Softwareentwicklung im VASS 6-Standard unterscheidet sich grundlegend von klassischer SPS-Programmierung. Der Entwickler entwirft keine eigenen Strukturen, sondern fügt autorisierte VASS-Bausteine zusammen. Entscheidend ist das fehlerfreie Bestehen des automatischen Code-Audits (VASS-Check).",
    vass_img2_caption: "Abb. 1. Integrierte Diagnose- und Steuerungsarchitektur im VASS 6-Standard.",
    vass_h2_3: "Warum fordert der Volkswagen-Konzern VASS 6 ausnahmslos?",
    vass_p3_1: "Für einen Konzern mit Millionen Fahrzeugen pro Jahr steht die Minimierung von Stillstandszeiten (Downtime) an erster Stelle. VASS 6 bietet klare operative Vorteile:",
    vass_box_title: "Wichtige Geschäftsvorteile des VASS 6-Standards:",
    vass_box_li1: "<strong>1. Schnelle Störungsbehebung:</strong> Instandhalter in Poznań, Wolfsburg oder Győr reagieren identisch, da Schnittstellen und Fehlercodes vereinheitlicht sind.",
    vass_box_li2: "<strong>2. Verkürzter Anlauf (Ramp-up):</strong> Vorvalidierte Module verkürzen die Inbetriebnahmephase um bis zu 30 %.",
    vass_box_li3: "<strong>3. Einfache Anlagenumsetzung:</strong> Das Verlagern automatisierter Zellen zwischen Werken erfordert keine Neuschulung des Personals.",
    vass_h2_4: "Herausforderungen für Systemintegratoren und Maschinenbauer",
    vass_p4_1: "Die Umsetzung von VASS 6-Projekten erfordert hohe Qualifikationen. Zu den größten Herausforderungen zählen:",
    vass_li_4_1: "<strong>Zertifizierungspflicht für Personal:</strong> SPS-Programmierer und Robotiker müssen aktuelle VASS-Schulungszertifikate vorweisen.",
    vass_li_4_2: "<strong>Strenge technische Abnahmen:</strong> Der Code wird mit automatisierten Prüftools gescannt. Abweichungen verhindern die Endabnahme der Anlage.",
    vass_li_4_3: "<strong>Kontinuierliche Standards-Releases:</strong> VASS entwickelt sich stetig weiter (z. B. Migration von VASS 5 auf VASS 6), was kontinuierliche Weiterbildung verlangt.",
    vass_h2_faq: "Häufig gestellte Fragen (FAQ)",
    vass_faq_q1: "Was unterscheidet VASS 5 von VASS 6?",
    vass_faq_a1: "Der Hauptunterschied liegt im Wechsel von Step7 Classic auf Siemens TIA Portal, der Einbindung von ProDiag, der Unterstützung von S7-1500 Steuerungen und aktualisierten KUKA KRC4/FANUC Roboterkonfigurationen.",
    vass_faq_q2: "Gilt VASS nur für den Karosseriebau und Schweißanlagen?",
    vass_faq_a2: "Nein. Obwohl im Karosseriebau entstanden, gilt VASS 6 heute auch in Presswerken, Lackierereien, der Endmontage sowie in der Fertigung von E-Antrieben und Batterien.",
    vass_faq_q3: "Bietet NEXAUT Programmierung im VASS 6-Standard an?",
    vass_faq_a3: "Ja. Das NEXAUT-Team verfügt über langjährige Erfahrung in der SPS-/Roboter-Programmierung und Inbetriebnahme von VASS 6-konformen Anlagen für die Automobilindustrie.",
    vass_h2_5: "Zusammenfassung – Setzen Sie auf Erfahrung bei VASS-Projekten",
    vass_p5_1: "Der VASS 6-Standard garantiert höchste Zuverlässigkeit in der Automobilproduktion. Der Erfolg von VW-Projekten erfordert einen Partner, der diese Spezifikation im Detail beherrscht. NEXAUT bietet vollständige Programmier- und Inbetriebnahmeunterstützung nach VASS 6."
  }
};