window.POST_TRANSLATIONS = {
  pl: {
    scada_meta_desc: "System SCADA czy panel HMI? Poznaj różnice architektoniczne, koszty licencji, możliwości archiwizacji danych i skalowalność obu rozwiązań w automatyce przemysłowej.",
    scada_page_title: "System SCADA czy panel HMI? Co wybrać do wizualizacji procesu? – NEXAUT",
    scada_h1: "System SCADA czy panel HMI? Co wybrać do&nbsp;wizualizacji procesu?",
    scada_intro: "Planując modernizację lub budowę nowej linii produkcyjnej, inżynierowie stają przed fundamentalnym wyborem systemu wizualizacji i nadrzędnej kontroli. Choć zarówno panel HMI (Human-Machine Interface), jak i system SCADA (Supervisory Control and Data Acquisition) służą do interakcji człowieka z maszyną, ich architektura, cele oraz koszty wdrożenia znacząco się różnią.",
    scada_h2_1: "1. Czym różni się panel HMI od systemu SCADA?",
    scada_p1_1: "Główna różnica sprowadza się do skali i poziomu nadrzędności. Panel HMI to zazwyczaj dedykowane urządzenie sprzętowe (ekran dotykowy montowany na elewacji szafy), połączone bezpośrednio z jednym sterownikiem PLC. Jego zadaniem jest umożliwienie lokalnej obsługi maszyny (start/stop, zmiana parametrów, podgląd alarmów).",
    scada_p1_2: "System SCADA to z kolei zaawansowane oprogramowanie działające na serwerze lub stacjach PC, które zbiera dane z wielu sterowników PLC, wysp I/O i urządzeń pomiarowych rozmieszczonych na terenie całego zakładu. SCADA odpowiada za długoterminową archiwizację danych w bazach SQL, raportowanie, zaawansowane trendy oraz integrację z systemami klasy MES/ERP.",
    scada_h2_2: "2. Koszty licencji i sprzętu – Gdzie kryją się pułapki?",
    scada_p2_1: "W przypadku paneli HMI płacimy głównie za pojedyncze urządzenie fizyczne, a oprogramowanie runtime jest wbudowane w cenę panela. Licencjonowanie systemów SCADA opiera się natomiast na liczbie zmiennych procesowych (tzw. Tagów / PowerTags), liczbie stanowisk klienckich (Web Client / Client RT) oraz dodatkowych modułach (np. receptury, archiwizacja SQL, alarmowanie SMS).",
    scada_callout_title: "Złota Zasada Inżyniera NEXAUT",
    scada_callout_text: "Nie traktuj wyboru jako „HMI albo SCADA”. Najbardziej niezawodna architektura to hybryda: lokalny panel HMI na szafie sterowniczej zapewnia operatorowi szybkie sterowanie bezpośrednie bez opóźnień sieciowych, podczas gdy serwer SCADA zbiera dane ze wszystkich paneli do nadrzędnej analityki!",
    scada_h2_3: "3. Kiedy wybrać HMI, a kiedy zaawansowaną SCADĘ?",
    scada_p3_1: "Wybierz panel HMI, gdy: budujesz autonomiczną maszynę, budżet projektu jest mocno ograniczony, środowisko pracy wymaga wysokiego stopnia ochrony IP (np. strefa zmywania w przemyśle spożywczym), a sterowanie nie wymaga rozbudowanej analityki historycznej.",
    scada_p3_2: "Wybierz system SCADA, gdy: zarządzasz rozproszoną infrastrukturą (np. oczyszczalnia ścieków, elektrociepłownia, ciągła linia produkcyjna), potrzebujesz wielomonitorowej dyspozyczelni, rozbudowanego modułu raportowania do PDF/Excel oraz integracji z bazami SQL i systemami zarządzania produkcją MES.",
    scada_h2_4: "4. Nowoczesne trendy: Web HMI oraz Unifikacja (WinCC Unified, Ignition)",
    scada_p4_1: "Granica między HMI a SCADA zaciera się wraz z rozwojem technologii webowych (HTML5, SVG, JavaScript). Nowoczesne platformy (np. Siemens WinCC Unified, Inductive Automation Ignition czy AVEWA) pozwalają tworzyć wizualizacje raz i uruchamiać je zarówno na panelu dotykowym, jak i w przeglądarce internetowej na smartfonie, tablecie czy komputerze stacjonarnym.",
    scada_h2_faq: "Często Zadawane Pytania (FAQ)",
    scada_faq_q1: "Czy system SCADA może całkowicie zastąpić panele HMI na hali produkcyjnej?",
    scada_faq_a1: "Technicznie tak, jednak ze względów bezpieczeństwa i ciągłości pracy zaleca się pozostawienie lokalnych paneli HMI. W przypadku awarii sieci zakładowej lub serwera SCADA, lokalny panel HMI pozwala operatorowi bezpiecznie zatrzymać lub skontrolować maszynę.",
    scada_faq_q2: "Ile kosztuje wdrożenie systemu SCADA w porównaniu do panela HMI?",
    scada_faq_a2: "Panel HMI wraz z prostą aplikacją to koszt od kilkuset do kilku tysięcy euro. Wdrożenie licencjonowanego systemu SCADA dla całej hali z serwerem redundantnym i bazą danych SQL zaczyna się od kilkunastu tysięcy euro i rośnie wraz z liczbą punktów (Tagów).",
    scada_faq_q3: "Czy inżynierowie NEXAUT tworzą i migrują aplikacje wizualizacji SCADA / HMI?",
    scada_faq_a3: "Tak. Projektujemy nowe wizualizacje HMI/SCADA na platformach Siemens (WinCC Comfort/Advanced/Unified), Wonderware/AVEVA, Ignition, Asix oraz Weintek, a także wykonujemy migracje ze starych i wycofanych z rynku paneli na nowoczesne standardy webowe.",
    scada_h2_5: "Podsumowanie – Dobierz system wizualizacji skrojony na miarę",
    scada_p5_1: "Wybór między panelem HMI a systemem SCADA zależy od specyfiki procesu, wymogów archiwizacji danych i zaplanowanego budżetu. Prawidłowo zaprojektowany interfejs graficzny podnosi komfort pracy operatorów i skraca czas reakcji na stany awaryjne. Szukasz optymalnego rozwiązania dla swojego zakładu? Skontaktuj się z zespołem NEXAUT!"
  },

  en: {
    scada_meta_desc: "SCADA system or HMI panel? Explore architectural differences, licensing costs, data archiving capabilities, and scalability in industrial automation.",
    scada_page_title: "SCADA System or HMI Panel? What to Choose for Process Visualization? – NEXAUT",
    scada_h1: "SCADA System or HMI Panel? What to Choose for Process Visualization?",
    scada_intro: "When planning a plant modernization or new production line, engineers face a crucial choice for visualization and supervisory control. Although both HMI (Human-Machine Interface) panels and SCADA (Supervisory Control and Data Acquisition) systems connect humans to machinery, their architecture and costs differ significantly.",
    scada_h2_1: "1. What Is the Difference Between HMI and SCADA?",
    scada_p1_1: "The primary distinction comes down to scope and hierarchy. An HMI panel is dedicated hardware (touchscreen mounted on an enclosure) connected directly to a single PLC for local machine control.",
    scada_p1_2: "A SCADA system is supervisory software running on servers/PCs that collects telemetry from multiple PLCs, I/O islands, and field devices across the entire factory. SCADA handles long-term SQL archiving, plant-wide reporting, and MES/ERP integration.",
    scada_h2_2: "2. Hardware & Licensing Costs – Hidden Pitfalls",
    scada_p2_1: "HMI panels involve upfront hardware costs with bundled runtime licenses. SCADA licensing is tag-based (PowerTags), scaled by client connections (Web Client / Client RT) and add-on modules (SQL logging, alarm dispatchers).",
    scada_callout_title: "NEXAUT Golden Engineering Rule",
    scada_callout_text: "Do not view it as 'HMI vs SCADA'. The most resilient architecture is a hybrid: local HMI touchpanels for zero-latency machine control, combined with a centralized SCADA server for plant-wide analytics!",
    scada_h2_3: "3. When to Choose HMI vs SCADA?",
    scada_p3_1: "Choose an HMI panel for standalone machinery, tight budgets, high IP-rating requirements (e.g., washdown areas in food processing), or simple local control.",
    scada_p3_2: "Choose a SCADA system for distributed infrastructure (e.g., water treatment, power generation, continuous lines), multi-monitor control rooms, automated PDF/Excel reporting, and SQL/MES integration.",
    scada_h2_4: "4. Modern Trends: Web HMI & Unified Platforms (WinCC Unified, Ignition)",
    scada_p4_1: "The boundary between HMI and SCADA is blurring thanks to web standards (HTML5, SVG, JS). Next-gen platforms (Siemens WinCC Unified, Ignition, AVEVA) allow designing UI graphics once and rendering them natively on touch panels, smartphones, or desktop browsers.",
    scada_h2_faq: "Frequently Asked Questions (FAQ)",
    scada_faq_q1: "Can a SCADA system completely replace HMI panels on the shop floor?",
    scada_faq_a1: "Technically yes, but keeping local HMIs is recommended for safety and redundancy. If plant networks or SCADA servers fail, local HMIs ensure operators can safely stop and control machinery.",
    scada_faq_q2: "How much does a SCADA implementation cost compared to an HMI panel?",
    scada_faq_a2: "An HMI panel with runtime software costs hundreds to a few thousand euros. Full SCADA deployments with redundant servers and SQL logging start at tens of thousands of euros depending on tag counts.",
    scada_faq_q3: "Does NEXAUT develop and migrate SCADA and HMI applications?",
    scada_faq_a3: "Yes. We design HMI/SCADA solutions on Siemens (WinCC Comfort/Advanced/Unified), Wonderware/AVEVA, Ignition, Asix, and Weintek, as well as migrate legacy panel software to modern web-based architectures.",
    scada_h2_5: "Summary – Choose a Tailored Visualization Solution",
    scada_p5_1: "Selecting between HMI and SCADA depends on process complexity, data archiving demands, and budget. An intuitively designed GUI improves operator efficiency and reduces fault response time. Contact NEXAUT engineers for expert guidance!"
  },

  de: {
    scada_meta_desc: "SCADA-System oder HMI-Panel? Architektonische Unterschiede, Lizenzkosten, Datenarchivierung und Skalierbarkeit in der Industrieautomatisierung.",
    scada_page_title: "SCADA-System oder HMI-Panel? Was sollte gewählt werden? – NEXAUT",
    scada_h1: "SCADA-System oder HMI-Panel? Was sollte für die Prozessvisualisierung gewählt werden?",
    scada_intro: "Bei der Modernisierung oder dem Neubau von Produktionslinien steht die Wahl des Visualisierungs- und Steuerungssystems an. HMI-Panels und SCADA-Systeme erfüllen unterschiedliche Aufgaben hinsichtlich Architektur, Umfang und Investitionskosten.",
    scada_h2_1: "1. Worin unterscheidet sich ein HMI-Panel von einem SCADA-System?",
    scada_p1_1: "Ein HMI-Panel ist ein dediziertes Hardwaregerät für die lokale Maschinenbedienung vor Ort, das direkt mit einer SPS verbunden ist.",
    scada_p1_2: "Ein SCADA-System ist eine übergeordnete Softwarelösung auf Servern/PCs, die Daten von vielen SPSen und Feldgeräten im gesamten Werk sammelt, in SQL-Datenbanken archiviert und an MES/ERP-Systeme übergibt.",
    scada_h2_2: "2. Lizenz- und Hardwarekosten",
    scada_p2_1: "Bei HMI-Panels ist die Runtime-Software meist im Gerätepreis enthalten. SCADA-Lizenzen richten sich nach der Anzahl der Prozessvariablen (Tags), Client-Zugriffe und Zusatzmodule.",
    scada_callout_title: "Goldene NEXAUT Ingenieur-Regel",
    scada_callout_text: "Betrachten Sie die Entscheidung nicht als 'HMI oder SCADA'. Die beste Architektur ist eine Kombination: Lokale HMIs für verzögerungsfreie Maschinensteuerung und ein zentraler SCADA-Server für die werkweite Analyse!",
    scada_h2_3: "3. Wann HMI und wann SCADA wählen?",
    scada_p3_1: "Wählen Sie ein HMI-Panel für eigenständige Maschinen, begrenzte Budgets, hohe IP-Schutzarten und lokale Bedienung.",
    scada_p3_2: "Wählen Sie ein SCADA-System für verteilte Infrastrukturen (Wasserwerke, Kraftwerke, verettete Linien), Leitstände, umfangreiches Reporting und SQL/MES-Anbindungen.",
    scada_h2_4: "4. Moderne Trends: Web HMI & Unified-Plattformen (WinCC Unified, Ignition)",
    scada_p4_1: "Durch Webtechnologien (HTML5, JavaScript) verschwimmen die Grenzen. Moderne Plattformen (WinCC Unified, Ignition) ermöglichen die einmalige Erstellung von Visualisierungen zur Nutzung auf Panels, PCs und Mobilgeräten.",
    scada_h2_faq: "Häufig gestellte Fragen (FAQ)",
    scada_faq_q1: "Kann ein SCADA-System HMI-Panels in der Halle komplett ersetzen?",
    scada_faq_a1: "Technisch ja, aus Redundanz- und Sicherheitsgründen wird die Beibehaltung lokaler HMIs jedoch dringend empfohlen.",
    scada_faq_q2: "Wie viel kostet ein SCADA-System im Vergleich zu einem HMI-Panel?",
    scada_faq_a2: "Ein HMI-Panel kostet einige hundert bis hunderte Euro. SCADA-Systeme mit redundanten Servern beginnen bei mehreren zehntausend Euro je nach Tag-Anzahl.",
    scada_faq_q3: "Erstellt und migriert NEXAUT SCADA- und HMI-Anwendungen?",
    scada_faq_a3: "Ja. Wir konzipieren HMI/SCADA-Lösungen (Siemens WinCC Unified, AVEVA, Ignition, Weintek) und migrieren Altsysteme auf moderne Standards.",
    scada_h2_5: "Zusammenfassung – Maßgeschneiderte Visualisierungslösungen",
    scada_p5_1: "Die Entscheidung für HMI oder SCADA hängt von der Prozesskomplexität und den Datenanforderungen ab. Kontaktieren Sie das NEXAUT-Team für eine individuelle Beratung!"
  }
};