window.POST_TRANSLATIONS = {
  pl: {
    north_meta_desc: "Automatyzacja przemysłu spożywczego i&nbsp;przetwórczego na&nbsp;Północy Polski: Trójmiasto, Olsztyn, Bydgoszcz. Poznaj normy higieniczne, roboty IP69K i&nbsp;systemy wizyjne z&nbsp;NEXAUT.",
    north_page_title: "Automatyzacja Przemysłu Spożywczego: Trójmiasto, Olsztyn, Bydgoszcz – NEXAUT",
    north_h1: "Automatyzacja przemysłu spożywczego i&nbsp;produkcji na&nbsp;Północy Polski – Trójmiasto, Olsztyn, Bydgoszcz",
    north_intro: "Północna Polska słynie z&nbsp;silnego zaplecza przetwórstwa rolno-spożywczego, logistyki portowej oraz nowoczesnej chemii i&nbsp;przetwórstwa tworzyw. Zakłady produkcyjne w&nbsp;Trójmieście, Olsztynie czy Bydgoszczy stawiają czoła unikalnym wyzwaniom: surowym wymogom sanitarnym, agresywnym środkom czyszczącym oraz ogromnej prędkości pakowania.",
    north_h2_1: "1. Zagłębie przetwórcze i&nbsp;produkcyjne Północy",
    north_p1_1: "Specyfika przemysłowa regionów Pomorza, Warmii i&nbsp;Mazur oraz Kujaw wymusza stosowanie zaawansowanych technologicznie rozwiązań z&nbsp;obszaru Hygienic Design oraz automatycznej inspekcji jakości.",
    
    // Huby
    north_hub1_title: "Przetwórstwo Rybne &amp; Logistyka",
    north_hub1_desc: "Nowoczesne zakłady przetwórstwa ryb i&nbsp;owoców morza, pakownie portowe oraz zautomatyzowane magazyny chłodnicze wymagające robotów dostosowanych do&nbsp;niskich temperatur.",
    north_hub2_title: "Mleczarstwo &amp; Przemysł Mięsny",
    north_hub2_desc: "Giganci branży nabiałowej i&nbsp;mięsnej. Linie rozlewnicze, szybka paletyzacja kartonów oraz zrobotyzowane konfekcjonowanie w&nbsp;warunkach wysokiej wilgotności.",
    north_hub3_title: "Opakowania, Tworzywa &amp; Chemia",
    north_hub3_desc: "Zagłębie produkcji opakowań z&nbsp;tworzyw sztucznych dla przemysłu spożywczego i&nbsp;farmaceutycznego. Wtryskarki, etykietowanie i&nbsp;automatyczna inspekcja wizyjna.",

    north_h2_2: "2. Kluczowe technologie w&nbsp;fabrykach żywności i&nbsp;opakowań",
    north_p2_1: "Wdrażanie robotyzacji w&nbsp;zakładach spożywczych różni się fundamentalnie od&nbsp;branży elektromaszynowej. Wymaga stosowania specyficznych komponentów i&nbsp;standardów materiałowych:",
    north_li_1: "<strong class=\"text-white\">Roboty w&nbsp;klasie szczelności IP67 / IP69K (Washdown):</strong> Konstrukcje ze&nbsp;stali nierdzewnej (AISI 316L) bez ostrych krawędzi, odporne na&nbsp;codzienne mycie gorącą wodą pod wysokim ciśnieniem i&nbsp;pianowanie chemiczne.",
    north_li_2: "<strong class=\"text-white\">Roboty typu Delta (Pick-and-Place):</strong> Niezwykle szybkie manipulatory zawieszane nad transporterami, osiągające ponad 120-150 cykli na&nbsp;minutę przy układaniu świeżej lub zapakowanej żywności.",
    north_li_3: "<strong class=\"text-white\">Systemy wizyjne 2D/3D &amp; OCR:</strong> Automatyczna weryfikacja poprawności zgrzewu folii, obecności ciał obcych, kontrola etykiet i&nbsp;nadrukowanych dat ważności bez spowalniania linii.",
    north_li_4: "<strong class=\"text-white\">Smary i&nbsp;oleje NSF H1:</strong> Dopuszczone do&nbsp;przypadkowego kontaktu z&nbsp;żywnością w&nbsp;przekładniach robotów i&nbsp;chwytakach pneumatycznych.",

    north_callout_title: "NEXAUT – Automatyzacja Dedykowana Branży Spożywczej i&nbsp;Przetwórczej",
    north_callout_text: "Zespół inżynierów NEXAUT projektuje i&nbsp;integruje zrobotyzowane stanowiska pakowania, paletyzacji i&nbsp;kontroli jakości dopasowane do&nbsp;wymagań EHEDG i&nbsp;HACCP. Zapewniamy kompleksowe wdrożenia dla zakładów w&nbsp;Trójmieście, Olsztynie, Bydgoszczy oraz w&nbsp;całym pasie Polski Północnej.",
    north_h2_faq: "Często Zadawane Pytania (FAQ)",
    north_faq_q1: "Czym jest standard IP69K w&nbsp;robotyce spożywczej?",
    north_faq_a1: "IP69K to&nbsp;najwyższy poziom ochrony przed wnikaniem pyłu i&nbsp;wody. Urządzenia o&nbsp;tym standardzie mogą być myte strumieniem wody o&nbsp;temp. do&nbsp;80°C pod ciśnieniem do&nbsp;100 barów z&nbsp;bliskiej odległości, co&nbsp;jest standardem w&nbsp;zakładach mięsnych czy mleczarskich.",
    north_faq_q2: "Jak systemy wizyjne pomagają w&nbsp;redukcji zwrotów produktów spożywczych?",
    north_faq_a2: "Systemy wizyjne (np. Cognex, Keyence) natychmiast odrzucają opakowania z&nbsp;nieczytelnym kodem kreskowym, błędną datą przydatności lub uszkodzonym zgrzewem tacki, eliminując ryzyko wycofania całej partii towaru z&nbsp;sieci handlowych.",
    north_faq_q3: "Czy roboty mogą pracować w&nbsp;mroźniach przy temperaturach -25°C?",
    north_faq_a3: "Tak. Stosuje się wówczas specjalne wykonania robotów paletyzujących wyposażone w&nbsp;wbudowane systemy podgrzewania przekładni oraz specjalne pokrowce izotermiczne odporne na&nbsp;kondensację pary wodnej.",
    north_h2_5: "Podsumowanie – Postaw na&nbsp;nowoczesną i&nbsp;higieniczną produkcję",
    north_p5_1: "Automatyzacja w&nbsp;przemyśle spożywczym to&nbsp;gwarancja stałej wydajności, bezpieczeństwa sanitarnego i&nbsp;pełnej identyfikowalności serii produkcyjnych (Traceability). Planujesz modernizację zakładu na&nbsp;Północy Polski? Skontaktuj się z&nbsp;ekspertami NEXAUT!"
  },

  en: {
    north_meta_desc: "Food industry and manufacturing automation in Northern Poland: Tri-City, Olsztyn, Bydgoszcz. Hygienic design, IP69K robots, and vision inspection with NEXAUT.",
    north_page_title: "Food Industry Automation: Tri-City, Olsztyn, Bydgoszcz – NEXAUT",
    north_h1: "Food industry and manufacturing automation in Northern Poland – Tri-City, Olsztyn, Bydgoszcz",
    north_intro: "Northern Poland is famous for food processing, port logistics, and packaging manufacturing. Factories in Tri-City, Olsztyn, and Bydgoszcz face strict sanitary demands, harsh washdowns, and high packaging speeds.",
    north_h2_1: "1. Food Processing & Manufacturing Hubs of the North",
    north_p1_1: "Pomerania, Warmia-Masuria, and Kuyavia require advanced Hygienic Design solutions and automated vision quality checks.",
    north_hub1_title: "Fish Processing & Port Logistics",
    north_hub1_desc: "Seafood processing plants, port packaging units, and automated cold storage facilities needing low-temperature robotics.",
    north_hub2_title: "Dairy & Meat Industry",
    north_hub2_desc: "Dairy and meat giants featuring bottling lines, high-speed carton palletizing, and robotic handling under high humidity.",
    north_hub3_title: "Packaging, Plastics & Chemicals",
    north_hub3_desc: "Plastics packaging hubs for food and pharma. Injection molding automation, labeling, and vision inspection.",
    north_h2_2: "2. Key Technologies in Food & Packaging Automation",
    north_p2_1: "Food automation requires specialized material standards and hygienic components:",
    north_li_1: "<strong class=\"text-white\">IP67 / IP69K Washdown Robots:</strong> Stainless steel (AISI 316L) smooth designs resistant to high-pressure hot water and chemical foam cleaning.",
    north_li_2: "<strong class=\"text-white\">Delta Robots (Pick-and-Place):</strong> High-speed manipulators exceeding 120-150 cycles/min for primary and secondary food packaging.",
    north_li_3: "<strong class=\"text-white\">2D/3D Vision Systems & OCR:</strong> Automated tray seal inspection, foreign object detection, and expiration date verification.",
    north_li_4: "<strong class=\"text-white\">NSF H1 Lubricants:</strong> Food-grade lubricants safe for incidental food contact inside robot gears.",
    north_callout_title: "NEXAUT – Dedicated Food & Processing Automation",
    north_callout_text: "NEXAUT engineers design robotic packaging, palletizing, and vision inspection lines compliant with EHEDG and HACCP standards for plants across Northern Poland.",
    north_h2_faq: "Frequently Asked Questions (FAQ)",
    north_faq_q1: "What is IP69K protection in food robotics?",
    north_faq_a1: "IP69K is the highest ingress protection rating, allowing direct washdowns with 80°C hot water at up to 100 bar pressure.",
    north_faq_q2: "How do vision systems prevent food recalls?",
    north_faq_a2: "Vision sensors instantly reject unreadable barcodes, wrong expiration dates, or compromised seals before products leave the factory.",
    north_faq_q3: "Can robots operate in cold storage at -25°C?",
    north_faq_a3: "Yes. Palletizing robots designed for cold storage use gear heaters and insulated protective suits against condensation.",
    north_h2_5: "Summary – High-Speed Hygienic Manufacturing",
    north_p5_1: "Food automation delivers consistent output, sanitary safety, and full batch traceability. Planning a plant upgrade in Northern Poland? Contact NEXAUT today!"
  },

  de: {
    north_meta_desc: "Automatisierung der Lebensmittelindustrie in Nordpolen: Dreistadt, Olsztyn, Bydgoszcz. Hygienic Design, IP69K Roboter und Bildverarbeitung.",
    north_page_title: "Automatisierung Lebensmittelindustrie: Dreistadt, Olsztyn, Bydgoszcz – NEXAUT",
    north_h1: "Automatisierung der Lebensmittelindustrie in Nordpolen – Dreistadt, Olsztyn, Bydgoszcz",
    north_intro: "Nordpolen zeichnet sich durch Lebensmittelverarbeitung, Hafenlogistik und Verpackungsherstellung aus. Es gelten höchste Hygieneanforderungen.",
    north_h2_1: "1. Verarbeitungs- und Produktionszentren im Norden",
    north_p1_1: "Die Regionen Pommern, Ermland-Masuren und Kujawien setzen verstärkt auf Hygienic Design und optische Qualitätskontrolle.",
    north_hub1_title: "Fischverarbeitung & Logistik",
    north_hub1_desc: "Fischverarbeitungsbetriebe und automatisierte Kühlhäuser mit kältefesten Robotern.",
    north_hub2_title: "Molkerei & Fleischindustrie",
    north_hub2_desc: "Abfüllanlagen, schnelle Kartonpalettierung und Roboterhandhabung unter hoher Luftfeuchtigkeit.",
    north_hub3_title: "Verpackung & Kunststoffe",
    north_hub3_desc: "Kunststoffverpackungen für Lebensmittel und Pharma mit Spritzgussautomation und Etikettenprüfung.",
    north_h2_2: "2. Schlüsseltechnologien in der Lebensmittelautomation",
    north_p2_1: "Die Automatisierung in der Lebensmittelbranche erfordert spezielle Komponenten:",
    north_li_1: "<strong class=\"text-white\">IP67 / IP69K Washdown-Roboter:</strong> Edelstahlkonstruktionen (AISI 316L) für die Reinigung mit Hochdruck-Heißwasser.",
    north_li_2: "<strong class=\"text-white\">Delta-Roboter (Pick-and-Place):</strong> Hochgeschwindigkeitsroboter mit über 120-150 Zyklen/Min.",
    north_li_3: "<strong class=\"text-white\">2D/3D-Bildverarbeitung & OCR:</strong> Automatische Siegelnahtprüfung und Haltbarkeitsdatumkontrolle.",
    north_li_4: "<strong class=\"text-white\">NSF H1 Schmierstoffe:</strong> Lebensmittelechte Schmierstoffe für maximale Produktsicherheit.",
    north_callout_title: "NEXAUT – Spezialisierte Lebensmittel-Automatisierung",
    north_callout_text: "Wir planen und integrieren Roboterzellen für Verpackung, Palettierung und Qualitätskontrolle nach EHEDG- und HACCP-Standards.",
    north_h2_faq: "Häufig gestellte Fragen (FAQ)",
    north_faq_q1: "Was bedeutet die Schutzart IP69K?",
    north_faq_a1: "IP69K ermöglicht die direkte Reinigung mit bis zu 80 °C heißem Wasser bei 100 bar Druck.",
    north_faq_q2: "Wie verhindern Kamerasysteme Produktrückrufe?",
    north_faq_a2: "Bildverarbeitungssysteme schleusen fehlerhafte Verpackungen oder unleserliche Codes sofort aus.",
    north_faq_q3: "Können Roboter im Tiefkühlbereich (-25 °C) arbeiten?",
    north_faq_a3: "Ja, mit Getriebeheizungen und Isolieranzügen ist der dauerhafte Betrieb in Tiefkühlhalden möglich.",
    north_h2_5: "Zusammenfassung – Moderne und hygienische Produktion",
    north_p5_1: "Die Automatisierung sichert Qualität und Rückverfolgbarkeit. Planen Sie eine Modernisierung in Nordpolen? Kontaktieren Sie NEXAUT!"
  }
};