window.POST_TRANSLATIONS = {
  pl: {
    slask_meta_desc: "Gdzie w&nbsp;Polsce jest najwięcej zautomatyzowanych firm? Katowice i&nbsp;Śląsk to&nbsp;serce polskiej robotyzacji. Sprawdź, jak KSSE i&nbsp;przemysł 4.0 napędzają rozwój regionu.",
    slask_page_title: "Gdzie jest najwięcej zautomatyzowanych firm? Katowice i&nbsp;Śląsk liderem przemysłu – NEXAUT",
    slask_h1: "Gdzie jest najwięcej zautomatyzowanych firm? Katowice i&nbsp;Śląsk liderem przemysłu",
    slask_intro: "Polska wyrosła na&nbsp;jednego z&nbsp;kluczowych graczy przemysłowych w&nbsp;Europie Środkowo-Wschodniej, ale to&nbsp;Górny Śląsk wraz z&nbsp;aglomeracją katowicką niezmiennie dzierży palmę pierwszeństwa pod względem gęstości zrobotyzowanych zakładów.",
    slask_h2_1: "1. Katowicka Specjalna Strefa Ekonomiczna (KSSE) – Serce Robotyzacji",
    slask_p1_1: "Nie da się rozmawiać o&nbsp;automatyzacji na&nbsp;Śląsku bez wspomnienia o&nbsp;KSSE. Wielokrotnie uznawana za&nbsp;najlepszą strefę ekonomiczną w&nbsp;Europie, stała się domem dla setek nowoczesnych fabryk. Wysoce rozwinięta infrastruktura drogowa (skrzyżowanie autostrad A1 i&nbsp;A4) oraz bliskość rynków zagranicznych sprawiają, że&nbsp;inwestorzy właśnie tu budują flagowe zakłady.",
    
    // Wskaźniki / Statystyki
    slask_stat_1: "Lider gęstości robotów w&nbsp;PL",
    slask_stat_2: "Fabryk z&nbsp;integracją PLC/SCADA",
    slask_stat_3: "Ciągłość ruchu i&nbsp;serwis zdalny",

    slask_h2_2: "2. Automotive i&nbsp;Elektromobilność jako Lokomotywa Regionu",
    slask_p2_1: "Głównym motorem napędowym robotyzacji na&nbsp;Śląsku jest branża motoryzacyjna. Zakłady produkujące samochody, baterie do&nbsp;pojazdów elektrycznych (EV), układy kierownicze oraz komponenty z&nbsp;plastiku i&nbsp;metalu wymagają najwyższego poziomu powtarzalności oraz wyśrubowanych norm bezpieczeństwa.",
    
    // Karty regionalne
    slask_cards_title: "Kluczowe Ośrodki Przemysłowe w&nbsp;Polsce:",
    slask_card1_title: "Śląsk &amp; Małopolska",
    slask_card1_desc: "Gliwice, Tychy, Katowice, Kraków. Główny nacisk na&nbsp;spawalnictwo, linie zgrzewalnicze, standardy VASS/BMW oraz paletyzację.",
    slask_card1_tag: "Automotive / Metal / EV",
    slask_card2_title: "Polska Centralna &amp; Zachód",
    slask_card2_desc: "Poznań, Łódź, Wrocław. Liderzy w&nbsp;zakresie systemów transportu wewnątrzmagazynowego (AGV/AMR), e-commerce i&nbsp;FMCG.",
    slask_card2_tag: "Intralogistyka / Spożywczy",
    slask_card3_title: "Dolina Lotnicza &amp; Północ",
    slask_card3_desc: "Rzeszów, Mielec, Trójmiasto. Obróbka skrawaniem CNC, zaawansowane systemy wizyjne i&nbsp;automatyzacja procesów higienicznych.",
    slask_card3_tag: "Lotnictwo / CNC / Marine",

    slask_h2_3: "3. Rola Integratora w&nbsp;sukcesie fabryki",
    slask_p3_1: "Samo zakupienie nowoczesnych robotów czy sterowników PLC nie gwarantuje sukcesu. Kluczem jest poprawna integracja systemowa: napisanie przejrzystego kodu PLC, optymalizacja trajektorii robotów, przygotowanie intuicyjnej wizualizacji SCADA/HMI oraz zapewnienie bezpieczeństwa maszynowego.",
    slask_callout_title: "Dlaczego klienci wybierają NEXAUT?",
    slask_callout_text: "Działamy elastycznie na&nbsp;terenie całej Polski i&nbsp;za granicą. Niezależnie od&nbsp;lokalizacji Twojego zakładu, zapewniamy kompleksowe wykonawstwo – od&nbsp;koncepcji i&nbsp;algorytmów sterowania, przez montaż i&nbsp;wdrożenie na&nbsp;obiekcie, aż po&nbsp;zdalne wsparcie serwisowe.",
    slask_h2_faq: "Często Zadawane Pytania (FAQ)",
    slask_faq_q1: "W&nbsp;których miastach na&nbsp;Śląsku znajduje się najwięcej zrobotyzowanych zakładów?",
    slask_faq_a1: "Największe zagęszczenie zautomatyzowanych fabryk występuje w&nbsp;Gliwicach, Tychach, Katowicach, Sosnowcu, Dąbrowie Górniczej oraz Bielsku-Białej, głównie w&nbsp;obrębie podstref Katowickiej Specjalnej Strefy Ekonomicznej.",
    slask_faq_q2: "Czy firmy z&nbsp;innych regionów Polski mogą skorzystać z&nbsp;usług integracji NEXAUT?",
    slask_faq_a2: "Tak! Mimo że&nbsp;Śląsk jest naszym naturalnym środowiskiem, realizujemy projekty automatyzacji i&nbsp;robotyzacji w&nbsp;całej Polsce (m.in. Wrocław, Poznań, Kraków, Warszawa, Rzeszów, Trójmiasto) oraz dla klientów zagranicznych.",
    slask_faq_q3: "Jakie standardy programowania dominują w&nbsp;śląskich fabrykach?",
    slask_faq_a3: "Ze&nbsp;względu na&nbsp;dominację branży motoryzacyjnej, ogromną popularnością cieszą się korporacyjne standardy programowania PLC i&nbsp;robotów, takie jak VASS (koncern VW), BMW GS9, Integra czy Siemens TIA Portal wg wytycznych Klienta.",
    slask_h2_5: "Podsumowanie – Zbuduj przewagę technologiczną z&nbsp;NEXAUT",
    slask_p5_1: "Górny Śląsk pozostaje niedoścignionym wzorem w&nbsp;zakresie skali i&nbsp;tempa automatyzacji przemysłu. Niezależnie od&nbsp;tego, czy Twój zakład mieści się w&nbsp;Katowicach, czy w&nbsp;innym zakątku Polski, inwestycja w&nbsp;nowoczesne sterowanie PLC i&nbsp;robotyzację to&nbsp;jedyna droga do&nbsp;utrzymania konkurencyjności. Skontaktuj się z&nbsp;nami i&nbsp;sprawdź, jak możemy zoptymalizować Twój proces!"
  },

  en: {
    slask_meta_desc: "Which region has the most automated companies? Katowice and Silesia are the heart of Polish robotics.",
    slask_page_title: "Which regions have the most automated companies? Katowice and Silesia – NEXAUT",
    slask_h1: "Which regions have the most automated companies? Katowice and Silesia as industrial leaders",
    slask_intro: "Poland has become a major CEE industrial player, but Upper Silesia and Katowice remain the leaders in robot density.",
    slask_h2_1: "1. Katowice Special Economic Zone (KSSE) – The Heart of Robotics",
    slask_p1_1: "KSSE is consistently named among the top economic zones in Europe, hosting hundreds of advanced manufacturing plants.",
    slask_stat_1: "Leader in Robot Density (PL)",
    slask_stat_2: "Factories with PLC/SCADA",
    slask_stat_3: "24/7 Remote Service & Support",
    slask_h2_2: "2. Automotive & Electromobility Driving Regional Growth",
    slask_p2_1: "The automotive sector is the primary driver of regional automation. EV battery plants and Tier-1 suppliers demand strict precision and safety.",
    slask_cards_title: "Key Industrial Hubs in Poland:",
    slask_card1_title: "Silesia & Lesser Poland",
    slask_card1_desc: "Gliwice, Tychy, Katowice, Kraków. Focus on welding, VASS/BMW automotive standards, and palletizing.",
    slask_card1_tag: "Automotive / Metal / EV",
    slask_card2_title: "Central & Western Poland",
    slask_card2_desc: "Poznań, Łódź, Wrocław. Leaders in warehouse intralogistics (AGV/AMR), e-commerce, and FMCG.",
    slask_card2_tag: "Intralogistics / Food",
    slask_card3_title: "Aviation Valley & North",
    slask_card3_desc: "Rzeszów, Mielec, Tri-City. Precision CNC machining, vision inspection, and hygienic processing.",
    slask_card3_tag: "Aviation / CNC / Marine",
    slask_h2_3: "3. The Role of System Integrators",
    slask_p3_1: "Buying robots isn't enough. Success relies on structured PLC code, robot trajectory tuning, intuitive SCADA/HMI, and machinery safety.",
    slask_callout_title: "Why Clients Choose NEXAUT",
    slask_callout_text: "We execute automation projects across Poland and abroad, providing complete services from control algorithms to site commissioning and support.",
    slask_h2_faq: "Frequently Asked Questions (FAQ)",
    slask_faq_q1: "Which Silesian cities host the most automated plants?",
    slask_faq_a1: "Gliwice, Tychy, Katowice, Sosnowiec, Dąbrowa Górnicza, and Bielsko-Biała hold the highest concentration of automated factories.",
    slask_faq_q2: "Can companies outside Silesia work with NEXAUT?",
    slask_faq_a2: "Yes! We execute automation and robotics projects across Poland and internationally.",
    slask_faq_q3: "Which programming standards dominate?",
    slask_faq_a3: "Automotive standards like VASS (VW Group), BMW GS9, Integra, and customized Siemens TIA Portal frameworks dominate.",
    slask_h2_5: "Summary – Build Your Technological Edge with NEXAUT",
    slask_p5_1: "Silesia sets the benchmark for industrial automation. Contact NEXAUT to optimize your production lines regardless of location."
  },

  de: {
    slask_meta_desc: "Wo gibt es die meisten automatisierten Unternehmen? Kattowitz und Schlesien als Spitzenreiter.",
    slask_page_title: "Wo gibt es die meisten automatisierten Unternehmen? Kattowitz und Schlesien – NEXAUT",
    slask_h1: "Wo gibt es die meisten automatisierten Unternehmen? Kattowitz und Schlesien als Industrie-Spitzenreiter",
    slask_intro: "Oberschlesien und die Metropole Kattowitz führen die polnische Industrieautomatisierung an.",
    slask_h2_1: "1. Sonderwirtschaftszone Katowice (KSSE) – Herz der Robotik",
    slask_p1_1: "Die KSSE ist eine der führenden Wirtschaftszonen Europas und beherbergt hunderte moderne Produktionsstätten.",
    slask_stat_1: "Führende Roboter-Dichte in PL",
    slask_stat_2: "Werke mit SPS/SCADA",
    slask_stat_3: "24/7 Fernwartung & Service",
    slask_h2_2: "2. Automotive & Elektromobilität als Treiber",
    slask_p2_1: "Die Automobilbranche verlangt höchste Wiederholgenauigkeit und strengste Sicherheitsstandards.",
    slask_cards_title: "Wichtige Industriezentren in Polen:",
    slask_card1_title: "Schlesien & Kleinpolen",
    slask_card1_desc: "Gliwice, Tychy, Katowice, Krakau. Fokus auf Schweißen, VASS/BMW-Automotive-Standards und Palettierung.",
    slask_card1_tag: "Automotive / Metall / EV",
    slask_card2_title: "Zentral- & Westpolen",
    slask_card2_desc: "Posen, Łódź, Breslau. Führend in Intralogistik (FTS/AGV), E-Commerce und FMCG.",
    slask_card2_tag: "Intralogistik / Lebensmittel",
    slask_card3_title: "Luftfahrtteil & Norden",
    slask_card3_desc: "Rzeszów, Mielec, Dreistadt. Präzisions-CNC-Bearbeitung, Bildverarbeitung und Hygiene-Prozesse.",
    slask_card3_tag: "Luftfahrt / CNC / Marine",
    slask_h2_3: "3. Die Rolle des Systemintegrators",
    slask_p3_1: "Saubere SPS-Programmierung, Roboterbahn-Optimierung und SCADA-Visualisierungen sind der Schlüssel zum Erfolg.",
    slask_callout_title: "Warum Kunden NEXAUT wählen",
    slask_callout_text: "Wir realisieren Automatisierungsprojekte in ganz Polen und im Ausland – von Steuerungsalgorithmen bis zur Inbetriebnahme vor Ort.",
    slask_h2_faq: "Häufig gestellte Fragen (FAQ)",
    slask_faq_q1: "In welchen Städten befinden sich die meisten Roboter?",
    slask_faq_a1: "Gliwice, Tychy, Katowice, Sosnowiec und Bielsko-Biała weisen die höchste Dichte auf.",
    slask_faq_q2: "Arbeitet NEXAUT auch außerhalb von Schlesien?",
    slask_faq_a2: "Ja, wir realisieren Projekte in ganz Polen sowie im internationalen Ausland.",
    slask_faq_q3: "Welche Standards dominieren?",
    slask_faq_a3: "Automotive-Standards wie VASS (VW), BMW GS9 sowie kundenspezifische Siemens TIA Portal-Lösungen.",
    slask_h2_5: "Zusammenfassung – Technologievorsprung mit NEXAUT",
    slask_p5_1: "Schlesien bleibt der Maßstab für Automatisierung. Kontaktieren Sie das NEXAUT-Team für Ihre Projektberatung!"
  }
};