window.POST_TRANSLATIONS = {
  pl: {
    covers_meta_desc: "Dlaczego warto stosować pokrowce na&nbsp;roboty przemysłowe? Ochrona przed pyłem, chemią i&nbsp;odpryskami spawalniczymi. Zmniejsz koszty serwisu i&nbsp;przestojów.",
    covers_page_title: "Dlaczego należy stosować pokrowce na&nbsp;roboty przemysłowe? – NEXAUT",
    covers_h1: "Dlaczego należy stosować pokrowce na&nbsp;roboty przemysłowe? Ochrona w&nbsp;trudnych warunkach",
    covers_intro: "Roboty przemysłowe to&nbsp;kosztowna inwestycja, która codziennie pracuje w&nbsp;skrajnie wymagających warunkach. Pył, agresywna chemia, opiłki metalu czy wysoka temperatura spawalnicza potrafią doprowadzić do&nbsp;kosztownych awarii uszczelnień i&nbsp;okablowania w&nbsp;zaledwie kilka miesięcy.",
    covers_h2_1: "1. Główne czynniki niszczące manipulatory na&nbsp;liniach produkcyjnych",
    covers_p1_1: "Nowoczesne roboty 6-osiowe posiadają fabryczne stopnie ochrony (np. IP65 lub IP67), jednak długotrwała ekspozycja na&nbsp;ścierny pył lub gorące odpryski szybko degraduje elastyczne osłony przegubów i&nbsp;przewody doprowadzające media.",
    covers_stat_1: "Spadek kosztów serwisu przegubów",
    covers_stat_2: "Dłuższa żywotność okablowania",
    covers_stat_3: "Dodatkowa osłona przed zalaniem",
    covers_h2_2: "2. Rodzaje pokrowców w&nbsp;zależności od&nbsp;środowiska pracy",
    covers_p2_1: "Nie ma jednego uniwersalnego pokrowca. Szyte na&nbsp;miarę ubrania ochronne na&nbsp;roboty wykonuje się ze&nbsp;specjalistycznych tkanin technicznych, dobranych pod&nbsp;konkretne zagrożenie.",
    covers_cards_title: "Kluczowe Obszary Zastosowania Pokrowców:",
    covers_card1_title: "Spawanie i&nbsp;Zgrzewanie",
    covers_card1_desc: "Tkaniny niepalne z&nbsp;powłoką silikonową lub kevlarową. Chronią przed płynnym metalem, iskrami oraz wysoką temperaturą promieniowania.",
    covers_card1_tag: "Kevlar / Trudnopalne",
    covers_card2_title: "Lakiernie i&nbsp;Chemia",
    covers_card2_desc: "Materiały antyelektrostatyczne (ATEX) oraz odporne na&nbsp;rozpuszczalniki i&nbsp;mgłę lakierniczą. Zapobiegają osadzaniu się farby na&nbsp;ramieniu robota.",
    covers_card2_tag: "ATEX / Antystatyczne",
    covers_card3_title: "Obróbka i&nbsp;Śrutowanie",
    covers_card3_desc: "Wzmocnione pokrowce odporne na&nbsp;ścieranie mechaniczne, opiłki metalu, chłodziwa oraz pył powstający przy szlifowaniu.",
    covers_card3_tag: "Wysoka Odporność CNC",
    covers_h2_3: "3. Jak czyszczenie i&nbsp;konserwacja pokrowca oszczędza budżet?",
    covers_p3_1: "Zamiast czyścić delikatne elementy robota i&nbsp;narażać czujniki na&nbsp;uszkodzenie, wystarczy zdemontować pokrowiec, poddać go czyszczeniu technicznemu lub wymianie. Czas wymiany ubrania na&nbsp;robocie to&nbsp;zaledwie kilkanaście minut, co&nbsp;eliminuje wielogodzinne przestojowe czyszczenie ramienia.",
    covers_callout_title: "NEXAUT – Dbałość o&nbsp;Pełną Niezawodność Cel Roboczych",
    covers_callout_text: "Projektując i&nbsp;wdrażając zrobotyzowane stanowiska pracy, zawsze analizujemy warunki środowiskowe. Pomagamy dobrać optymalne systemy ochrony osi oraz trasy prowadzenia okablowania (Dress Pack), minimalizując ryzyko kosztownych przestojów w&nbsp;Twoim zakładzie.",
    covers_h2_faq: "Często Zadawane Pytania (FAQ)",
    covers_faq_q1: "Czy pokrowiec nie ogranicza zakresu ruchów robota?",
    covers_faq_a1: "Dobrej jakości pokrowce szyte są na&nbsp;wymiar pod&nbsp;konkretny model robota (np. KUKA, ABB, Fanuc, Yaskawa) i&nbsp;posiadają tzw.&nbsp;harmonijki oraz elastyczne wstawki na&nbsp;przegubach, co&nbsp;pozwala na&nbsp;pełny zakres ruchów bez oporów.",
    covers_faq_q2: "Jak często należy wymieniać pokrowiec na&nbsp;robocie?",
    covers_faq_a2: "Zależy to&nbsp;od&nbsp;środowiska. W&nbsp;lakierniach lub przy czystym montażu pokrowiec służy latami. W&nbsp;bardzo agresywnych środowiskach śrutowniczych czy spawalniczych regeneruje się go lub wymienia co&nbsp;kilka lub kilkanaście miesięcy.",
    covers_faq_q3: "Czy pokrowce można stosować w&nbsp;przemyśle spożywczym?",
    covers_faq_a3: "Tak. Dostępne są specjalne pokrowce higieniczne z&nbsp;certyfikatem FDA, odporne na&nbsp;czyszczenie parowe i&nbsp;agresywne detergenty stosowane w&nbsp;zakładach spożywczych i&nbsp;farmaceutycznych.",
    covers_h2_5: "Podsumowanie – Zabezpiecz swój park maszynowy",
    covers_p5_1: "Koszt profesjonalnego pokrowca ochronnego stanowi zaledwie ułamek ceny naprawy zatartej przekładni czy wymiany zniszczonej wiązki kablowej. Inwestując w&nbsp;osłony robotów, zyskujesz pewność i&nbsp;ciągłość produkcji. Zgłoś się do&nbsp;NEXAUT, by&nbsp;dowiedzieć się więcej o&nbsp;zabezpieczaniu linii zrobotyzowanych!"
  },

  en: {
    covers_meta_desc: "Why use protective covers for industrial robots? Protection against dust, chemicals, and welding spatter. Reduce maintenance and downtime costs.",
    covers_page_title: "Why Should You Use Protective Covers for Industrial Robots? – NEXAUT",
    covers_h1: "Why Should You Use Protective Covers for Industrial Robots? Protection in Harsh Environments",
    covers_intro: "Industrial robots are a significant investment operating in harsh daily environments. Dust, aggressive chemicals, metal shavings, and welding heat can destroy seals and cabling in just a few months.",
    covers_h2_1: "1. Key Factors Damaging Manipulators on Production Lines",
    covers_p1_1: "Modern 6-axis robots feature factory protection ratings (e.g., IP65 or IP67), but prolonged exposure to abrasive dust or hot spatter quickly degrades flexible joint seals and media lines.",
    covers_stat_1: "Reduction in joint service costs",
    covers_stat_2: "Extended cabling lifespan",
    covers_stat_3: "Extra protection against liquid ingress",
    covers_h2_2: "2. Types of Protective Covers Based on the Working Environment",
    covers_p2_1: "There is no single universal cover. Custom-tailored robot protection suit designs utilize specialized technical fabrics chosen for specific hazards.",
    covers_cards_title: "Key Application Areas for Robot Covers:",
    covers_card1_title: "Welding and Spot Welding",
    covers_card1_desc: "Non-flammable fabrics with silicone or Kevlar coating. Protect against molten metal, sparks, and intense radiant heat.",
    covers_card1_tag: "Kevlar / Flame Retardant",
    covers_card2_title: "Paint Shops and Chemical Exposure",
    covers_card2_desc: "Antistatic materials (ATEX) resistant to solvents and paint overspray. Prevent paint buildup on the robot arm.",
    covers_card2_tag: "ATEX / Antistatic",
    covers_card3_title: "Machining and Shot Blasting",
    covers_card3_desc: "Reinforced covers resistant to mechanical abrasion, metal chips, coolants, and fine grinding dust.",
    covers_card3_tag: "High CNC Resistance",
    covers_h2_3: "3. How Cover Cleaning and Maintenance Saves Your Budget",
    covers_p3_1: "Instead of cleaning delicate robot components and risking sensor damage, simply remove the cover for technical cleaning or replacement. Changing a cover suit takes minutes, avoiding hours of production downtime for arm cleaning.",
    covers_callout_title: "NEXAUT – Ensuring Full Reliability of Robotic Cells",
    covers_callout_text: "When designing and deploying robotic workstations, we analyze environmental conditions thoroughly. We help select optimal axis protection systems and dress packs to minimize downtime risks in your plant.",
    covers_h2_faq: "Frequently Asked Questions (FAQ)",
    covers_faq_q1: "Does a protective cover restrict the robot's motion?",
    covers_faq_a1: "High-quality custom covers tailored to specific robot models (e.g., KUKA, ABB, Fanuc, Yaskawa) feature bellows and flexible joint inserts, ensuring smooth, unrestricted movement.",
    covers_faq_q2: "How often should a robot cover be replaced?",
    covers_faq_a2: "It depends on the operating environment. In paint shops or clean assembly, covers last for years. In harsh shot blasting or welding setups, they are reconditioned or replaced every few months.",
    covers_faq_q3: "Can covers be used in the food industry?",
    covers_faq_a3: "Yes. Special FDA-certified hygienic covers are available, built to withstand steam cleaning and harsh detergents used in food and pharmaceutical facilities.",
    covers_h2_5: "Summary – Secure Your Machinery Park",
    covers_p5_1: "The cost of a professional protective cover is a fraction of repairing a seized gearbox or replacing damaged wiring harnesses. Protect your robots to ensure production continuity. Contact NEXAUT to learn more!"
  },

  de: {
    covers_meta_desc: "Warum Schutzabdeckungen für Industrie-Roboter verwenden? Schutz vor Staub, Chemie und Schweißspritzern. Reduzieren Sie Wartungskosten und Ausfallzeiten.",
    covers_page_title: "Warum sollte man Schutzabdeckungen für Industrieroboter verwenden? – NEXAUT",
    covers_h1: "Warum sollte man Schutzabdeckungen für Industrieroboter verwenden? Schutz in rauen Umgebungen",
    covers_intro: "Industrieroboter sind eine wertvolle Investition, die unter extremen Bedingungen arbeitet. Staub, aggressive Chemikalien, Metallspäne und hohe Schweißtemperaturen können Dichtungen und Verkabelungen in wenigen Monaten beschädigen.",
    covers_h2_1: "1. Hauptfaktoren, die Manipulatoren in Fertigungslinien schädigen",
    covers_p1_1: "Moderne 6-Achs-Roboter besitzen werkseitige Schutzarten (z. B. IP65 oder IP67), jedoch beschädigt dauerhafter Kontakt mit Schleifstaub oder heißen Spritzern schnell Dichtungen und Leitungen.",
    covers_stat_1: "Senkung der Gelenkwartungskosten",
    covers_stat_2: "Längere Lebensdauer der Verkabelung",
    covers_stat_3: "Zusätzlicher Schutz gegen Flüssigkeiten",
    covers_h2_2: "2. Arten von Schutzabdeckungen je nach Arbeitsumgebung",
    covers_p2_1: "Es gibt keine universelle Schutzhülle. Maßgeschneiderte Roboterschutzbekleidung wird aus speziellen technischen Geweben hergestellt.",
    covers_cards_title: "Wichtigste Anwendungsbereiche für Schutzabdeckungen:",
    covers_card1_title: "Schweißen und Punktschweißen",
    covers_card1_desc: "Nicht brennbare Gewebe mit Silikon- oder Kevlarbeschichtung. Schutz vor flüssigem Metall, Funken und Strahlungswärme.",
    covers_card1_tag: "Kevlar / Schwer entflammbar",
    covers_card2_title: "Lackierereien und Chemie",
    covers_card2_desc: "Antistatische Materialien (ATEX), beständig gegen Lösungsmittel und Farbnebel. Verhindern Farbablagerungen am Roboterarm.",
    covers_card2_tag: "ATEX / Antistatisch",
    covers_card3_title: "Zerspanung und Strahlen",
    covers_card3_desc: "Verstärkte Schutzabdeckungen, beständig gegen mechanischen Abrieb, Späne, Kühlmittel und Schleifstaub.",
    covers_card3_tag: "Hohe CNC-Beständigkeit",
    covers_h2_3: "3. Wie Reinigung und Wartung der Schutzhülle das Budget schont",
    covers_p3_1: "Statt empfindliche Roboterteile mühsam zu reinigen, wird einfach die Schutzhülle abgenommen und gereinigt oder ersetzt. Der Wechsel dauert nur wenige Minuten.",
    covers_callout_title: "NEXAUT – Zuverlässigkeit für Ihre Roboterzellen",
    covers_callout_text: "Bei der Planung von Roboterarbeitsplätzen analysieren wir stets die Umgebungsbedingungen und wählen optimale Schutzsysteme und Dress Packs aus.",
    covers_h2_faq: "Häufig gestellte Fragen (FAQ)",
    covers_faq_q1: "Schränkt die Schutzhülle die Bewegungsfreiheit des Roboters ein?",
    covers_faq_a1: "Hochwertige, passgenaue Schutzabdeckungen (für KUKA, ABB, Fanuc, Yaskawa) verfügen über Faltenbälge und flexible Einsätze für uneingeschränkte Bewegung.",
    covers_faq_q2: "Wie oft muss die Schutzhülle ausgetauscht werden?",
    covers_faq_a2: "In sauberen Umgebungen hält sie jahrelang. In rauen Umgebungen wird sie alle paar Monate gewartet oder ersetzt.",
    covers_faq_q3: "Können Schutzabdeckungen in der Lebensmittelindustrie eingesetzt werden?",
    covers_faq_a3: "Ja. Es gibt spezielle FDA-zertifizierte Hygiene-Schutzhüllen, die dampfstrahl- und detergentienbeständig sind.",
    covers_h2_5: "Zusammenfassung – Sichern Sie Ihren Maschinenpark",
    covers_p5_1: "Die Kosten einer Schutzhülle betragen nur einen Bruchteil einer Reparatur. Investieren Sie in Roboterschutz und sichern Sie Ihre Produktion. Kontaktieren Sie NEXAUT!"
  }
};