window.POST_TRANSLATIONS = {
  pl: {
    int_meta_desc: "Integrator automatyki przemysłowej i robotyki z zasięgiem w całej Polsce. Katowice, Wrocław, Kraków, Poznań, Gdańsk. Poznaj etapy współpracy: FAT, SAT i serwis zdalny z NEXAUT.",
    int_page_title: "Integrator Automatyki Przemysłowej Polska: Katowice, Wrocław, Kraków, Poznań – NEXAUT",
    int_h1: "Integrator automatyki z&nbsp;zasięgiem w&nbsp;całej Polsce: Od Katowic, Wrocławia i&nbsp;Krakowa po Poznań i&nbsp;Gdańsk",
    int_intro: "Współczesna produkcja przemysłowa nie zna granic regionalnych. Zakłady wytwórcze na Górnym Śląsku, w Małopolsce, na Dolnym Śląsku, w Wielkopolsce czy na Pomorzu oczekują od integratora automatyki nie tylko najwyższych kompetencji inżynieryjnych, ale także elastyczności, szybkiego czasu reakcji i nowoczesnych narzędzi diagnostyki zdalnej.",
    int_h2_1: "1. Etapy realizacji projektów automatyzacji – Jak wygląda współpraca?",
    int_p1_1: "Profesjonalny proces integracji systemów PLC i robotyki gwarantuje bezpieczeństwo inwestycji, terminowość oraz minimalizację przestojów produkcyjnych u klienta:",
    
    // Etapy
    int_stage1_title: "Audyt, Koncepcja & Projekt",
    int_stage1_desc: "Wizja lokalna w zakładzie klienta, szczegółowa analiza cyklu pracy, doboru komponentów (Siemens, Beckhoff, KUKA, Fanuc) oraz przygotowanie projektu elektrycznego i oprogramowania.",
    int_stage2_title: "Prefabrykacja & Testy FAT",
    int_stage2_desc: "Montaż szaf sterowniczych oraz symulacja działania kodu PLC/HMI i robotów w hali integratora. Klient bierze udział w odbiorze FAT (Factory Acceptance Test) przed wysyłką do fabryki.",
    int_stage3_title: "Montaż & Odbiór SAT",
    int_stage3_desc: "Prace instalacyjne i wdrożeniowe bezpośrednio na obiekcie. Odbiór SAT (Site Acceptance Test), asysta przy uruchomieniu oraz szkolenia dla służb utrzymania ruchu.",
    int_stage4_title: "Zdalny Serwis & Umowy SLA",
    int_stage4_desc: "Szybka diagnostyka awarii poprzez zabezpieczone łącza VPN/Secomea, analiza logów w czasie rzeczywistym oraz stały dojazd serwisowy w wyznaczonym czasie reakcji.",

    int_h2_2: "2. Dlaczego warto wybrać ogólnopolskiego integratora automatyki?",
    int_p2_1: "Nowoczesne metody inżynieryjne znoszą bariery odległości. Dzięki standaryzacji kodu, cyfrowym bliźniakom (Digital Twin) i bezpiecznym kanałom łączności, wsparcie techniczne realizowane jest błyskawicznie:",
    int_li_1: "<strong class=\"text-white\">Standaryzowane oprogramowanie PLC/HMI:</strong> Kod pisany według dobrych praktyk (np. IEC 61131-3, OMAC, PackML), co ułatwia diagnostykę zakładowym automatykom.",
    int_li_2: "<strong class=\"text-white\">Kompleksowość (PLC, Robotyka, Wizja, Safety):</strong> Jeden partner odpowiedzialny za całe stanowisko – od projektu elektrycznego EPLAN, przez programowanie sterowników i robotów, po certyfikację CE.",
    int_li_3: "<strong class=\"text-white\">Szybka diagnostyka zdalna (VPN):</strong> Ponad 80% zgłoszeń i poprawek procesowych realizujemy zdalnie bez konieczności oczekiwania na przyjazd serwisanta.",
    int_li_4: "<strong class=\"text-white\">Gotowość na projekty zagraniczne:</strong> Doświadczenie w realizacjach zgodnych ze standardami europejskimi i międzynarodowymi (VDA, UL, ISO 13849).",

    int_callout_title: "NEXAUT – Twój Zaufany Integrator Automatyki w Polsce i Europie",
    int_callout_text: "Niezależnie od tego, czy Twój zakład znajduje się w Katowicach, Wrocławiu, Krakowie, Poznaniu, Warszawie, Łodzi czy Gdańsku – inżynierowie NEXAUT dostarczą zintegrowane systemy sterowania i stanowiska zrobotyzowane na najwyższym poziomie niezawodności.",
    int_h2_faq: "Często Zadawane Pytania (FAQ)",
    int_faq_q1: "Czym różnią się odbiory FAT od odbiorów SAT?",
    int_faq_a1: "Odbiór FAT (Factory Acceptance Test) odbywa się w warsztacie integratora na zmontowanym stanowisku testowym przed jego wysyłką. Odbiór SAT (Site Acceptance Test) przeprowadza się w docelowej fabryce klienta po pełnym montażu i podłączeniu do mediów produkcyjnych.",
    int_faq_q2: "Czy dostęp zdalny do szafy sterowniczej jest bezpieczny dla sieci zakładowej?",
    int_faq_a2: "Tak. Stosujemy przemysłowe routery VPN (np. Secomea, eWON) wyposażone w sprzętowe klucze szyfrujące, dwuskładnikową autoryzację (2FA) oraz fizyczne przełączniki dostępu sterowane przez obsługę fabryki.",
    int_faq_q3: "Czy NEXAUT podejmuje się modernizacji (Retrofitu) istniejących, starszych linii?",
    int_faq_a3: "Tak. Oferujemy wymianę wycofywanych ze sprzedaży sterowników (np. Siemens S7-300 na S7-1500), migrację paneli HMI oraz doposażenie linii w nowe roboty i systemy bezpieczeństwa wg dyrektywy maszynowej.",
    int_h2_5: "Podsumowanie – Rozpocznij współpracę z NEXAUT",
    int_p5_1: "Nowoczesna automatyzacja przemysłowa to inwestycja w elastyczność i ciągłość produkcji. Szukasz doświadczonego partnera do realizacji projektu automatyki lub robotyzacji w dowolnym miejscu w Polsce lub za granicą? Skontaktuj się z zespołem NEXAUT już dziś!"
  },

  en: {
    int_meta_desc: "Industrial automation and robotics integrator across Poland. Katowice, Wrocław, Kraków, Poznań, Gdańsk. Learn about our project phases: FAT, SAT, and remote service with NEXAUT.",
    int_page_title: "Industrial Automation Integrator Poland: Katowice, Wrocław, Kraków, Poznań – NEXAUT",
    int_h1: "Automation integrator across Poland: From Katowice, Wrocław, and Kraków to Poznań and Gdańsk",
    int_intro: "Modern manufacturing knows no regional boundaries. Factories in Upper Silesia, Lesser Poland, Lower Silesia, Greater Poland, or Pomerania demand not only top engineering skills but also agility, fast response times, and remote diagnostics.",
    int_h2_1: "1. Stages of Automation Projects – How Collaboration Works",
    int_p1_1: "A structured PLC and robotics integration process guarantees investment security, timely delivery, and minimal downtime:",
    int_stage1_title: "Audit, Concept & Design",
    int_stage1_desc: "On-site analysis, cycle time calculations, component selection (Siemens, Beckhoff, KUKA, Fanuc), and electrical/software design.",
    int_stage2_title: "Prefabrication & FAT Testing",
    int_stage2_desc: "Control cabinet assembly and code simulation in our facility. Clients attend Factory Acceptance Testing (FAT) before shipment.",
    int_stage3_title: "Installation & SAT Acceptance",
    int_stage3_desc: "On-site mechanical and electrical installation, Site Acceptance Testing (SAT), startup assistance, and maintenance team training.",
    int_stage4_title: "Remote Support & SLA Contracts",
    int_stage4_desc: "Fast troubleshooting via encrypted VPN routers, real-time log diagnostics, and guaranteed on-site arrival SLA times.",
    int_h2_2: "2. Why Partner with a Nationwide Integrator?",
    int_p2_1: "Modern engineering removes physical barriers through standardized code, digital twins, and secure remote connectivity:",
    int_li_1: "<strong class=\"text-white\">Standardized PLC/HMI Code:</strong> Programmed following industry standards (IEC 61131-3, OMAC) to simplify maintenance.",
    int_li_2: "<strong class=\"text-white\">End-to-End Delivery (PLC, Robotics, Vision, Safety):</strong> One responsible partner from EPLAN schematics to CE certification.",
    int_li_3: "<strong class=\"text-white\">Fast Remote Diagnostics (VPN):</strong> Over 80% of software adjustments and support issues resolved remotely without delay.",
    int_li_4: "<strong class=\"text-white\">International Project Capability:</strong> Proficient in global industrial standards (VDA, UL, ISO 13849).",
    int_callout_title: "NEXAUT – Your Trusted Automation Integrator in Poland & Europe",
    int_callout_text: "Whether your plant is located in Katowice, Wrocław, Kraków, Poznań, Warsaw, Łódź, or Gdańsk – NEXAUT engineers deliver reliable control systems and turnkey robotic cells.",
    int_h2_faq: "Frequently Asked Questions (FAQ)",
    int_faq_q1: "What is the difference between FAT and SAT testing?",
    int_faq_a1: "FAT (Factory Acceptance Test) takes place at the integrator's workshop before shipping. SAT (Site Acceptance Test) is performed at the client's plant after final installation.",
    int_faq_q2: "Is remote connection to control cabinets secure for plant IT networks?",
    int_faq_a2: "Yes. Industrial VPN routers (Secomea, eWON) feature hardware encryption, 2FA authorization, and physical key switches controlled by local operators.",
    int_faq_q3: "Does NEXAUT handle retrofits of older control systems?",
    int_faq_a3: "Yes. We specialize in upgrading obsolete PLCs (e.g., Siemens S7-300 to S7-1500), HMI migrations, and adding safety systems under Machine Directive.",
    int_h2_5: "Summary – Partner with NEXAUT Today",
    int_p5_1: "Industrial automation drives long-term manufacturing flexibility. Looking for a reliable integration partner in Poland or internationally? Contact NEXAUT today!"
  },

  de: {
    int_meta_desc: "Automatisierungs- und Robotikintegrator in ganz Polen. Kattowitz, Breslau, Krakau, Posen, Danzig. Etappen: FAT, SAT und Fernwartung von NEXAUT.",
    int_page_title: "Automatisierungsintegrator Polen: Kattowitz, Breslau, Krakau, Posen – NEXAUT",
    int_h1: "Automatisierungsintegrator in ganz Polen: Von Kattowitz, Breslau und Krakau bis Posen und Danzig",
    int_intro: "Moderne Industrieproduktion kennt keine regionalen Grenzen. Betriebe in Oberschlesien, Niederschlesien, Großpolen oder Pommern erwarten höchste Engineering-Kompetenz und Fernwartungsoptionen.",
    int_h2_1: "1. Projektablauf der Automatisierung – So läuft die Zusammenarbeit",
    int_p1_1: "Ein strukturierter Integrationsprozess garantiert Investitionssicherheit und kurze Ausfallzeiten:",
    int_stage1_title: "Audit, Konzept & Planung",
    int_stage1_desc: "Bestandsaufnahme vor Ort, Taktzeitanalyse, Komponentenauswahl (Siemens, Beckhoff, KUKA, Fanuc) und Elektrokonstruktion.",
    int_stage2_title: "Schaltschrankbau & FAT-Test",
    int_stage2_desc: "Schaltschrankverdrahtung und Simulation in der Halle des Integrators. Werksabnahme (FAT) mit dem Kunden vor der Auslieferung.",
    int_stage3_title: "Montage & SAT-Abnahme",
    int_stage3_desc: "Installation vor Ort beim Kunden, Baustellenabnahme (SAT), Inbetriebnahmebegleitung und Personalschulung.",
    int_stage4_title: "Fernwartung & SLA-Verträge",
    int_stage4_desc: "Schnelle Fehlerdiagnose über verschlüsselte VPN-Verbindungen und garantierte Service-Reaktionszeiten.",
    int_h2_2: "2. Vorteile eines landesweit agierenden Integrators",
    int_p2_1: "Moderne Engineering-Methoden und Fernwartung heben Distanzen auf:",
    int_li_1: "<strong class=\"text-white\">Standardisierte SPS-/HMI-Programmierung:</strong> Strukturierter Code nach IEC 61131-3 / OMAC zur einfachen Wartung.",
    int_li_2: "<strong class=\"text-white\">Alles aus einer Hand:</strong> Elektrokonstruktion, SPS- & Roboterprogrammierung sowie CE-Zertifizierung.",
    int_li_3: "<strong class=\"text-white\">Schnelle Fernwartung (VPN):</strong> Über 80 % aller Softwareanpassungen werden direkt per Fernzugriff gelöst.",
    int_li_4: "<strong class=\"text-white\">Erfahrung mit internationalen Projekten:</strong> Ausführung nach europäischen Normen (VDA, UL, ISO 13849).",
    int_callout_title: "NEXAUT – Ihr Integrator für Polen und Europa",
    int_callout_text: "Ob Kattowitz, Breslau, Krakau, Posen, Warschau oder Danzig – NEXAUT liefert schlüsselfertige Automatisierungslösungen.",
    int_h2_faq: "Häufig gestellte Fragen (FAQ)",
    int_faq_q1: "Was unterscheidet FAT- und SAT-Abnahmen?",
    int_faq_a1: "FAT findet in der Werkstatt des Integrators statt, SAT direkt am Kundenstandort nach der Endmontage.",
    int_faq_q2: "Ist der Fernzugriff auf den Schaltschrank sicher?",
    int_faq_a2: "Ja, der Zugriff erfolgt über Industrie-VPN-Router mit 2FA und physischen Schlüsselschaltern vor Ort.",
    int_faq_q3: "Führt NEXAUT auch Retrofits bestehender Anlagen durch?",
    int_faq_a3: "Ja, wir modernisieren veraltete SPS-Steuerungen (z. B. S7-300 auf S7-1500) und HMI-Systeme.",
    int_h2_5: "Zusammenfassung – Starten Sie Ihr Projekt mit NEXAUT",
    int_p5_1: "Automatisierung sichert Ihre Zukunftsfähigkeit. Suchen Sie einen erfahrenen Partner? Kontaktieren Sie das NEXAUT-Team!"
  }
};