window.POST_TRANSLATIONS = {
  pl: {
    cc_meta_desc: "Poznaj zasady Clean Code w programowaniu PLC. Standardyzacja tagów, architektura modułowa, maszyny stanów PackML oraz obsługa błędów wg normy IEC 61131-3.",
    cc_page_title: "Dobre praktyki programowania PLC – Clean Code – NEXAUT",
    cc_h1: "Dobre praktyki programowania PLC – jak pisać czysty i&nbsp;bezpieczny kod?",
    cc_intro: "W&nbsp;świecie automatyki przemysłowej panuje niepisana zasada: kod sterownika PLC pisze się raz, ale czyta i&nbsp;serwisuje setki razy. Dobre praktyki programowania (Clean Code) to&nbsp;nie estetyczny kaprys, lecz fundament niezawodności, skróconego czasu przestojów oraz bezpieczeństwa pracy maszyn. Sprawdź, jak pisać oprogramowanie PLC zgodnie z&nbsp;najlepszymi standardami inżynieryjnymi.",
    cc_h2_1: "1. Standardyzacja zmiennych i konwencje nazewnicze",
    cc_p1_1: "Zatroszcz się o&nbsp;to, aby nazwa każdej zmiennej natychmiast zdradzała jej przeznaczenie i&nbsp;typ. Unikaj niejednoznacznych skrótów typu <code>temp1</code> czy <code>M0.0</code>. W&nbsp;nowoczesnym programowaniu PLC wg&nbsp;normy IEC 61131-3 stosuje się czytelne przedrostki (tzw. konwencja węgierska lub CamelCase):",
    cc_h2_2: "2. Architektura modułowa i zasada DRY (Don't Repeat Yourself)",
    cc_p2_1: "Pisanie całej logiki maszyny w&nbsp;jednym blokowym pliku głównym (np. OB1) to&nbsp;prosta droga do&nbsp;tzw. „Spaghetti Code”. Prawidłowa struktura opiera się na&nbsp;podziale aplikacji na&nbsp;wielokrotnie używalne bloki funkcjonalne (FB) i&nbsp;funkcje (FC). Każde fizyczne urządzenie – silnik, zawór, czujnik analogowy – powinno posiadać swój własny, przetestowany blok biblioteczny z&nbsp;wyraźnie zdefiniowanym interfejsem wejść i&nbsp;wyjść.",
    cc_callout_title: "Złota Zasada Inżyniera NEXAUT",
    cc_callout_text: "Jeśli ten sam fragment kodu kopiujesz w&nbsp;projekcie więcej niż dwa razy, natychmiast zamień go w&nbsp;uniwersalny blok funkcyjny (FB). Zmiana logiki w&nbsp;jednym miejscu biblioteki automatycznie zaktualizuje działanie wszystkich obiektów na&nbsp;linii produkcyjnej.",
    cc_h2_3: "3. Maszyny stanów (State Machines) i standard PackML",
    cc_p3_1: "Sterowanie sekwencją pracy stacji roboczej powinno opierać się na&nbsp;jawnej maszynie stanów (np. przy użyciu instrukcji <code>CASE...OF</code> w&nbsp;języku SCL/ST). Zamiast gubić się w&nbsp;setkach flanek i&nbsp;zazębionych warunków <code>IF-THEN</code>, program jednoznacznie przechodzi przez zdefiniowane kroki: <i>INIT, IDLE, EXECUTE, STOPPING, ERROR</i>. Powszechne stosowanie standardu PackML ułatwia integrację maszyn od&nbsp;różnych dostawców.",
    cc_h2_4: "4. Wbudowana diagnostyka i bezpieczna obsługa błędów",
    cc_p4_1: "Czysty kod PLC nie tylko realizuje ruchy wykonawcze, ale precyzyjnie informuje operatora o&nbsp;problemach. Każdy siłownik powinien posiadać kontrolę czasu dojazdu do&nbsp;krańcówki (Timeout). W&nbsp;przypadku awarii, sterownik powinien generować konkretny komunikat błędów na&nbsp;panelu HMI (np. „Przekroczony czas wysuwu siłownika CY1”), zamiast zatrzymywać linię bez podania przyczyny.",
    cc_h2_faq: "Często Zadawane Pytania (FAQ)",
    cc_faq_q1: "Jaki język programowania wybrać: LAD (Drabinka) czy SCL/ST (Tekst strukturalny)?",
    cc_faq_a1: "Zgodnie z dobrymi praktykami, do prostej logiki zezwoleń, bezpieczeństwa i sekwencji idealnie nadaje się język drabinkowy (LAD), ponieważ jest czytelny dla automatyków utrzymania ruchu. Natomiast skomplikowane przeliczenia matematyczne, operacje na ciągach znaków, pętle oraz maszyny stanów warto pisać w języku SCL/ST.",
    cc_faq_q2: "Dlaczego nie należy stosować hardkadowanych adresów i zmiennych M (Merkerów)?",
    cc_faq_a2: "Używanie pamięci Merkerów (M) oraz sztywnych adresów sprzyja przypadkowemu nadpisaniu pamięci w innych częściach programu. Zamiast tego nowoczesne środowiska (TIA Portal, Studio 5000) bazują na zmiennych symbolicznych oraz uporządkowanych blokach danych (Data Blocks DB).",
    cc_faq_q3: "Czy NEXAUT audituje i standaryzuje istniejący kod PLC?",
    cc_faq_a3: "Tak. Zespół NEXAUT zajmuje się refaktoryzacją, tworzeniem dedykowanych bibliotek standardów firmowych (PLC/HMI) oraz audytowaniem kodu pod kątem wydajności, bezpieczeństwa i łatwości serwisowania.",
    cc_h2_5: "Podsumowanie – Postaw na najwyższą jakość kodu z NEXAUT",
    cc_p5_1: "Inwestycja w czysty, przejrzysty i dobrze udokumentowany kod PLC zwraca się przy pierwszym przeglądzie lub awarii na obiekcie. Profesjonalnie napisany program skraca czas uruchomienia i minimalizuje ryzyko nieplanowanych przestojów. Chcesz wdrożyć najwyższe standardy programowania w swojej firmie? Skontaktuj się z ekspertami NEXAUT."
  },

  en: {
    cc_meta_desc: "Master Clean Code principles in PLC programming. Tag standardization, modular architecture, PackML state machines, and IEC 61131-3 error handling.",
    cc_page_title: "PLC Programming Best Practices – Clean Code – NEXAUT",
    cc_h1: "PLC Programming Best Practices – How to Write Clean and Safe Code?",
    cc_intro: "In industrial automation, an unwritten rule applies: PLC code is written once, but read and serviced hundreds of times. Clean Code practices are not an aesthetic luxury, but the foundation of reliability, reduced downtime, and equipment safety. Learn how to craft PLC software following top engineering standards.",
    cc_h2_1: "1. Variable Standardization and Naming Conventions",
    cc_p1_1: "Ensure every variable name instantly conveys its purpose and data type. Avoid ambiguous tags like <code>temp1</code> or <code>M0.0</code>. Modern IEC 61131-3 programming utilizes clear prefixes (Hungarian notation or CamelCase):",
    cc_h2_2: "2. Modular Architecture and the DRY Principle (Don't Repeat Yourself)",
    cc_p2_1: "Writing an entire machine program inside a single monolithic block (e.g., OB1) leads straight to 'Spaghetti Code'. Proper architecture divides the application into reusable Function Blocks (FBs) and Functions (FCs). Each physical component—motor, valve, sensor—should have its own tested library block with clearly defined I/O interfaces.",
    cc_callout_title: "NEXAUT Golden Engineering Rule",
    cc_callout_text: "If you copy-paste the same code snippet more than twice, convert it into a reusable Function Block (FB) immediately. Updating logic in a single library block automatically updates all instantiated devices across the entire line.",
    cc_h2_3: "3. State Machines and the PackML Standard",
    cc_p3_1: "Station sequence execution should rely on explicit State Machines (e.g., using <code>CASE...OF</code> statements in SCL/ST). Instead of getting lost in nested <code>IF-THEN</code> conditions, the application transitions deterministically through defined steps: <i>INIT, IDLE, EXECUTE, STOPPING, ERROR</i>. Adopting PackML simplifies cross-vendor integration.",
    cc_h2_4: "4. Embedded Diagnostics and Safe Error Handling",
    cc_p4_1: "Clean PLC code does not merely execute motion; it informs operators clearly when faults occur. Every actuator requires travel time monitoring (Timeout). Upon failure, the PLC should generate descriptive HMI alarm messages (e.g., 'Cylinder CY1 Extend Timeout') rather than stopping without context.",
    cc_h2_faq: "Frequently Asked Questions (FAQ)",
    cc_faq_q1: "Which language to choose: LAD (Ladder) or SCL/ST (Structured Text)?",
    cc_faq_a1: "Best practice dictates using Ladder Logic (LAD) for interlocking, safety, and sequence control due to its readability for plant technicians. Complex math, string manipulations, loops, and state machines are best written in SCL/ST.",
    cc_faq_q2: "Why avoid hardcoded memory addresses and M flags (Merkers)?",
    cc_faq_a2: "Relying on direct M flags and absolute memory addressing risks accidental memory overwrites. Modern platforms (TIA Portal, Studio 5000) rely on symbolic variables and structured Data Blocks (DBs).",
    cc_faq_q3: "Does NEXAUT audit and standardize existing PLC codebases?",
    cc_faq_a3: "Yes. NEXAUT provides code refactoring, custom PLC/HMI corporate standard libraries, and comprehensive code audits focused on performance, safety, and maintainability.",
    cc_h2_5: "Summary – Elevate Your Code Quality with NEXAUT",
    cc_p5_1: "Investing in clean, structured, and well-documented PLC code pays off during the very first maintenance event or site commissioning. Professional code speeds up deployment and minimizes unplanned outages. Contact NEXAUT experts to implement gold-standard programming in your organization."
  },

  de: {
    cc_meta_desc: "Erfahren Sie die Prinzipien für Clean Code in der SPS-Programmierung. Tag-Standardisierung, modulare Architektur, PackML und Fehlerdiagnose nach IEC 61131-3.",
    cc_page_title: "SPS-Programmierung Best Practices – Clean Code – NEXAUT",
    cc_h1: "Bewährte Methoden der SPS-Programmierung – wie schreibt man sauberen Code?",
    cc_intro: "In der Industrieautomatisierung gilt: SPS-Code wird einmal geschrieben, aber hunderte Male gelesen und gewartet. Clean Code ist kein Luxus, sondern das Fundament für Zuverlässigkeit, kurze Stillstandszeiten und Maschinensicherheit. Erfahren Sie, wie Sie SPS-Software nach den besten Standards erstellen.",
    cc_h2_1: "1. Variablenstandardisierung und Benennungsregeln",
    cc_p1_1: "Jeder Variablenname sollte sofort Zweck und Datentyp offenbaren. Vermeiden Sie unklare Namen wie <code>temp1</code> oder <code>M0.0</code>. Nach IEC 61131-3 werden eindeutige Präfixe verwendet:",
    cc_h2_2: "2. Modulare Architektur und das DRY-Prinzip (Don't Repeat Yourself)",
    cc_p2_1: "Das Schreiben der gesamten Logik in einem einzigen Baustein (z. B. OB1) führt direkt zu 'Spaghetti-Code'. Eine saubere Architektur unterteilt die Anwendung in wiederverwendbare Funktionsbausteine (FB) und Funktionen (FC). Jedes Aggregat sollte über einen eigenen Bibliotheksbaustein verfügen.",
    cc_callout_title: "Goldene NEXAUT Ingenieur-Regel",
    cc_callout_text: "Kopieren Sie denselben Code mehr als zweimal, erstellen Sie sofort einen universellen Funktionsbaustein (FB). Eine Änderung im Bibliotheksbaustein aktualisiert automatisch alle Instanzen in der gesamten Anlage.",
    cc_h2_3: "3. Zustandsmaschinen (State Machines) und PackML-Standard",
    cc_p3_1: "Die Ablaufsteuerung sollte auf einer expliziten Zustandsmaschine basieren (z. B. mittels <code>CASE...OF</code> in SCL/ST). Statt unübersichtlicher <code>IF-THEN</code>-Verschachtelungen durchläuft das Programm definierte Schritte: <i>INIT, IDLE, EXECUTE, STOPPING, ERROR</i>.",
    cc_h2_4: "4. Integrierte Diagnose und sichere Fehlerbehandlung",
    cc_p4_1: "Sauberer SPS-Code führt nicht nur Bewegungen aus, sondern informiert den Bediener präzise über Störungen. Jedes Aktorik-Element benötigt eine Laufzeitüberwachung (Timeout), um Fehler direkt am HMI klar anzuzeigen.",
    cc_h2_faq: "Häufig gestellte Fragen (FAQ)",
    cc_faq_q1: "Welche Sprache wählen: KOP (Kontaktplan) oder SCL/ST (Strukturierter Text)?",
    cc_faq_a1: "Kontaktplan (KOP/LAD) eignet sich hervorragend für Verriegelungen und einfache Sequenzen, da er für das Instandhaltungspersonal leicht lesbar ist. Komplexe Berechnungen, Schleifen und Zustandsmaschinen werden bevorzugt in SCL/ST programmiert.",
    cc_faq_q2: "Warum sollte man harte Adressen und Merker (M) vermeiden?",
    cc_faq_a2: "Harte Merkeradressen bergen das Risiko von Speicherüberschreibungen. Moderne Entwicklungsumgebungen (TIA Portal, Studio 5000) setzen auf symbolische Variablen und strukturierte Datenbausteine (DB).",
    cc_faq_q3: "Auditiert und standardisiert NEXAUT bestehenden SPS-Code?",
    cc_faq_a3: "Ja. Das Team von NEXAUT übernimmt Refactoring, die Erstellung firmenspezifischer Bibliotheksstandards (SPS/HMI) sowie Code-Audits hinsichtlich Performance und Wartbarkeit.",
    cc_h2_5: "Zusammenfassung – Setzen Sie auf höchste Codequalität mit NEXAUT",
    cc_p5_1: "Eine Investition in sauberen und gut dokumentierten SPS-Code zahlt sich bereits bei der ersten Wartung oder Inbetriebnahme aus. Kontaktieren Sie die Experten von NEXAUT für professionelle Softwarestandards."
  }
};