window.POST_TRANSLATIONS = {
  pl: {
    vc_meta_desc: "Testowanie kodu PLC i robotów w środowisku cyfrowego bliźniaka pozwala wyeliminować kolizje i skrócić czas rozruchu linii o 50% przed wdrożeniem na obiekcie.",
    vc_page_title: "Wirtualne uruchomienie (Virtual Commissioning) – jak skrócić czas rozruchu linii o 50%? – NEXAUT",
    vc_h1: "Wirtualne uruchomienie (Virtual Commissioning) – jak skrócić czas rozruchu linii o&nbsp;50%?",
    vc_intro: "Testowanie kodu PLC i&nbsp;robotów w&nbsp;środowisku cyfrowym bliźniaka pozwala wyeliminować błędy logiki oraz kolizje zanim pierwsza fizyczna maszyna trafi na&nbsp;hale produkcyjną. Poznaj technologię, która rewolucjonizuje harmonogramy wdrożeń przemysłowych.",
    vc_h2_1: "Czym jest Virtual Commissioning i Cyfrowy Bliźniak (Digital Twin)?",
    vc_p1_1: "Tradycyjny proces uruchomienia linii zautomatyzowanej wiąże się z&nbsp;dużym ryzykiem: programiści PLC i&nbsp;robotycy wchodzą na&nbsp;obiekt dopiero po&nbsp;zakończeniu montażu mechanicznego i&nbsp;elektrycznego. Każdy błąd w&nbsp;kodzie, błędna sekwencja czy kolizja ramienia robota z&nbsp;wygrodzeniem oznacza kosztowne opóźnienia i&nbsp;ryzyko uszkodzenia sprzętu.",
    vc_p1_2: "<strong>Wirtualne Uruchomienie (Virtual Commissioning – VIBN)</strong> zmienia ten paradygmat. Polega na&nbsp;połączeniu prawdziwego sterownika PLC (lub jego symulatora PLCSIM Advanced) z&nbsp;trójwymiarowym, dynamicznym modelem CAD celi produkcyjnej – tzw. <strong>Cyfrowym Bliźniakiem (Digital Twin)</strong>.",
    vc_h2_2: "Główne korzyści z&nbsp;wdrożenia Wirtualnego Uruchomienia",
    vc_p2_intro: "Inwestycja w&nbsp;przygotowanie wirtualnego modelu celi zwraca się z&nbsp;nawiązką już podczas pierwszego tygodnia prac na&nbsp;obiekcie:",
    vc_li_2_1: "<strong>Skrócenie czasu rozruchu na obiekcie o 50-80%:</strong> Większość błędów w&nbsp;kodzie sterującym i&nbsp;sekwencjach jest wykrywana i&nbsp;poprawiana w&nbsp;biurze inżynierskim.",
    vc_li_2_2: "<strong>Całkowite wyeliminowanie kolizji mechanicznych:</strong> Symulacja ruchu robotów i&nbsp;siłowników w&nbsp;środowisku 3D gwarantuje brak uszkodzeń chwytaków i&nbsp;detali przy pierwszym przejeździe.",
    vc_li_2_3: "<strong>Równoległe prowadzenie prac (Engineering Parallelism):</strong> Programowanie PLC i&nbsp;robotów odbywa się równolegle z&nbsp;zamawianiem komponentów i&nbsp;budową mechaniczną.",
    vc_li_2_4: "<strong>Bezpieczne testowanie stanów awaryjnych (Safety):</strong> Możliwość symulacji wciśnięcia przycisku E-STOP, otwarcia wygrodzenia czy awarii czujnika bez ryzyka dla personelu.",
    vc_callout_title: "Wskazówka Inżyniera NEXAUT",
    vc_callout_text: "Virtual Commissioning to&nbsp;nie tylko symulacja CAD. Kluczem jest wygenerowanie sygnałów w&nbsp;czasie rzeczywistym – sterownik PLC musi „myśleć”, że&nbsp;jest podłączony do&nbsp;fizycznej maszyny (fizyka czujników, zaworów i&nbsp;napędów). Tylko wtedy testy logiki są&nbsp;w&nbsp;100% miarodajne.",
    vc_img2_caption: "Rys 1. Połączenie sterownika PLC z&nbsp;cyfrowym bliźniakiem 3D w&nbsp;środowisku symulacyjnym.",
    vc_h2_3: "Jak przebiega proces Virtual Commissioning krok po kroku?",
    vc_p3_1: "Skuteczne przeprowadzenie wirtualnego uruchomienia składa się z&nbsp;kilku przejrzystych etapów technicznych:",
    vc_box_title: "Etapy realizacji cyfrowego bliźniaka:",
    vc_box_li1: "<strong>1. Przygotowanie modelu 3D:</strong> Uproszczenie geometrii CAD, zdefiniowanie kinematyki (osi, przegubów, liniowych ruchów siłowników).",
    vc_box_li2: "<strong>2. Mapowanie sygnałów I/O:</strong> Przypisanie wirtualnych czujników i&nbsp;zaworów do&nbsp;adresacji w&nbsp;sterowniku PLC.",
    vc_box_li3: "<strong>3. Testy automatyczne i VIBN:</strong> Uruchomienie pełnego cyklu automatycznego w&nbsp;kodzie PLC/robotów oraz weryfikacja czasów cyklu (Cycle Time).",
    vc_h2_4: "Narzędzia wykorzystywane w Wirtualnym Uruchomieniu",
    vc_p4_1: "W&nbsp;zależności od&nbsp;wymagań klienta i&nbsp;zastosowanej platformy sterowania, inżynierowie NEXAUT wykorzystują czołowe środowiska symulacyjne:",
    vc_li_4_1: "<strong>Siemens SIMIT & Process Simulate:</strong> Przemysłowy standard w&nbsp;branży automotive do&nbsp;zaawansowanej symulacji procesów i&nbsp;kodów VASS/FAST.",
    vc_li_4_2: "<strong>Emulate3D / Visual Components:</strong> Elastyczne oprogramowanie do&nbsp;symulacji logistyki, intralogistyki oraz cel zautomatyzowanych.",
    vc_li_4_3: "<strong>S7-PLCSIM Advanced:</strong> Odpowiedzialny za&nbsp;emulację cyklu pracy sterownika S7-1500 w&nbsp;czasie rzeczywistym z&nbsp;obsługą PROFINET.",
    vc_h2_faq: "Często Zadawane Pytania (FAQ)",
    vc_faq_q1: "Czy do Virtual Commissioning potrzebuję pełnego modelu CAD celi?",
    vc_faq_a1: "Tak, podstawą jest model 3D. Może to&nbsp;być jednak model uproszczony – kluczowe jest zachowanie poprawnych wymiarów, kinematyki ruchomych elementów oraz pozycji czujników.",
    vc_faq_q2: "O ile realnie można skrócić czas przebywania inżynierów w zakładzie klienta?",
    vc_faq_a2: "Praktyka pokazuje, że&nbsp;czas uruchomienia na&nbsp;obiekcie skraca się o&nbsp;40% do&nbsp;60%. Wirtualne testy pozwalają wyeliminować około 90% błędów programistycznych jeszcze przed wysyłką szafy sterowniczej.",
    vc_faq_q3: "Czy NEXAUT wykonuje usługi wirtualnego uruchomienia dla zewnętrznych projektów?",
    vc_faq_a3: "Tak. Tworzymy cyfrowe bliźniaki oraz wykonujemy testy VIBN zarówno dla własnych kompleksowych wdrożeń, jak i&nbsp;na zlecenie producentów maszyn (OEM) oraz integratorów automatyki.",
    vc_h2_5: "Podsumowanie – Zabezpiecz termin wdrożenia z NEXAUT",
    vc_p5_1: "Wirtualne Uruchomienie to&nbsp;najlepsza polisę ubezpieczeniowa dla każdego projektu automatyzacji. Pozwala uniknąć opóźnień, kar umownych oraz stresu związanego z&nbsp;goniącymi terminami. Zespół NEXAUT pomoże Ci&nbsp;wdrożyć cyfrowego bliźniaka i&nbsp;zoptymalizować proces uruchomienia."
  },

  en: {
    vc_meta_desc: "Testing PLC and robot code in a digital twin environment allows eliminating collisions and reducing line startup time by 50% before physical commissioning.",
    vc_page_title: "Virtual Commissioning – how to reduce line startup time by 50%? – NEXAUT",
    vc_h1: "Virtual Commissioning – How to Reduce Line Startup Time by 50%?",
    vc_intro: "Testing PLC and robot code within a digital twin environment eliminates logic errors and physical collisions long before hardware arrives on the plant floor. Discover the technology revolutionizing industrial schedules.",
    vc_h2_1: "What is Virtual Commissioning and the Digital Twin?",
    vc_p1_1: "Traditional automated line commissioning carries substantial risks: PLC programmers and roboticists arrive on site only after mechanical and electrical assembly finish. Every logic bug, sequence error, or robot collision results in costly delays and potential hardware damage.",
    vc_p1_2: "<strong>Virtual Commissioning (VIBN)</strong> shifts this workflow entirely. It connects an actual PLC controller (or PLCSIM Advanced instance) with a dynamic 3D CAD model of the cell – the <strong>Digital Twin</strong>.",
    vc_h2_2: "Core Benefits of Implementing Virtual Commissioning",
    vc_p2_intro: "Investing in a virtual cell model pays off rapidly during the first week of physical site integration:",
    vc_li_2_1: "<strong>50-80% Reduction in On-Site Commissioning Time:</strong> Most control logic bugs and sequence issues are caught and fixed in the engineering office.",
    vc_li_2_2: "<strong>Zero Mechanical Collisions:</strong> Simulating robot and cylinder movements in 3D ensures grippers and tooling remain undamaged during initial runs.",
    vc_li_2_3: "<strong>Parallel Engineering Workflows:</strong> PLC and robot programming proceed simultaneously alongside component procurement and mechanical assembly.",
    vc_li_2_4: "<strong>Safe Emergency State Testing:</strong> Testing E-STOP loops, safety gate interlocks, and sensor faults safely without risking site personnel.",
    vc_callout_title: "NEXAUT Engineering Pro-Tip",
    vc_callout_text: "Virtual Commissioning extends beyond basic CAD animation. Real-time signal generation is crucial – the PLC must experience realistic sensor feedback, valve timing, and drive dynamics as if connected to real hardware.",
    vc_img2_caption: "Fig 1. Real-time connection between a PLC controller and a 3D digital twin in a simulation environment.",
    vc_h2_3: "Step-by-Step Virtual Commissioning Process",
    vc_p3_1: "Executing an effective virtual commissioning project involves clear engineering stages:",
    vc_box_title: "Digital Twin Implementation Stages:",
    vc_box_li1: "<strong>1. 3D Model Preparation:</strong> CAD geometry simplification and setting up kinematics (axes, joints, linear cylinder strokes).",
    vc_box_li2: "<strong>2. I/O Signal Mapping:</strong> Binding virtual sensors and actuators to exact PLC memory addresses.",
    vc_box_li3: "<strong>3. Automated Testing & VIBN:</strong> Running full auto-cycles in PLC/robot code to validate interlocks and cycle times.",
    vc_h2_4: "Software Tools Used in Virtual Commissioning",
    vc_p4_1: "Depending on client requirements and control architectures, NEXAUT engineers leverage top-tier simulation suites:",
    vc_li_4_1: "<strong>Siemens SIMIT & Process Simulate:</strong> Industry standard in automotive for advanced process and VASS/FAST code validation.",
    vc_li_4_2: "<strong>Emulate3D / Visual Components:</strong> Flexible suites for intralogistics, material handling, and custom automated cell simulations.",
    vc_li_4_3: "<strong>S7-PLCSIM Advanced:</strong> Provides real-time execution of Siemens S7-1500 controller code with PROFINET support.",
    vc_h2_faq: "Frequently Asked Questions (FAQ)",
    vc_faq_q1: "Do I need a full CAD model of the cell for Virtual Commissioning?",
    vc_faq_a1: "Yes, a 3D model is required. However, a simplified model suffices as long as accurate dimensions, moving kinematics, and sensor positions are retained.",
    vc_faq_q2: "How much site time is realistically saved for engineering teams?",
    vc_faq_a2: "Field data demonstrates 40% to 60% savings in physical on-site time. Virtual testing eliminates nearly 90% of software bugs prior to panel dispatch.",
    vc_faq_q3: "Does NEXAUT offer standalone Virtual Commissioning services?",
    vc_faq_a3: "Yes. We build digital twins and execute VIBN testing for our turnkey projects as well as third-party machine builders (OEMs) and integrators.",
    vc_h2_5: "Summary – Secure Your Commissioning Schedule with NEXAUT",
    vc_p5_1: "Virtual Commissioning is the ultimate insurance policy for industrial automation projects. It eliminates delays, contractual penalties, and deadline pressure. Contact NEXAUT engineers to deploy digital twin simulation on your next project."
  },

  de: {
    vc_meta_desc: "Das Testen von SPS- und Roboter-Code in der digitalen Zwillingsumgebung eliminiert Kollisionen und verkürzt die Anlaufzeit um 50 % vor Ort.",
    vc_page_title: "Virtuelle Inbetriebnahme – wie Sie die Anlaufzeit einer Linie um 50 % verkürzen? – NEXAUT",
    vc_h1: "Virtuelle Inbetriebnahme – Wie Sie die Anlaufzeit einer Linie um 50 % verkürzen?",
    vc_intro: "Das Testen von SPS- und Roboter-Code im digitalen Zwilling eliminiert Logikfehler und Kollisionen, bevor die erste physische Maschine auf den Werksboden gelangt. Entdecken Sie die Technologie, die Industriezeitpläne revolutioniert.",
    vc_h2_1: "Was ist die Virtuelle Inbetriebnahme (VIBN) und der Digitale Zwilling?",
    vc_p1_1: "Klassische Inbetriebnahmen bergen hohe Risiken: Programmierer gelangen erst nach der mechanischen und elektrischen Montage auf die Baustelle. Jeder Logikfehler oder Roboterzusammenstoß führt zu teuren Verzögerungen und Hardware-Schäden.",
    vc_p1_2: "Die <strong>Virtuelle Inbetriebnahme (VIBN)</strong> verändert diesen Ablauf grundlegend. Eine reale SPS-Steuerung (oder PLCSIM Advanced) wird mit einem dynamischen 3D-CAD-Modell der Anlage – dem <strong>Digitalen Zwilling (Digital Twin)</strong> – gekoppelt.",
    vc_h2_2: "Hauptvorteile der Virtuellen Inbetriebnahme",
    vc_p2_intro: "Die Investition in ein virtuelles Modell macht sich bereits in der ersten Woche der Vor-Ort-Inbetriebnahme bezahlt:",
    vc_li_2_1: "<strong>50–80 % Verkürzung der Anlaufzeit vor Ort:</strong> Der Großteil der Logik- und Ablauffehler wird direkt im Entwicklungsbüro behoben.",
    vc_li_2_2: "<strong>Vollständige Vermeidung mechanischer Kollisionen:</strong> 3D-Bewegungssimulationen von Robotern und Zylindern verhindern Schäden an Greifern und Werkzeugen.",
    vc_li_2_3: "<strong>Paralleles Engineering:</strong> SPS- und Roboter-Programmierung erfolgen parallel zur Bauteilbeschaffung und Mechanikmontage.",
    vc_li_2_4: "<strong>Sichere Simulation von Notfallzuständen:</strong> Testen von Not-Halt-Schaltungen, Schutztüren und Sensorausfällen ohne Gefahr für das Personal.",
    vc_callout_title: "NEXAUT Ingenieur-Tipp",
    vc_callout_text: "Virtuelle Inbetriebnahme ist mehr als CAD-Animation. Entscheidend ist die E/A-Echtzeitsimulation – die SPS muss das Verhalten von Sensoren, Ventilen und Antrieben wie an einer realen Maschine erfahren.",
    vc_img2_caption: "Abb. 1. Kopplung einer SPS-Steuerung mit dem 3D-Digitalen-Zwilling in der Simulationsumgebung.",
    vc_h2_3: "Schritt-für-Schritt-Ablauf der Virtuellen Inbetriebnahme",
    vc_p3_1: "Eine erfolgreiche Virtuelle Inbetriebnahme durchläuft klare technische Phasen:",
    vc_box_title: "Umsetzungsphasen des Digitalen Zwillings:",
    vc_box_li1: "<strong>1. 3D-Modellvorbereitung:</strong> Vereinfachung der CAD-Geometrie und Definition der Kinematik (Achsen, Gelenke, Zylinderhübe).",
    vc_box_li2: "<strong>2. E/A-Signalmapping:</strong> Zuordnung virtueller Sensoren und Aktoren zu den Adressen der SPS-Steuerung.",
    vc_box_li3: "<strong>3. Automatische Tests & VIBN:</strong> Durchführung automatischer Zyklen im SPS-/Robotercode und Überprüfung der Taktzeiten.",
    vc_h2_4: "Eingesetzte Software-Werkzeuge in der VIBN",
    vc_p4_1: "Je nach Kundenanforderung und Steuerungssystem nutzen NEXAUT-Ingenieure führende Simulationslösungen:",
    vc_li_4_1: "<strong>Siemens SIMIT & Process Simulate:</strong> Industriestandard in der Automobilindustrie zur Validierung von Prozessen und VASS/FAST-Codes.",
    vc_li_4_2: "<strong>Emulate3D / Visual Components:</strong> Flexible Software für Materialfluss, Intralogistik und automatisierte Zellen.",
    vc_li_4_3: "<strong>S7-PLCSIM Advanced:</strong> Echtzeit-Emulation der S7-1500 SPS-Steuerungen mit PROFINET-Unterstützung.",
    vc_h2_faq: "Häufig gestellte Fragen (FAQ)",
    vc_faq_q1: "Benötige ich ein vollständiges CAD-Modell für die VIBN?",
    vc_faq_a1: "Ja, ein 3D-Modell ist erforderlich. Es reicht jedoch ein vereinfachtes Modell aus, solange Abmessungen, Kinematiken und Sensorpositionen exakt stimmen.",
    vc_faq_q2: "Wie viel Vor-Ort-Zeit lässt sich realistisch einsparen?",
    vc_faq_a2: "Erfahrungen zeigen eine Reduzierung der Vor-Ort-Zeit um 40 % bis 60 %. Etwa 90 % aller Softwarefehler werden vor dem Schaltschrankversand eliminiert.",
    vc_faq_q3: "Bietet NEXAUT Virtuelle Inbetriebnahme als Dienstleistung an?",
    vc_faq_a3: "Ja. Wir erstellen Digitale Zwillinge und führen VIBN-Tests sowohl für eigene schlüsselfertige Projekte als auch im Auftrag von Maschinenbauern (OEMs) durch.",
    vc_h2_5: "Zusammenfassung – Sichern Sie Ihren Inbetriebnahmetermin mit NEXAUT",
    vc_p5_1: "Die Virtuelle Inbetriebnahme ist die beste Versicherung für jedes Automatisierungsprojekt. Sie verhindert Terminstrallowed, Vertragsstrafen und Anlaufstress. Lassen Sie sich von NEXAUT bei der Umsetzung Ihres Digitalen Zwillings unterstützen."
  }
};