window.POST_TRANSLATIONS = {
  pl: {
    auto_meta_desc: "Automatyzacja i&nbsp;robotyzacja automotive w&nbsp;Gliwicach, Tychach, Bielsku-Białej, Katowicach i&nbsp;Krakowie. Poznaj standardy KUKA, FANUC, ABB oraz&nbsp;integrację PLC z&nbsp;NEXAUT.",
    auto_page_title: "Automatyzacja Automotive: Gliwice, Tychy, Bielsko, Katowice, Kraków – NEXAUT",
    auto_h1: "Automatyzacja w&nbsp;bastionach automotive: Gliwice, Tychy, Bielsko-Biała, Katowice i&nbsp;Kraków",
    auto_intro: "Południowa Polska to&nbsp;bezapelacyjne serce przemysłu motoryzacyjnego w&nbsp;Europie Środkowo-Wschodniej. Pas obejmujący Śląsk i&nbsp;Małopolskę gromadzi największe fabryki OEM oraz&nbsp;dostawców Tier&nbsp;1 i&nbsp;Tier&nbsp;2. To&nbsp;tutaj narzucane są&nbsp;najbardziej wyśrubowane rygory produkcyjne oraz&nbsp;standardy automatyki przemysłowej.",
    auto_h2_1: "1. Mapa robotyzacji Śląska i&nbsp;Małopolski",
    auto_p1_1: "Ekosystem motoryzacyjny w&nbsp;regionie charakteryzuje się niezwykłą gęstością powiązań kooperacyjnych. Szybki czas reakcji serwisu oraz&nbsp;znajomość specyficznych standardów koncernowych są&nbsp;warunkiem koniecznym do&nbsp;utrzymania ciągłości pracy linii.",
    
    // Huby
    auto_hub1_title: "Giganci OEM &amp; Linie Dostawcze",
    auto_hub1_desc: "Centra produkcji pojazdów dostawczych i&nbsp;osobowych. Charakteryzują się potężnymi spawalniami, zautomatyzowanymi lakierniami oraz&nbsp;tłoczniami pracującymi w&nbsp;reżimie taktowym.",
    auto_hub2_title: "Powertrain &amp; Komponenty Precyzyjne",
    auto_hub2_desc: "Historyczny i&nbsp;współczesny węzeł produkcji napędów, zespołów napędowych, układów kierowniczych oraz&nbsp;zaawansowanych komponentów metalowo-tworzywowych.",
    auto_hub3_title: "Strefy KSSE &amp; Dostawcy Tier 1/2",
    auto_hub3_desc: "Kilkadziesiąt nowoczesnych zakładów produkujących wiązki elektryczne, oświetlenie, układy hamulcowe, elementy wyposażenia wnętrz i&nbsp;systemy poduszek powietrznych.",
    auto_hub4_title: "R&amp;D, Elektronika &amp; Robotyka",
    auto_hub4_desc: "Połączenie zaplecza inżynieryjnego z&nbsp;zakładami elektroniki samochodowej (ECU, sensoryka, wiązki wysokonapięciowe dla pojazdów EV/HEV).",

    auto_h2_2: "2. Standardy automatyki i&nbsp;robotyki w&nbsp;branży Automotive",
    auto_p2_1: "W&nbsp;branży samochodowej nie&nbsp;ma miejsca na&nbsp;dowolność. Każdy projekt musi być realizowany zgodnie z&nbsp;rygorystyczną specyfikacją techniczną zamawiającego. Kluczowe obszary technologiczne stanowią:",
    auto_standards_desc: "Programowanie robotów oraz&nbsp;sterowników PLC w&nbsp;zakładach automotive wymaga bezwzględnej znajomości standardów koncepcyjnych (np.&nbsp;VASS stosowanego w&nbsp;grupie VW czy standardów Stellantis/BMW). Obejmuje to&nbsp;zunifikowane struktury kodów, standardy diagnostyczne i&nbsp;protokoły bezpieczeństwa PROFIsafe.",

    auto_callout_title: "NEXAUT – Twój Partner Technologiczny w&nbsp;Pasie Śląsko-Małopolskim",
    auto_callout_text: "Dzięki dogodnej lokalizacji i&nbsp;doświadczeniu w&nbsp;projektach motoryzacyjnych, inżynierowie NEXAUT zapewniają błyskawiczne wsparcie programistyczne i&nbsp;wdrożeniowe dla zakładów w&nbsp;Gliwicach, Tychach, Bielsku-Białej, Katowicach i&nbsp;Krakowie. Programujemy roboty KUKA, FANUC, ABB oraz&nbsp;sterowniki Siemens zgodnie ze&nbsp;standardami OEM.",
    auto_h2_faq: "Często Zadawane Pytania (FAQ)",
    auto_faq_q1: "Czym różni się programowanie robotów w&nbsp;automotive od&nbsp;standardowych aplikacji przemysłowych?",
    auto_faq_a1: "Aplikacje automotive wymagają 100% zgodności z&nbsp;wymuszonym standardem koncernowym (np.&nbsp;VASS, Integra). Każda zmienna, struktura programu, interfejs HMI i&nbsp;sekwencja E-Stop muszą dokładnie odpowiadać oficjalnej bibliotece OEM.",
    auto_faq_q2: "Czy NEXAUT realizuje modyfikacje programistyczne podczas krótkich przestojów (np.&nbsp;wakacyjnych/świątecznych)?",
    auto_faq_a2: "Tak. Doskonale rozumiemy specyfikę branży motoryzacyjnej, w&nbsp;której kluczowe modernizacje linii i&nbsp;wdrożenia nowych modeli odbywają się podczas zaplanowanych okien serwisowych (Summer/Winter Shut-down).",
    auto_faq_q3: "Jakie marki robotów są&nbsp;najbardziej popularne w&nbsp;południowej Polsce?",
    auto_faq_a3: "Zdecydowanie dominują KUKA, FANUC oraz&nbsp;ABB, ze&nbsp;wzrastającym udziałem robotów współpracujących (np.&nbsp;Universal Robots, Yaskawa) w&nbsp;aplikacjach montażowych Tier&nbsp;1/2.",
    auto_h2_5: "Podsumowanie – Inżynieria na&nbsp;najwyższym poziomie",
    auto_p5_1: "Nowoczesny przemysł motoryzacyjny wyznacza kierunek dla całego sektora produkcyjnego. Potrzebujesz sprawdzonego wsparcia przy integracji robotów lub sterowników w&nbsp;pasie Gliwice-Tychy-Bielsko-Katowice-Kraków? Skontaktuj się z&nbsp;zespołem NEXAUT!"
  },

  en: {
    auto_meta_desc: "Automotive automation in Gliwice, Tychy, Bielsko-Biała, Katowice, and Kraków. KUKA, FANUC, ABB standards and PLC integration with NEXAUT.",
    auto_page_title: "Automotive Automation: Gliwice, Tychy, Bielsko, Katowice, Kraków – NEXAUT",
    auto_h1: "Automation in automotive strongholds: Gliwice, Tychy, Bielsko-Biała, Katowice, and Kraków",
    auto_intro: "Southern Poland is the undisputed heart of the automotive industry in CEE. The belt covering Silesia and Lesser Poland gathers major OEMs and Tier 1/2 suppliers setting strict automation standards.",
    auto_h2_1: "1. Robotics Map of Silesia and Lesser Poland",
    auto_p1_1: "The regional automotive ecosystem features dense supply chain ties. Fast service response times and deep standard compliance are vital.",
    auto_hub1_title: "OEM Giants &amp; Delivery Vans",
    auto_hub1_desc: "Vehicle assembly hubs featuring massive body shops, automated paint shops, and synchronized stamping facilities.",
    auto_hub2_title: "Powertrain &amp; Precision Components",
    auto_hub2_desc: "Engine and drivetrain production centers manufacturing steering gearboxes, powertrains, and precision metal-plastic parts.",
    auto_hub3_title: "KSSE Zones &amp; Tier 1/2 Suppliers",
    auto_hub3_desc: "Dozens of plants producing wiring harnesses, automotive lighting, braking systems, and interior equipment.",
    auto_hub4_title: "R&amp;D, Electronics &amp; Robotics",
    auto_hub4_desc: "High-tech automotive electronics (ECUs, sensors, high-voltage harnesses for EVs) paired with advanced R&D hubs.",
    auto_h2_2: "2. Robotics &amp; Automation Standards in Automotive",
    auto_p2_1: "In automotive, strict adherence to OEM standards is mandatory across all technical domains:",
    auto_standards_desc: "Programming robots and PLCs requires strict compliance with automotive standards (e.g. VASS, Integra). This includes unified code structures, diagnostic standards, and PROFIsafe protocols.",
    auto_callout_title: "NEXAUT – Your Tech Partner in Silesia &amp; Lesser Poland",
    auto_callout_text: "Located in the heart of the industrial cluster, NEXAUT engineers deliver fast PLC and robotics integration (KUKA, FANUC, ABB, Siemens) compliant with automotive specifications.",
    auto_h2_faq: "Frequently Asked Questions (FAQ)",
    auto_faq_q1: "How does automotive robot programming differ from standard industrial applications?",
    auto_faq_a1: "Automotive demands 100% compliance with strict OEM standards (e.g. VASS, Integra). Every variable and logic block must conform precisely.",
    auto_faq_q2: "Does NEXAUT perform commissioning during holiday shut-downs?",
    auto_faq_a2: "Yes. We regularly execute major PLC/robotics retrofits during scheduled plant shut-downs (Summer/Winter Shut-down).",
    auto_faq_q3: "Which robot brands dominate Southern Poland?",
    auto_faq_a3: "KUKA, FANUC, and ABB are the primary brands, alongside an increasing cobot footprint in Tier 1/2 assembly stations.",
    auto_h2_5: "Summary – World-Class Industrial Engineering",
    auto_p5_1: "The automotive industry drives automation trends worldwide. Need reliable integration support in Gliwice, Tychy, Bielsko, Katowice, or Kraków? Contact NEXAUT today!"
  },

  de: {
    auto_meta_desc: "Automatisierung der Automobilindustrie in Gliwice, Tychy, Bielsko-Biała, Katowice und Krakau. KUKA-, FANUC-, ABB-Standards und SPS-Integration.",
    auto_page_title: "Automatisierung Automotive: Gliwice, Tychy, Bielsko, Katowice, Krakau – NEXAUT",
    auto_h1: "Automatisierung in Automobil-Hochburgen: Gliwice, Tychy, Bielsko-Biała, Kattowitz und Krakau",
    auto_intro: "Südpolen ist das Herzstück der Automobilindustrie in Mitteleuropa. Das Industriegebiet in Schlesien und Kleinpolen vereint OEM-Werke und Tier 1/2 Zulieferer.",
    auto_h2_1: "1. Robotik-Karte von Schlesien und Kleinpolen",
    auto_p1_1: "Das regionale Automobilnetzwerk zeichnet sich durch enge Lieferketten aus. Kurze Service-Reaktionszeiten und Standardtreue sind entscheidend.",
    auto_hub1_title: "OEM-Giganten &amp; Fahrzeugbau",
    auto_hub1_desc: "Produktionszentren für Nutzfahrzeuge und PKW mit hochentwickelten Karosseriebaulinien und Lackierereien.",
    auto_hub2_title: "Powertrain &amp; Präzisionsteile",
    auto_hub2_desc: "Traditioneller Standort für Motoren- und Getriebebau sowie Lenksysteme und Präzisionskomponenten.",
    auto_hub3_title: "KSSE-Sonderwirtschaftszonen &amp; Tier 1/2",
    auto_hub3_desc: "Zahlreiche Zulieferbetriebe für Kabelbäume, Beleuchtungssysteme, Bremsen und Innenraumkomponenten.",
    auto_hub4_title: "F&amp;E, Elektronik &amp; Robotik",
    auto_hub4_desc: "Verbindung von Entwicklungszentren mit Fabriken für Fahrzeugelektronik und EV-Hochvoltkomponenten.",
    auto_h2_2: "2. Standards der Automatisierungstechnik in Automotive",
    auto_p2_1: "In der Automobilindustrie sind herstellerspezifische Programmierstandards zwingend vorgeschrieben:",
    auto_standards_desc: "Die Programmierung von Robotern und SPS erfordert genaue Kenntnisse der Konzernstandards (z. B. VASS, Integra). Dies umfasst einheitliche Bausteinstrukturen und PROFIsafe-Sicherheitskonzepte.",
    auto_callout_title: "NEXAUT – Ihr Technologiepartner in Schlesien &amp; Kleinpolen",
    auto_callout_text: "Durch die strategische Lage bieten NEXAUT-Ingenieure schnelle Unterstützung für Roboter (KUKA, FANUC, ABB) und Siemens-SPSen nach OEM-Standards.",
    auto_h2_faq: "Häufig gestellte Fragen (FAQ)",
    auto_faq_q1: "Wie unterscheidet sich die Programmierung in Automotive?",
    auto_faq_a1: "Sie erfordert eine 100-prozentige Einhaltung von Vorgaben wie VASS oder Integra.",
    auto_faq_q2: "Führt NEXAUT Arbeiten während der Werksferien durch?",
    auto_faq_a2: "Ja, wir nutzen geplante Produktionsstillstände (Summer/Winter Shut-down) für komplexe Umbauten.",
    auto_faq_q3: "Welche Robotermarken dominieren in Südpolen?",
    auto_faq_a3: "KUKA, FANUC und ABB sind führend, ergänzt durch kollaborative Roboter bei Zulieferern.",
    auto_h2_5: "Zusammenfassung – Engineering auf höchstem Niveau",
    auto_p5_1: "Benötigen Sie Integrationsunterstützung in den Regionen Gliwice, Tychy, Bielsko, Kattowitz oder Krakau? Kontaktieren Sie NEXAUT!"
  }
};