window.POST_TRANSLATIONS = {
  pl: {
    hazards_meta_desc: "Najczęstsze zagrożenia w&nbsp;fabrykach i&nbsp;na liniach produkcyjnych. Poznaj analizę ryzyka BHP, normy bezpieczeństwa maszyn i&nbsp;metody redukcji wypadków.",
    hazards_page_title: "Najczęstsze zagrożenia w&nbsp;fabrykach i&nbsp;na liniach produkcyjnych – Analiza BHP – NEXAUT",
    hazards_h1: "Najczęstsze zagrożenia w&nbsp;fabrykach i&nbsp;na liniach produkcyjnych – analiza ryzyka BHP",
    hazards_intro: "Współczesna hala produkcyjna to&nbsp;środowisko pełne szybko poruszających się elementów mechanicznych, robotów przemysłowych oraz układów wysokiego napięcia. Prawidłowa ocena ryzyka maszynowego oraz bezkompromisowe systemy bezpieczeństwa stanowią fundament każdej nowoczesnej fabryki.",
    hazards_h2_1: "1. Klasyfikacja zagrożeń w&nbsp;nowoczesnym zakładzie produkcyjnym",
    hazards_p1_1: "Wypadki w&nbsp;przemyśle rzadko są dziełem pojedynczego zbiegu okoliczności. Zazwyczaj wynikają z&nbsp;nałożenia się braku odpowiednich osłon technicznych, zmęczenia operatora oraz usterek osprzętu sterującego.",
    
    // Kategorie zagrożeń
    hazards_cat1_title: "Zagrożenia Mechaniczne",
    hazards_cat1_desc: "Pochwycenia przez obracające się wały, zgniecenia w&nbsp;prasach, uderzenia ramion robotów oraz skaleczenia o&nbsp;ostre krawędzie detali.",
    hazards_cat2_title: "Zagrożenia Elektryczne",
    hazards_cat2_desc: "Porażenia prądem w&nbsp;szafach sterowniczych, łuk elektryczny przy przełączaniu obwodów wysokiego prądu oraz uszkodzenia przewodów zasilających.",
    hazards_cat3_title: "Błąd Ludzki &amp; Organizacja",
    hazards_cat3_desc: "Omijanie blokad bezpieczeństwa, brak środków ochrony indywidualnej (ŚOI) oraz brak przeszkolenia personelu w&nbsp;zakresie procedur LOTO (Lockout/Tagout).",

    hazards_h2_2: "2. Systemy techniczne eliminujące ryzyko wypadku",
    hazards_p2_1: "Zgodnie z&nbsp;Dyrektywą Maszynową, środki ochrony fizycznej i&nbsp;automatycznej mają zawsze pierwszeństwo przed instrukcjami stanowiskowymi czy ostrzeżeniami na&nbsp;tablicach. Do&nbsp;najskuteczniejszych rozwiązań należą:",
    hazards_li_1: "<strong class=\"text-white\">Wygrodzenia stacjonarne i&nbsp;zamki elektromagnetyczne:</strong> Uniemożliwiają otwarcie osłony, dopóki niebezpieczny ruch maszyny nie zostanie całkowicie wyhamowany.",
    hazards_li_2: "<strong class=\"text-white\">Aparatura optoelektroniczna:</strong> Kurtyny świetlne i&nbsp;skanery laserowe wyznaczające niewidzialną barierę – jej naruszenie zatrzymuje linię w&nbsp;ułamku sekundy.",
    hazards_li_3: "<strong class=\"text-white\">Sterowniki Bezpieczeństwa (Safety PLC):</strong> Redundantne układy (np.&nbsp;Siemens F-PLC), które stale monitorują stan grzybków bezpieczeństwa (E-Stop) i&nbsp;przekaźników.",

    hazards_callout_title: "Modernizacja i&nbsp;Audyty Bezpieczeństwa Maszyn z&nbsp;NEXAUT",
    hazards_callout_text: "Masz wątpliwości, czy Twój park maszynowy spełnia wymogi norm ISO 13849-1 oraz IEC 62061? Inżynierowie NEXAUT przeprowadzają kompleksowe audyty bezpieczeństwa, projektują obwody Safety i&nbsp;wdrażają certyfikowane modyfikacje na&nbsp;działających liniach produkcyjnych.",
    hazards_h2_faq: "Często Zadawane Pytania (FAQ)",
    hazards_faq_q1: "Co to&nbsp;jest wskaźnik PL (Performance Level) w&nbsp;automatyce?",
    hazards_faq_a1: "Wskaźnik PL (od PL&nbsp;a do&nbsp;PL&nbsp;e) określa zdolność elementów systemu sterowania do&nbsp;realizowania funkcji bezpieczeństwa. Im wyższe potencjalne ryzyko urazu, tym wyższy poziom PL jest wymagany.",
    hazards_faq_q2: "Czym różni się standardowy sterownik PLC od&nbsp;Safety PLC?",
    hazards_faq_a2: "Sterownik Safety PLC posiada zwielokrotnione (redundantne) rdzenie procesora oraz samodiagnostykę, co&nbsp;gwarantuje, że jakakolwiek awaria wewnętrzna nie doprowadzi do&nbsp;niekontrolowanego uruchomienia maszyny.",
    hazards_faq_q3: "Czy sam przycisk E-Stop (grzybek) wystarczy do&nbsp;zabezpieczenia stanowiska?",
    hazards_faq_a3: "Nie. E-Stop jest środkiem ochrony uzupełniającej. Podstawę stanowią osłony, kurtyny optyczne oraz automatyczne blokady uniemożliwiające fizyczny kontakt operatora z&nbsp;zagrożeniem.",
    hazards_h2_5: "Podsumowanie – Bezpieczeństwo to&nbsp;inwestycja, nie koszt",
    hazards_p5_1: "Zapewnienie najwyższych standardów BHP chroni nie tylko zdrowie i&nbsp;życie pracowników, ale zapobiega również niezwykle kosztownym przestojom i&nbsp;ewentualnym konsekwencjom prawnym. Skontaktuj się z&nbsp;NEXAUT, aby zaudytować i&nbsp;unowocześnić systemy bezpieczeństwa w&nbsp;Twojej fabryce!"
  },

  en: {
    hazards_meta_desc: "Most common hazards in factories and production lines. Learn about OHS risk analysis, machine safety standards, and accident prevention.",
    hazards_page_title: "Most common hazards in factories – OHS Risk Analysis – NEXAUT",
    hazards_h1: "Most common hazards in factories and production lines – OHS risk analysis",
    hazards_intro: "Modern manufacturing plants feature fast-moving machinery, industrial robots, and high-voltage circuits. Proper risk assessment and robust safety systems form the backbone of modern factories.",
    hazards_h2_1: "1. Hazard Classification in Industrial Facilities",
    hazards_p1_1: "Industrial accidents rarely happen by chance. They usually stem from missing physical guards, operator fatigue, and control hardware failures.",
    hazards_cat1_title: "Mechanical Hazards",
    hazards_cat1_desc: "Entrapment by rotating shafts, crushing in presses, impact from robot arms, and cuts from sharp sheet metal.",
    hazards_cat2_title: "Electrical Hazards",
    hazards_cat2_desc: "Electric shocks in control cabinets, arc flashes during switching, and damaged power cables.",
    hazards_cat3_title: "Human Error & Process",
    hazards_cat3_desc: "Bypassing safety interlocks, missing PPE, and unexecuted LOTO (Lockout/Tagout) procedures.",
    hazards_h2_2: "2. Technical Safety Systems Preventing Accidents",
    hazards_p2_1: "According to the Machinery Directive, engineering controls always take precedence over warning signs or manuals. Key solutions include:",
    hazards_li_1: "<strong class=\"text-white\">Physical Fencing &amp; Interlocks:</strong> Prevents opening guards until hazardous motion comes to a complete standstill.",
    hazards_li_2: "<strong class=\"text-white\">Optoelectronic Protection:</strong> Light curtains and laser scanners creating optical barriers that trigger immediate emergency stops.",
    hazards_li_3: "<strong class=\"text-white\">Safety PLCs:</strong> Redundant controllers (e.g., Siemens F-PLC) continuously monitoring E-Stops and safety relays.",
    hazards_callout_title: "Machine Safety Audits &amp; Upgrades by NEXAUT",
    hazards_callout_text: "Need to verify compliance with ISO 13849-1 or IEC 62061? NEXAUT engineers perform safety audits, design safety circuits, and implement certified retrofits.",
    hazards_h2_faq: "Frequently Asked Questions (FAQ)",
    hazards_faq_q1: "What is Performance Level (PL) in automation?",
    hazards_faq_a1: "Performance Level (PL a to PL e) defines the reliability of safety-related control functions based on potential risk severity.",
    hazards_faq_q2: "What is the difference between standard PLC and Safety PLC?",
    hazards_faq_a2: "Safety PLCs utilize redundant processor cores and self-diagnostics to ensure internal faults never lead to dangerous failures.",
    hazards_faq_q3: "Is an E-Stop button enough to secure a workstation?",
    hazards_faq_a3: "No. E-Stops are complementary protections. Physical guards and light curtains are primary barriers.",
    hazards_h2_5: "Summary – Safety is an Investment, Not an Expense",
    hazards_p5_1: "Ensuring top safety standards protects workers while preventing costly downtime. Contact NEXAUT to audit and upgrade your safety systems!"
  },

  de: {
    hazards_meta_desc: "Die häufigsten Gefahren in Fabriken und an Produktionslinien. Arbeitsschutz-Risikoanalyse und Maschinensicherheit.",
    hazards_page_title: "Häufigste Gefahren in Fabriken – Arbeitsschutz-Risikoanalyse – NEXAUT",
    hazards_h1: "Die häufigsten Gefahren in Fabriken und an Produktionslinien – Arbeitsschutz-Risikoanalyse",
    hazards_intro: "Moderne Produktionshallen bergen mechanische, elektrische und robotergestützte Risiken. Eine präzise Risikobeurteilung ist unumgänglich.",
    hazards_h2_1: "1. Klassifizierung von Gefahren im Betrieb",
    hazards_p1_1: "Unfälle entstehen meist durch fehlende Schutzeinrichtungen, Bedienerfehler oder defekte Steuerungstechnik.",
    hazards_cat1_title: "Mechanische Gefahren",
    hazards_cat1_desc: "Erfassen an rotierenden Teilen, Quetschen an Pressen, Stöße durch Roboterarme und Schnittverletzungen.",
    hazards_cat2_title: "Elektrische Gefahren",
    hazards_cat2_desc: "Stromschläge in Schaltschränken, Lichtbögen und beschädigte Anschlussleitungen.",
    hazards_cat3_title: "Menschlicher Faktor",
    hazards_cat3_desc: "Umgehen von Sicherheitseinrichtungen und fehlende LOTO-Prozeduren.",
    hazards_h2_2: "2. Technische Schutzmaßnahmen zur Unfallverhütung",
    hazards_p2_1: "Gemäß Maschinenrichtlinie haben technische Schutzmaßnahmen Vorrang vor organisatorischen Regeln:",
    hazards_li_1: "<strong class=\"text-white\">Trennende Schutzeinrichtungen:</strong> Zwingen zum Stillstand, bevor Gefahrenbereiche betreten werden können.",
    hazards_li_2: "<strong class=\"text-white\">Optoelektronische Schutzsteuerungen:</strong> Lichtgitter und Laserscanner zur fehlerfreien Personenerkennung.",
    hazards_li_3: "<strong class=\"text-white\">Sicherheits-SPS (Safety PLC):</strong> Redundante Steuerungen zur lückenlosen Überwachung von Not-Halt-Kreisen.",
    hazards_callout_title: "Sicherheitsaudits &amp; Nachrüstungen von NEXAUT",
    hazards_callout_text: "Wir prüfen Ihre Anlagen gemäß ISO 13849-1 und rüsten zertifizierte Sicherheitstechnik im laufenden Betrieb nach.",
    hazards_h2_faq: "Häufig gestellte Fragen (FAQ)",
    hazards_faq_q1: "Was bedeutet Performance Level (PL)?",
    hazards_faq_a1: "Der Performance Level (PL a bis PL e) beschreibt die Zuverlässigkeit einer Sicherheitsfunktion.",
    hazards_faq_q2: "Wie unterscheidet sich eine Safety-SPS?",
    hazards_faq_a2: "Sicherheits-SPSen verfügen über redundant ausgelegte Prozessoren und erweiterte Eigendiagnosen.",
    hazards_faq_q3: "Reicht ein Not-Halt-Taster aus?",
    hazards_faq_a3: "Nein, Not-Halt ist eine ergänzende Schutzmaßnahme. Primär sind zwingend trennende oder optische Schutzeinrichtungen nötig.",
    hazards_h2_5: "Zusammenfassung – Sicherheit schützt Mensch und Ertrag",
    hazards_p5_1: "Hohe Sicherheitsstandards sichern die Gesundheit der Mitarbeiter und verhindern Ausfallzeiten. Kontaktieren Sie NEXAUT!"
  }
};