window.POST_TRANSLATIONS = {
  pl: {
    factories_meta_desc: "Ranking najnowocześniejszych fabryk w&nbsp;Polsce. Poznaj historię automatyzacji i&nbsp;cyfryzacji zakładów – od&nbsp;prostych linii lat 90. po&nbsp;erę Przemysłu 4.0.",
    factories_page_title: "Ranking najnowocześniejszych fabryk w&nbsp;Polsce: Historia i&nbsp;Przemysł 4.0 – NEXAUT",
    factories_h1: "Ranking najnowocześniejszych fabryk w&nbsp;Polsce – jak rozwijała się automatyzacja zakładów?",
    factories_intro: "Od&nbsp;prostej mechanizacji i&nbsp;podstawowych sterowników PLC w&nbsp;latach 90. po&nbsp;w&nbsp;pełni autonomiczne gigafabryki wykorzystujące cyfrowe bliźniaki (Digital Twins) oraz roboty AMR. Droga, jaką przebył polski przemysł w&nbsp;ciągu ostatnich trzech dekad, jest spektakularna.",
    factories_h2_1: "1. Ewolucja Polskiej Automatyki: Od&nbsp;Lat 90. do&nbsp;Ery Przemysłu 4.0",
    
    // Oś Czasu
    factories_t1_title: "Początki Cyfryzacji i&nbsp;Pierwsze PLC",
    factories_t1_desc: "Wymiana przekaźnikowych układów sterowania na&nbsp;pierwsze sterowniki PLC (m.in. Siemens S5). Automatyzacja ograniczała się głównie do&nbsp;prostych operacji i&nbsp;mechanicznego transportu.",
    factories_t2_title: "Napływ Zagranicznych Inwestycji Bezpośrednich (FDI)",
    factories_t2_desc: "Wejście Polski do&nbsp;UE otworzyło drzwi dla gigantów automotive i&nbsp;elektroenergetyki. Pojawiają się pierwsze zrobotyzowane cele spawalnicze oraz magistrale przemysłowe Profibus i&nbsp;Profinet.",
    factories_t3_title: "Standaryzacja i&nbsp;Systemy SCADA",
    factories_t3_desc: "Seryjna instalacja robotów 6-osiowych (KUKA, ABB, Fanuc), masowe wdrażanie systemów wizyjnych oraz integrowanie linii produkcyjnych z&nbsp;systemami nadzoru SCADA i&nbsp;MES.",
    factories_t4_title: "Autonomiczne Gigafabryki &amp; Przemysł 4.0",
    factories_t4_desc: "Pełna integracja wózków AMR/AGV, AI w&nbsp;kontroli jakości, diagnostyka predictive maintenance oraz cyfrowe odzwierciedlenie procesów w&nbsp;czasie rzeczywistym.",

    factories_h2_2: "2. Co Decyduje o&nbsp;Miejscu w&nbsp;Rankingu Najnowocześniejszych Zakładów?",
    factories_p2_1: "Nowoczesności fabryki nie mierzy się już wyłącznie powierzchnią hali czy liczbą zatrudnionych osób. O&nbsp;pozycji lidera decydują precyzyjne wskaźniki efektywności cyfrowej oraz poziom automatyzacji.",

    // Lista Kryteriów
    factories_c1_title: "100% Łączność OT/IT (MES + ERP + SCADA)",
    factories_c1_desc: "Każde zdarzenie na&nbsp;linii jest natychmiast raportowane do&nbsp;systemu zarządzania, eliminując papierowy obieg dokumentów.",
    factories_c2_title: "Autonomiczna Intralogistyka (AMR / AGV)",
    factories_c2_desc: "Materiały i&nbsp;półprodukty dostarczane są na&nbsp;stanowiska bez udziału operatorów wózków widłowych.",
    factories_c3_title: "Standaryzowane Sterowanie PLC i&nbsp;Robotyka",
    factories_c3_desc: "Spójny kod sterowników oraz zoptymalizowane trajektorie robotów gwarantujące najkrótszy czas cyklu (CT).",

    factories_h2_3: "3. Modernizacja Istniejących Linii vs Nowe Inwestycje (Greenfield)",
    factories_p3_1: "Nie każdy zakład musi być budowany od&nbsp;zera, by&nbsp;dołączyć do&nbsp;czołówki. Wiele polskich firm odnosi sukcesy dzięki retrofitowi – czyli modernizacji dojrzałych linii produkcyjnych poprzez dołożenie nowoczesnych sterowników PLC, paneli HMI oraz gniazd zrobotyzowanych.",
    factories_callout_title: "Rola NEXAUT w&nbsp;Transformacji Cyfrowej Zakładów",
    factories_callout_text: "Niezależnie od&nbsp;tego, czy wdrażasz projekt typu greenfield, czy chcesz przeprowadzić retrofit istniejącego parku maszynowego – nasz zespół inżynierów projektuje, programuje i&nbsp;uruchamia niezawodne systemy sterowania PLC i&nbsp;robotyki na&nbsp;terenie całej Polski i&nbsp;zagranicy.",
    factories_h2_faq: "Często Zadawane Pytania (FAQ)",
    factories_faq_q1: "Jakie branże w&nbsp;Polsce posiadają najbardziej zautomatyzowane zakłady?",
    factories_faq_a1: "Zdecydowanymi liderami są branża motoryzacyjna (automotive), produkcja baterii EV, przemysł spożywczy i&nbsp;e-commerce (duże centra intralogistyczne).",
    factories_faq_q2: "Czy retrofit starej linii produkcyjnej opłaca się bardziej niż zakup nowej?",
    factories_faq_a2: "W&nbsp;większości przypadków tak. Wymiana systemu sterowania PLC, serwonapędów i&nbsp;dodanie robotów kosztuje ułamek ceny nowej linii, przywracając pełną wydajność i&nbsp;zgodność z&nbsp;normami bezpieczeństwa.",
    factories_faq_q3: "Jakie sterowniki PLC dominują w&nbsp;nowoczesnych fabrykach w&nbsp;Polsce?",
    factories_faq_a3: "Największą popularnością cieszą się rozwiązania firm Siemens (Simatic S7-1500 / TIA Portal), Allen-Bradley / Rockwell Automation oraz Beckhoff.",
    factories_h2_5: "Podsumowanie – Dołącz do&nbsp;Liderów Przemysłu z&nbsp;NEXAUT",
    factories_p5_1: "Historia pokazała, że&nbsp;zakłady inwestujące w&nbsp;elastyczną automatyzację i&nbsp;robotyzację wygrywają rywalizację rynkową. Jeśli planujesz rozbudowę lub modernizację swojego zakładu, skontaktuj się z&nbsp;NEXAUT – pomożemy Ci wdrożyć rozwiązania na&nbsp;poziomie światowych liderów!"
  },

  en: {
    factories_meta_desc: "Ranking of the most modern factories in Poland. Discover the history of automation from the 90s to Industry 4.0.",
    factories_page_title: "Ranking of the most modern factories in Poland: History and Industry 4.0 – NEXAUT",
    factories_h1: "Ranking of the most modern factories in Poland – how industrial automation evolved",
    factories_intro: "From basic PLC controllers in the 90s to autonomous gigafactories with Digital Twins and AMR robots. The journey of Polish manufacturing over three decades is remarkable.",
    factories_h2_1: "1. Evolution of Polish Automation: From the 90s to Industry 4.0",
    factories_t1_title: "Early Digitalization & First PLCs",
    factories_t1_desc: "Replacing relay systems with early PLCs (e.g. Siemens S5). Focus was limited to basic machine control.",
    factories_t2_title: "Inflow of Foreign Direct Investment (FDI)",
    factories_t2_desc: "EU entry opened doors for automotive giants. Introduction of robotic welding cells and Profibus/Profinet networks.",
    factories_t3_title: "Standardization & SCADA Systems",
    factories_t3_desc: "Serial deployment of 6-axis robots (KUKA, ABB, Fanuc), vision inspection systems, and MES/SCADA integration.",
    factories_t4_title: "Autonomous Gigafactories & Industry 4.0",
    factories_t4_desc: "Full integration of AMR/AGV vehicles, AI quality inspection, predictive maintenance, and real-time digital twins.",
    factories_h2_2: "2. Key Criteria of Modern Smart Plants",
    factories_p2_1: "Plant maturity is no longer measured solely by square footage. Digital efficiency metrics define leadership.",
    factories_c1_title: "100% OT/IT Connectivity (MES + ERP + SCADA)",
    factories_c1_desc: "Every event on the line is instantly logged to central management, eliminating paper records.",
    factories_c2_title: "Autonomous Intralogistics (AMR / AGV)",
    factories_c2_desc: "Materials and parts are delivered to cells without human forklift drivers.",
    factories_c3_title: "Standardized PLC & Robotics Code",
    factories_c3_desc: "Clean PLC architecture and optimized robot trajectories guaranteeing minimum cycle time (CT).",
    factories_h2_3: "3. Retrofit vs Greenfield Investments",
    factories_p3_1: "Not every plant needs to be built from scratch. Line retrofits with modern PLCs, HMIs, and robot cells deliver incredible ROI.",
    factories_callout_title: "NEXAUT's Role in Digital Transformation",
    factories_callout_text: "Whether executing greenfield projects or retrofitting legacy equipment, NEXAUT designs, programs, and commissions PLC and robotics systems nationwide and abroad.",
    factories_h2_faq: "Frequently Asked Questions (FAQ)",
    factories_faq_q1: "Which industries in Poland are most automated?",
    factories_faq_a1: "Automotive, EV battery production, food processing, and large e-commerce logistics hubs lead the charge.",
    factories_faq_q2: "Is retrofitting an old line better than buying new?",
    factories_faq_a2: "In most cases, yes. Upgrading PLCs, servo drives, and adding robots costs a fraction of a new line while restoring reliability.",
    factories_faq_q3: "Which PLC controllers dominate in Polish plants?",
    factories_faq_a3: "Siemens (Simatic S7-1500 / TIA Portal), Allen-Bradley / Rockwell Automation, and Beckhoff dominate the market.",
    factories_h2_5: "Summary – Join Industry Leaders with NEXAUT",
    factories_p5_1: "Plants investing in flexible automation win the market. Contact NEXAUT to upgrade or expand your production lines!"
  },

  de: {
    factories_meta_desc: "Ranking der modernsten Fabriken in Polen. Geschichte der Automatisierung von den 90er Jahren bis zu Industrie 4.0.",
    factories_page_title: "Ranking der modernsten Fabriken in Polen – NEXAUT",
    factories_h1: "Ranking der modernsten Fabriken in Polen – wie sich die Industrieautomatisierung entwickelt hat",
    factories_intro: "Von einfachen SPS-Steuerungen der 90er Jahre bis hin zu autonomen Gigafabriken mit digitalen Zwillingen und AMR-Robotern.",
    factories_h2_1: "1. Evolution der polnischen Automatisierung",
    factories_t1_title: "Anfänge der Digitalisierung & Erste SPS",
    factories_t1_desc: "Ablösung von Relaissteuerungen durch frühe SPS-Systeme (z.B. Siemens S5).",
    factories_t2_title: "Zufluss von Direktinvestitionen",
    factories_t2_desc: "EU-Beitritt brachte Automobilkonzerne nach Polen. Schweißroboterzellen und Profibus/Profinet hielten Einzug.",
    factories_t3_title: "Standardisierung & SCADA",
    factories_t3_desc: "Serienmäßiger Einsatz von 6-Achs-Robotern (KUKA, ABB, Fanuc) und MES/SCADA-Anbindungen.",
    factories_t4_title: "Autonome Gigafabriken & Industrie 4.0",
    factories_t4_desc: "Vollständige FTS/AGV-Einbindung, KI-Qualitätskontrolle und Vorausschauende Wartung (Predictive Maintenance).",
    factories_h2_2: "2. Kriterien einer Smart Factory",
    factories_p2_1: "Digitale Effizienzkennzahlen bestimmen heute die Spitzenpositionen.",
    factories_c1_title: "100% OT/IT-Konnektivität",
    factories_c1_desc: "Lückenlose Datenerfassung vom Feld bis zum MES/ERP-System.",
    factories_c2_title: "Autonome Intralogistik (AMR / AGV)",
    factories_c2_desc: "Materialversorgung der Roboterzellen ohne manuelle Stapler fahrten.",
    factories_c3_title: "Standardisierte SPS- & Robotercodes",
    factories_c3_desc: "Einheitliche Bausteine zur Minimierung der Taktzeit (CT).",
    factories_h2_3: "3. Retrofit vs. Greenfield",
    factories_p3_1: "Modernisierungen bestehender Anlagen (Retrofit) bieten hervorragende Erträge bei geringeren Investitionskosten.",
    factories_callout_title: "NEXAUT als Partner für Ihre Transformation",
    factories_callout_text: "Wir projektieren, programmieren und nehmen SPS- sowie Robotersysteme in Polen und europaweit in Betrieb.",
    factories_h2_faq: "Häufig gestellte Fragen (FAQ)",
    factories_faq_q1: "Welche Branchen führen in Polen?",
    factories_faq_a1: "Automotive, EV-Batteriefertigung, Lebensmittelindustrie und E-Commerce.",
    factories_faq_q2: "Lohnt sich ein Retrofit?",
    factories_faq_a2: "Ja, die Aufrüstung von SPS-Steuerung und Servoantrieben kostet nur einen Bruchteil einer Neuanlage.",
    factories_faq_q3: "Welche SPS-Systeme dominieren?",
    factories_faq_a3: "Siemens TIA Portal (S7-1500), Allen-Bradley und Beckhoff.",
    factories_h2_5: "Zusammenfassung – Technologievorsprung mit NEXAUT",
    factories_p5_1: "Sichern Sie sich Wettbewerbsvorteile durch moderne Automatisierung. Kontaktieren Sie das NEXAUT-Team!"
  }
};