window.POST_TRANSLATIONS = {
  pl: {
    cr_meta_desc: "Cobot czy robot przemysłowy? Porównujemy udźwig, prędkość, wymogi bezpieczeństwa ISO/TS 15066 i koszty wdrożenia obu rozwiązań w automatyzacji produkcji.",
    cr_page_title: "Robot przemysłowy czy cobot? Porównanie i analiza – NEXAUT",
    cr_h1: "Robot przemysłowy czy cobot? Kiedy warto wybrać robota współpracującego?",
    cr_intro: "Automatyzacja procesów produkcyjnych nie&nbsp;jest już przywilejem największych koncernów. Dziś przed wyzwaniem robotyzacji stają firmy każdej wielkości, a&nbsp;podstawowe pytanie brzmi: postawić na&nbsp;klasycznego robota przemysłowego czy elastycznego cobota? Wyjaśniamy kluczowe różnice w&nbsp;dynamice, wygrodzeniach oraz stopie zwrotu z&nbsp;inwestycji.",
    cr_h2_1: "Czym naprawdę różni się cobot od robota przemysłowego?",
    cr_p1_1: "Główna różnica nie tkwi wyłącznie w&nbsp;wyglądzie czy gabarytach, lecz w&nbsp;<strong>filozofii bezpieczeństwa i&nbsp;przeznaczeniu aplikacyjnym</strong>. Tradycyjne roboty przemysłowe (np. FANUC, KUKA, ABB) projektowane są&nbsp;z&nbsp;myślą o&nbsp;maksymalnej wydajności, olbrzymich prędkościach i&nbsp;dużym udźwigu. Z&nbsp;kolei coboty (Collaborative Robots) zostały stworzone do&nbsp;bezpiecznej pracy ramię w&nbsp;ramię z&nbsp;człowiekiem na&nbsp;wspólnej przestrzeni roboczej.",
    cr_h2_2: "Analiza techniczna: Kiedy wybrać poszczególne rozwiązanie?",
    cr_p2_intro: "Wybór odpowiedniego typu manipulatora sprowadza się do&nbsp;przeanalizowania parametrów procesu produkcyjnego:",
    cr_li_2_1: "<strong>Dynamika i takt cyklu:</strong> Jeśli Twój proces wymaga sekundowych cykli i&nbsp;przenoszenia detali z&nbsp;ogromną prędkością, klasyczny robot przemysłowy pozostaje bezkonkurencyjny. Coboty ze&nbsp;względu na&nbsp;normy bezpieczeństwa poruszają się wolniej.",
    cr_li_2_2: "<strong>Udźwig i zasięg:</strong> Roboty tradycyjne z&nbsp;łatwością radzą sobie z&nbsp;ciężarami od&nbsp;kilkunastu do&nbsp;nawet kilkuset kilogramów. Nowoczesne coboty osiągają udźwig rzędu 10–30 kg, co&nbsp;wystarcza do&nbsp;większości zadań paletyzacji i&nbsp;obsługi maszyn, ale wyklucza je&nbsp;z&nbsp;ciężkiego spawalnictwa czy odlewnictwa.",
    cr_li_2_3: "<strong>Bezpieczeństwo i klatki (Wygrodzenia):</strong> Robot przemysłowy bezkompromisowo wymaga zamkniętej strefy ochronnej (wybramowania, kurtyny świetlne, zamki ryglowane). Cobot wyposażony w&nbsp;czujniki siły i&nbsp;momentu może (po ocenie ryzyka wg&nbsp;ISO/TS 15066) pracować bez fizycznych wygrodzeń.",
    cr_li_2_4: "<strong>Elastyczność montażu i przestrzeń:</strong> Cobota można łatwo przenieść między stanowiskami (np. na&nbsp;wózku mobilnym) i&nbsp;przeprogramować w&nbsp;kilkanaście minut. Klasyczna gniazda z&nbsp;robotem przemysłowym są&nbsp;zazwyczaj instalacjami stacjonarnymi na&nbsp;stałe.",
    cr_callout_title: "Pułapka myślowa: „Cobot nie wymaga żadnego zabezpieczenia”",
    cr_callout_text: "Pamiętaj, że&nbsp;bezpieczny jest sam manipulator, a&nbsp;nie cała aplikacja! Jeśli wyposażysz cobota w&nbsp;ostry chwytak lub będzie on&nbsp;przenosił noże czy gorące elementy, całe stanowisko nadal musi posiadać dodatkowe zabezpieczenia lub skanery bezpieczeństwa.",
    cr_img2_caption: "Rys 1. Zastosowanie cobota w&nbsp;procesie paletyzacji na&nbsp;ograniczonej przestrzeni halowej.",
    cr_h2_3: "Tabela Porównawcza: Robot Przemysłowy vs Cobot",
    cr_h2_faq: "Często Zadawane Pytania (FAQ)",
    cr_faq_q1: "Czy cobot jest tańszy w zakupie od robota przemysłowego?",
    cr_faq_a1: "Sam ramieniowy cobot bywa droższy od tradycyjnego robota o podobnym udźwigu, ponieważ posiada wbudowane skomplikowane czujniki siły. Jednak całkowity koszt wdrożenia stanowiska z cobotem bywa niższy z uwagi na brak konieczności budowania wygrodzeń ochronnych i prostszy montaż.",
    cr_faq_q2: "Czy do programowania cobota potrzebny jest wykwalifikowany programista?",
    cr_faq_a2: "Proste zadania (np. Pick & Place) na cobocie może zaprogramować operator po krótkim szkoleniu, korzystając z graficznego interfejsu lub przeciągając ramię ręcznie (hand guiding). Przy złożonych integracjach z linią i PLC nadal zalecane jest wsparcie eksperckie.",
    cr_faq_q3: "Jak NEXAUT pomaga w doborze i integracji robotów?",
    cr_faq_a3: "W NEXAUT przeprowadzamy pełny audyt wykonalności, ocenę ryzyka (norma ISO/TS 15066) oraz symulację czasów cyklu. Pomagamy dobrać idealne rozwiązanie – od doboru marki manipulatora, przez chwytaki, po pełne zaprogramowanie i certyfikację CE.",
    cr_h2_5: "Podsumowanie – Postaw na trafną robotyzację z NEXAUT",
    cr_p5_1: "Nie ma uniwersalnie „lepszego” rozwiązania – zarówno cobot, jak i klasyczny robot przemysłowy mają swoje idealne zastosowania. Zamiast kierować się panującą modą, warto przeanalizować czas cyklu, przestrzeń fabryczną oraz budżet. Skontaktuj się z NEXAUT, a przeanalizujemy Twój proces i zaproponujemy optymalny wariant robotyzacji."
  },

  en: {
    cr_meta_desc: "Cobot or industrial robot? Comparing payload, speed, ISO/TS 15066 safety requirements, and integration costs in factory automation.",
    cr_page_title: "Industrial Robot or Cobot? Comparison and Analysis – NEXAUT",
    cr_h1: "Industrial Robot or Cobot? When Should You Choose a Collaborative Robot?",
    cr_intro: "Production process automation is no longer exclusive to giant corporations. Today, companies of all sizes face robotics decisions, asking: should we install a classic industrial robot or a flexible cobot? We break down key differences in speed, safety fencing, and return on investment.",
    cr_h2_1: "What Really Distinguishes a Cobot from an Industrial Robot?",
    cr_p1_1: "The primary difference lies not merely in physical dimensions, but in **safety philosophy and application design**. Traditional industrial robots (e.g., FANUC, KUKA, ABB) are built for maximum velocity, high payloads, and heavy duty. Cobots (Collaborative Robots), conversely, are designed to safely work alongside humans in shared workspaces.",
    cr_h2_2: "Technical Analysis: When to Select Each Solution?",
    cr_p2_intro: "Selecting the ideal manipulator comes down to analyzing your specific production process parameters:",
    cr_li_2_1: "<strong>Dynamics & Cycle Time:</strong> If your process requires sub-second cycles and high-speed material handling, traditional industrial robots remain unmatched. Cobots operate at lower speeds due to safety limits.",
    cr_li_2_2: "<strong>Payload & Reach:</strong> Traditional robots effortlessly manage loads from tens to hundreds of kilograms. Modern cobots handle payloads between 10–30 kg, ideal for palletizing or machine tending, but unsuitable for heavy foundry work.",
    cr_li_2_3: "<strong>Safety & Cages:</strong> Industrial robots strictly mandate protective physical fencing, light curtains, and safety interlocks. Cobots with integrated force sensors can operate without perimeter fences (subject to ISO/TS 15066 risk assessment).",
    cr_li_2_4: "<strong>Deployment & Footprint:</strong> Cobots are highly mobile, easily redeployed on mobile carts, and reprogrammed quickly. Industrial robot cells represent permanent, stationary installations.",
    cr_callout_title: "Common Myth: 'Cobots Never Require Safety Gear'",
    cr_callout_text: "Remember: the manipulator arm itself is safe, not necessarily the entire application! If your cobot carries sharp tooling, blades, or heated parts, safety scanners or guarding are still mandatory.",
    cr_img2_caption: "Fig 1. Cobot palletizing application operating in a space-constrained plant environment.",
    cr_h2_3: "Comparison Table: Industrial Robot vs. Cobot",
    cr_h2_faq: "Frequently Asked Questions (FAQ)",
    cr_faq_q1: "Is a cobot cheaper than a traditional industrial robot?",
    cr_faq_a1: "The bare cobot arm is often costlier than an equivalent industrial arm due to built-in force sensors. However, total integration costs are frequently lower because protective fencing and complex safety hardware are reduced.",
    cr_faq_q2: "Do you need a dedicated software engineer to program a cobot?",
    cr_faq_a2: "Simple tasks (like basic Pick & Place) can be programmed by plant operators using drag-and-drop interfaces or hand guiding. Complex multi-PLC line integrations still benefit from professional engineering support.",
    cr_faq_q3: "How does NEXAUT assist with robot selection and integration?",
    cr_faq_a3: "NEXAUT delivers full feasibility studies, ISO/TS 15066 risk assessments, and cycle-time simulations. We guide you from selecting the optimal brand to end-effector tooling, complete PLC programming, and CE certification.",
    cr_h2_5: "Summary – Drive Smart Robotics with NEXAUT",
    cr_p5_1: "Neither technology is universally 'better' – both cobots and traditional industrial robots serve distinct ideal use cases. Base your choice on required cycle time, floor footprint, and budget. Contact NEXAUT today to evaluate your production line and implement the optimal robotic solution."
  },

  de: {
    cr_meta_desc: "Cobot oder Industrieroboter? Vergleich von Traglast, Geschwindigkeit, ISO/TS 15066 Sicherheitsanforderungen und Integrationskosten.",
    cr_page_title: "Industrieroboter oder Cobot? Vergleich und Analyse – NEXAUT",
    cr_h1: "Industrieroboter oder Cobot? Wann lohnt sich ein kollaborativer Roboter?",
    cr_intro: "Die Automatisierung von Fertigungsprozessen ist längst kein Privileg von Großkonzernen mehr. Unternehmen jeder Größe stehen vor der Frage: Klassischer Industrieroboter oder flexibler Cobot? Wir erklären die wesentlichen Unterschiede bei Dynamik, Schutzumzäunung und ROI.",
    cr_h2_1: "Was unterscheidet einen Cobot wirklich von einem Industrieroboter?",
    cr_p1_1: "Der Hauptunterschied liegt nicht nur in der Optik, sondern in der **Sicherheitsphilosophie und dem Anwendungszweck**. Traditionelle Industrieroboter (z. B. FANUC, KUKA, ABB) sind auf maximale Ausbringung und schwere Traglasten ausgelegt. Cobots (Collaborative Robots) wurden entwickelt, um sicher Seite an Seite mit dem Menschen im gemeinsamen Arbeitsraum zu agieren.",
    cr_h2_2: "Technische Analyse: Wann wählt man welches System?",
    cr_p2_intro: "Die Wahl des passenden Manipulators hängt von Ihren Prozessparametern ab:",
    cr_li_2_1: "<strong>Dynamik & Taktzeit:</strong> Erfordert Ihr Prozess extrem kurze Taktzeiten und hohe Geschwindigkeiten, ist der Industrieroboter unschlagbar. Cobots bewegen sich aus Sicherheitsgründen langsamer.",
    cr_li_2_2: "<strong>Traglast & Reichweite:</strong> Industrieroboter bewältigen problemlos Hunderte Kilogramm. Moderne Cobots bieten Traglasten von 10–30 kg – ideal für Palettierung und Maschinenbestückung.",
    cr_li_2_3: "<strong>Sicherheit & Schutzgitter:</strong> Industrieroboter erfordern zwingend Schutzzäune und Lichtschranken. Cobots mit integrierter Sensorik können nach ISO/TS 15066 Risikobeurteilung zaunlos betrieben werden.",
    cr_li_2_4: "<strong>Flexibilität & Platzbedarf:</strong> Cobots lassen sich einfach auf mobilen Gestellen verfahren und umprogrammieren. Roboterzellen sind meist stationäre Festinstallationen.",
    cr_callout_title: "Denkfalle: „Ein Cobot braucht nie Sicherheitstechnik“",
    cr_callout_text: "Achtung: Sicher ist nur der Roboterarm, nicht zwingend die Gesamtanwendung! Greift der Cobot scharfe oder heiße Werkstücke, sind weiterhin Sicherheitsscanner oder Schutzeinrichtungen erforderlich.",
    cr_img2_caption: "Abb. 1. Cobot-Palettierer auf engem Raum in einer Produktionshalle.",
    cr_h2_3: "Vergleichstabelle: Industrieroboter vs. Cobot",
    cr_h2_faq: "Häufig gestellte Fragen (FAQ)",
    cr_faq_q1: "Ist ein Cobot günstiger in der Anschaffung als ein Industrieroboter?",
    cr_faq_a1: "Der reine Roboterarm ist wegen der feinen Sensorik oft teurer. Die Gesamtkosten der Integration sind bei Cobots jedoch häufig geringer, da aufwendige Schutzzäune entfallen.",
    cr_faq_q2: "Benötigt man zur Cobot-Programmierung einen Roboterspezialisten?",
    cr_faq_a2: "Einfache Aufgaben (Pick & Place) können Bediener nach kurzer Einweisung per Touchpanel oder Handführung teachen. Bei komplexer SPS-Einbindung wird Expertenunterstützung empfohlen.",
    cr_faq_q3: "Wie unterstützt NEXAUT bei Auswahl und Integration?",
    cr_faq_a3: "NEXAUT führt Machbarkeitsstudien, Risikobeurteilungen nach ISO/TS 15066 sowie Taktzeitsimulationen durch. Wir begleiten Sie von der Herstellerauswahl über Greifertechnik bis zur CE-Zertifizierung.",
    cr_h2_5: "Zusammenfassung – Erfolgreiche Robotisierung mit NEXAUT",
    cr_p5_1: "Es gibt kein pauschal „besseres“ System – sowohl Cobots als auch Industrieroboter haben ihre Berechtigung. Entscheidend sind Taktzeit, Platz und Budget. Kontaktieren Sie NEXAUT für eine maßgeschneiderte Beratung."
  }
};