window.POST_TRANSLATIONS = {
  pl: {
    log_meta_desc: "Robotyzacja magazynów i&nbsp;intralogistyki w&nbsp;Łodzi, Poznaniu, Warszawie i&nbsp;Wrocławiu. Roboty AMR/AGV, przenośniki i&nbsp;integracja WMS z&nbsp;PLC od&nbsp;NEXAUT.",
    log_page_title: "Robotyzacja Magazynów i Intralogistyka: Łódź, Poznań, Warszawa, Wrocław – NEXAUT",
    log_h1: "Robotyzacja logistyki i&nbsp;intralogistyki w&nbsp;Polsce Centralnej – Łódź, Poznań, Warszawa i&nbsp;Wrocław",
    log_intro: "Polska Centralna i&nbsp;Zachodnia stanowią kluczowy węzeł dystrybucyjny dla całej Europy. Skrzyżowanie autostrad A1, A2 i&nbsp;A4 w&nbsp;okolicach Łodzi, Poznania, Warszawy i&nbsp;Wrocławia skupia miliony metrów kwadratowych nowoczesnych powierzchni magazynowych. W&nbsp;obliczu rosnącego wolumenu e-commerce i&nbsp;braku rąk do&nbsp;pracy, automatyzacja intralogistyki stała się tu&nbsp;priorytetem.",
    log_h2_1: "1. Cztery filary logistycznego serca Polski",
    log_p1_1: "Każdy z&nbsp;głównych aglomeracyjnych węzłów charakteryzuje się odmienną specyfiką operacyjną i&nbsp;techniczną:",
    
    // Huby
    log_hub1_title: "Centralny Hub &amp; E-Commerce",
    log_hub1_desc: "Serce polskiej logistyki. Gigantyczne centra fulfillmentowe nakierowane na&nbsp;ultraszybką wysyłkę paczek, wykorzystujące sortery pętlowe oraz&nbsp;floty robotów AMR.",
    log_hub2_title: "Brama na&nbsp;Europę Zachodnią",
    log_hub2_desc: "Logistyka kontraktowa i&nbsp;obsługa rynku niemieckiego. Wysoki stopień automatyzacji regałów wysokiego składowania (ASRS) oraz&nbsp;transportu paletowego.",
    log_hub3_title: "Logistyka Miejska &amp; Last-Mile",
    log_hub3_desc: "Magazyny typu Cross-Dock i&nbsp;centra miejskie (City Logistics). Nacisk na&nbsp;elastyczność, szybki rozładunek TIR-ów oraz&nbsp;automatyczne depaletyzatory.",
    log_hub4_title: "Intralogistyka Przemysłowa",
    log_hub4_desc: "Połączenie logistyki magazynowej z&nbsp;produkcją. Roboty AGV dostarczające komponenty bezpośrednio na&nbsp;linie montażowe w&nbsp;trybie Just-in-Time.",

    log_h2_2: "2. Kluczowe technologie robotyzacji intralogistyki",
    log_p2_1: "Nowoczesne magazyny odchodzą od&nbsp;ręcznego transportu wózkami widłowymi na&nbsp;rzecz zintegrowanych systemów autonomicznych i&nbsp;transportu ciągłego:",
    log_li_1: "<strong class=\"text-white\">Roboty AMR (Autonomous Mobile Robots):</strong> Nawigują dynamicznie bez&nbsp;konieczności modyfikacji posadzki (SLAM 2D/3D). Świetnie sprawdzają się w&nbsp;transporcie pojemników i&nbsp;palet.",
    log_li_2: "<strong class=\"text-white\">Roboty AGV (Automated Guided Vehicles):</strong> Dedykowane do&nbsp;ciężkich ładunków paletowych na&nbsp;stałych, precyzyjnie wyznaczonych trasach transportowych.",
    log_li_3: "<strong class=\"text-white\">Systemy przenośników i&nbsp;Sorterów:</strong> Zaawansowane linie rolkowe i&nbsp;paskowe sterowane przez PLC (Siemens S7-1500 / Beckhoff), osiągające przepustowość tysięcy paczek na&nbsp;godzinę.",
    log_li_4: "<strong class=\"text-white\">Warstwa integracji WMS / WCS ze&nbsp;sterownikami PLC:</strong> Płynna wymiana danych w&nbsp;czasie rzeczywistym między systemem zarządzania magazynem a&nbsp;warstwą wykonawczą.",

    log_callout_title: "NEXAUT – Kompleksowa Integracja Systemów Intralogistycznych",
    log_callout_text: "Inżynierowie NEXAUT łączą świat automatyki przemysłowej (PLC, robotyka) z&nbsp;systemami zarządczymi (WMS/WCS). Projektujemy i&nbsp;programujemy układy sterowania dla linii transportu palet, sorterów oraz&nbsp;stanowisk automatycznej paletyzacji w&nbsp;obiektach logistycznych w&nbsp;Łodzi, Poznaniu, Warszawie i&nbsp;Wrocławiu.",
    log_h2_faq: "Często Zadawane Pytania (FAQ)",
    log_faq_q1: "Czym różni się robot AMR od&nbsp;robota AGV?",
    log_faq_a1: "Robot AGV porusza się po&nbsp;wyznaczonej ścieżce (np.&nbsp;taśmie magnetycznej lub&nbsp;pętlach indukcyjnych) i&nbsp;zatrzymuje po&nbsp;napotkaniu przeszkody. Robot AMR analizuje otoczenie w&nbsp;czasie rzeczywistym i&nbsp;potrafi samodzielnie ominąć przeszkodę, wyznaczając nową trasę.",
    log_faq_q2: "Jak wygląda integracja sterowników PLC z&nbsp;systemami magazynowymi WMS/ERP?",
    log_faq_a2: "Integracja odbywa się poprzez dedykowaną warstwę oprogramowania pośredniczącego (WCS – Warehouse Control System) z&nbsp;wykorzystaniem protokołów OPC UA, TCP/IP lub&nbsp;dedykowanych API REST, zapewniając wymianę danych o&nbsp;statusie palet w&nbsp;milisekundach.",
    log_faq_q3: "Jaki jest średni czas zwrotu z&nbsp;inwestycji (ROI) w&nbsp;automatyzację intralogistyki?",
    log_faq_a3: "W&nbsp;zależności od&nbsp;skali operacji i&nbsp;trybu pracy magazynu (np.&nbsp;praca 24/7), zwrot z&nbsp;inwestycji w&nbsp;roboty mobilne lub&nbsp;zautomatyzowane linie przenośników następuje zazwyczaj w&nbsp;okresie od&nbsp;18 do&nbsp;36 miesięcy.",
    log_h2_5: "Podsumowanie – Przyspiesz swój przepływ materiałów",
    log_p5_1: "Wydajna intralogistyka to&nbsp;klucz do&nbsp;przewagi konkurencyjnej w&nbsp;nowoczesnym handlu i&nbsp;produkcji. Szukasz wsparcia przy programowaniu i&nbsp;wdrażaniu systemów automatyki w&nbsp;obiektach magazynowych w&nbsp;Polsce Centralnej lub&nbsp;Zachodniej? Skontaktuj się z&nbsp;zespołem NEXAUT!"
  },

  en: {
    log_meta_desc: "Warehouse and intralogistics robotics in Łódź, Poznań, Warsaw, and Wrocław. AMR/AGV robots, conveyors, and WMS to PLC integration by NEXAUT.",
    log_page_title: "Logistics Robotics & Intralogistics: Łódź, Poznań, Warsaw, Wrocław – NEXAUT",
    log_h1: "Logistics &amp; intralogistics robotics in Central Poland – Łódź, Poznań, Warsaw, and Wrocław",
    log_intro: "Central and Western Poland form a vital logistics hub for European trade. The intersection of A1, A2, and A4 highways hosts millions of square meters of modern warehousing. Intralogistics automation is crucial to match rising e-commerce demand.",
    log_h2_1: "1. Four Pillars of Poland's Logistics Heart",
    log_p1_1: "Each key metropolitan logistics node presents unique operational characteristics:",
    log_hub1_title: "Central Hub &amp; E-Commerce",
    log_hub1_desc: "The core of Polish logistics. Massive fulfillment hubs utilizing loop sorters and AMR fleets for fast shipping.",
    log_hub2_title: "Gateway to Western Europe",
    log_hub2_desc: "Contract logistics serving Western European markets. High adoption of ASRS automated high-bay racking and pallet transport.",
    log_hub3_title: "City Logistics &amp; Last-Mile",
    log_hub3_desc: "Cross-dock terminals and urban logistics hubs prioritizing flexible unloading and automatic depalletizing.",
    log_hub4_title: "Industrial Intralogistics",
    log_hub4_desc: "Direct integration between warehouse and manufacturing. AGVs delivering components directly to assembly lines Just-in-Time.",
    log_h2_2: "2. Key Technologies in Intralogistics Robotics",
    log_p2_1: "Modern logistics shifts away from manual forklifts towards integrated autonomous transport:",
    log_li_1: "<strong class=\"text-white\">AMR Robots (Autonomous Mobile Robots):</strong> Dynamic navigation using 2D/3D SLAM without floor modification for tote and pallet moving.",
    log_li_2: "<strong class=\"text-white\">AGV Robots (Automated Guided Vehicles):</strong> Dedicated heavy-duty pallet haulers running along fixed, highly reliable routes.",
    log_li_3: "<strong class=\"text-white\">Conveyors &amp; Sorters:</strong> Advanced roller/belt conveyor lines managed by Siemens or Beckhoff PLCs processing thousands of parcels per hour.",
    log_li_4: "<strong class=\"text-white\">WMS / WCS to PLC Integration:</strong> Real-time millisecond data sync between warehouse management software and PLC hardware.",
    log_callout_title: "NEXAUT – End-to-End Intralogistics Systems Integration",
    log_callout_text: "NEXAUT engineers bridge industrial automation (PLC, robotics) with management software (WMS/WCS) for warehouses in Łódź, Poznań, Warsaw, and Wrocław.",
    log_h2_faq: "Frequently Asked Questions (FAQ)",
    log_faq_q1: "What is the difference between an AMR and an AGV?",
    log_faq_a1: "An AGV follows a fixed track and stops at obstacles. An AMR dynamically scans its environment and calculates new routes around obstacles autonomously.",
    log_faq_q2: "How are PLCs integrated with WMS/ERP systems?",
    log_faq_a2: "Integration uses a WCS middleware layer communicating via OPC UA, TCP/IP, or REST APIs to exchange real-time status data.",
    log_faq_q3: "What is the average ROI for warehouse automation?",
    log_faq_a3: "Depending on operating hours (e.g., 24/7 shifts), ROI for mobile robotics and automated conveyors typically ranges from 18 to 36 months.",
    log_h2_5: "Summary – Accelerate Your Material Flow",
    log_p5_1: "Efficient intralogistics is key to maintaining competitive advantage. Planning an automation project in Central or Western Poland? Contact NEXAUT today!"
  },

  de: {
    log_meta_desc: "Lagerrobotik und Intralogistik in Łódź, Posen, Warschau und Breslau. AMR/AGV-Roboter, Fördertechnik und WMS-PLC-Integration von NEXAUT.",
    log_page_title: "Lagerrobotik & Intralogistik: Łódź, Posen, Warschau, Breslau – NEXAUT",
    log_h1: "Robotik in Logistik und Intralogistik in Zentralpolen – Łódź, Posen, Warschau und Breslau",
    log_intro: "Zentral- und Westpolen bilden einen zentralen Logistikknotenpunkt für Europa. Das Autobahnnetz beherbergt Millionen von Quadratmetern moderner Logistikflächen.",
    log_h2_1: "1. Die vier Säulen des polnischen Logistikzentrums",
    log_p1_1: "Jeder Standort weist spezifische logistische Schwerpunkte auf:",
    log_hub1_title: "Zentraler Hub &amp; E-Commerce",
    log_hub1_desc: "Fulfillment-Zentren mit Sortersystemen und AMR-Flotten für extrem schnelle Paketauslieferung.",
    log_hub2_title: "Tor nach Westeuropa",
    log_hub2_desc: "Kontraktlogistik für den europäischen Markt mit automatisierten Hochregallagern (AKL/HRL).",
    log_hub3_title: "City-Logistik &amp; Last-Mile",
    log_hub3_desc: "Cross-Dock-Terminals für schnelle Entladung und automatische Depalettierung.",
    log_hub4_title: "Industrielle Intralogistik",
    log_hub4_desc: "Direkte Verbindung von Lager und Produktion. AGVs liefern Bauteile Just-in-Time an Montagelinien.",
    log_h2_2: "2. Schlüsseltechnologien der Intralogistik-Robotik",
    log_p2_1: "Die Intralogistik setzt zunehmend auf autonome Transportsysteme:",
    log_li_1: "<strong class=\"text-white\">AMR-Roboter (Autonome Mobile Roboter):</strong> Freie Navigation mittels SLAM 2D/3D zum Transport von Behältern und Paletten.",
    log_li_2: "<strong class=\"text-white\">FTS/AGV-Systeme:</strong> Fahrerlose Transportsysteme für schwere Lasten auf festen Routen.",
    log_li_3: "<strong class=\"text-white\">Fördertechnik &amp; Sorter:</strong> SPS-gesteuerte Rollen- und Gurtförderer mit hoher Paketdurchsatzrate.",
    log_li_4: "<strong class=\"text-white\">WMS/WCS-SPS-Kopplung:</strong> Nahtlose Datenübertragung in Echtzeit zwischen Lagerverwaltung und SPS.",
    log_callout_title: "NEXAUT – Ihr Partner für Intralogistik und Mobilrobotik",
    log_callout_text: "NEXAUT verbindet industrielle Automatisierung mit Softwarelösungen für Logistikzentren in Łódź, Posen, Warschau und Breslau.",
    log_h2_faq: "Häufig gestellte Fragen (FAQ)",
    log_faq_q1: "Was ist der Unterschied zwischen AMR und AGV?",
    log_faq_a1: "Ein AGV folgt einer festen Spur, während ein AMR dank freier Navigation Hindernisse selbstständig umfahren kann.",
    log_faq_q2: "Wie erfolgt die Anbindung der SPS an WMS-Systeme?",
    log_faq_a2: "Über eine WCS-Zwischenschicht mittels OPC UA, TCP/IP oder REST-Schnittstellen.",
    log_faq_q3: "Wie hoch ist der ROI für die Automatisierung der Intralogistik?",
    log_faq_a3: "Je nach Betriebszeiten liegt die Amortisationszeit meist zwischen 18 und 36 Monaten.",
    log_h2_5: "Zusammenfassung – Materialfluss optimieren",
    log_p5_1: "Effiziente Intralogistik sichert Wettbewerbsvorteile. Benötigen Sie Unterstützung bei Automatisierungsprojekten? Kontaktieren Sie NEXAUT!"
  }
};